import type {
  DependencyTemplate,
  LifeEventTypeCode,
  LifeEventTypeDefinition,
  LifeEventTypeSummary,
  MilestoneTemplate,
} from "@/lib/continuity-os/taxonomy/types";

const employmentMilestones: MilestoneTemplate[] = [
  {
    code: "information_gathered",
    label: "Information gathered",
    required: true,
    defaultOwnerRole: "participant",
  },
  {
    code: "decision_made",
    label: "Decision made",
    required: true,
    defaultOwnerRole: "participant",
  },
  {
    code: "employer_confirmed",
    label: "Employer confirmed",
    required: true,
    defaultOwnerRole: "employer",
  },
  {
    code: "equipment_ordered",
    label: "Equipment arranged",
    required: false,
    defaultOwnerRole: "participant",
  },
  {
    code: "transport_arranged",
    label: "Accessible transport arranged",
    required: true,
    defaultOwnerRole: "transport_operator",
  },
  {
    code: "support_roster_confirmed",
    label: "Support roster confirmed",
    required: false,
    defaultOwnerRole: "provider_manager",
  },
  {
    code: "service_commenced",
    label: "First day commenced",
    required: true,
    defaultOwnerRole: "participant",
  },
  {
    code: "outcome_reviewed",
    label: "Outcome reviewed",
    required: true,
    defaultOwnerRole: "participant",
  },
];

const startJobDependencies: DependencyTemplate[] = [
  {
    code: "participant_goal",
    label: "Participant goal",
    domain: "mission",
    required: true,
    defaultOwnerRole: "participant",
  },
  {
    code: "workplace_entrance",
    label: "Accessible workplace entrance",
    domain: "access",
    required: true,
    defaultOwnerRole: "employer",
    alternativeHint: "Alternate verified entrance if available",
  },
  {
    code: "lift",
    label: "Required lift or level access",
    domain: "access",
    required: false,
    defaultOwnerRole: "venue",
    alternativeHint: "Verified alternate lift or route",
  },
  {
    code: "first_day_adjustment",
    label: "First-day workplace adjustment",
    domain: "jobs",
    required: false,
    defaultOwnerRole: "employer",
  },
  {
    code: "accessible_transport",
    label: "Accessible transport",
    domain: "transport",
    required: true,
    defaultOwnerRole: "transport_operator",
    alternativeHint: "Replacement accessible vehicle or reschedule",
  },
  {
    code: "morning_support_worker",
    label: "Morning support worker",
    domain: "care",
    required: false,
    defaultOwnerRole: "provider_manager",
    alternativeHint: "Backup worker or changed departure time",
  },
  {
    code: "equipment_charger",
    label: "Chair charger or essential equipment",
    domain: "equipment",
    required: false,
    defaultOwnerRole: "participant",
  },
  {
    code: "arrival_deadline",
    label: "Arrival before start time",
    domain: "calendar",
    required: true,
    defaultOwnerRole: "participant",
  },
  {
    code: "employer_contact",
    label: "Employer contact for changes",
    domain: "jobs",
    required: false,
    defaultOwnerRole: "employer",
  },
  {
    code: "communication_mode",
    label: "Preferred communication mode",
    domain: "messaging",
    required: true,
    defaultOwnerRole: "participant",
  },
];

function def(
  partial: Omit<
    LifeEventTypeDefinition,
    "version" | "prohibitedAutomatedDecisions" | "reviewOwner"
  > &
    Partial<
      Pick<
        LifeEventTypeDefinition,
        "prohibitedAutomatedDecisions" | "reviewOwner" | "version"
      >
    >
): LifeEventTypeDefinition {
  return {
    version: partial.version ?? "1.0.0",
    reviewOwner: partial.reviewOwner ?? "continuity-os-product",
    prohibitedAutomatedDecisions: partial.prohibitedAutomatedDecisions ?? [
      "assign_worker",
      "book_transport",
      "cancel_service",
      "approve_refund",
      "determine_clinical_readiness",
      "determine_legal_eligibility",
      "close_incident",
      "override_access_passport",
    ],
    ...partial,
  };
}

const REGISTRY: LifeEventTypeDefinition[] = [
  def({
    code: "start_job",
    category: "EMPLOYMENT",
    title: "Starting a job",
    plainLanguageDescription:
      "Plan the supports, transport, access and communication needed to begin work on the participant’s terms.",
    likelyDomains: ["jobs", "care", "transport", "access", "calendar", "equipment"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: [
      "offer_letter",
      "adjustment_request",
      "access_passport_slice",
      "transport_booking",
    ],
    commonHandoffs: [
      "provider_to_worker",
      "transport_to_venue",
      "navigator_to_employer",
    ],
    accessibilityBarriers: [
      "inaccessible_entrance",
      "lift_outage",
      "inaccessible_vehicle",
      "unclear_instructions",
    ],
    humanRoles: [
      "participant",
      "employer",
      "support_worker",
      "transport_operator",
      "navigator",
      "rights_officer",
    ],
    policySourceKeys: [
      "ndis_code_of_conduct",
      "privacy_act_1988",
      "wcag_2_2_aa",
      "mapable_masterplan_continuity",
    ],
    requiredWarnings: [
      "Templates are starting points only — not every person needs every step.",
      "A proposed replacement is not available until the service confirms it.",
      "Service failure is never the participant’s failure.",
    ],
  }),
  def({
    code: "begin_job_search",
    category: "EMPLOYMENT",
    title: "Beginning job search",
    plainLanguageDescription:
      "Organise job-search supports, adjustments and transport without scoring the person.",
    likelyDomains: ["jobs", "care", "transport", "rights"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "application_submitted", "outcome_reviewed"].includes(
        m.code
      )
    ),
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "communication_mode", "accessible_transport"].includes(d.code)
    ),
    commonDocuments: ["resume_slice", "adjustment_preferences"],
    commonHandoffs: ["navigator_to_employment_service"],
    accessibilityBarriers: ["inaccessible_application_forms", "unclear_instructions"],
    humanRoles: ["participant", "navigator", "employment_service"],
    policySourceKeys: ["privacy_act_1988", "mapable_masterplan_continuity"],
    requiredWarnings: ["Do not create a readiness or employability score."],
  }),
  def({
    code: "interview",
    category: "EMPLOYMENT",
    title: "Interview",
    plainLanguageDescription:
      "Coordinate access, transport and communication for an interview.",
    likelyDomains: ["jobs", "transport", "access", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["interview_invite", "adjustment_request"],
    commonHandoffs: ["transport_to_venue"],
    accessibilityBarriers: ["inaccessible_venue", "inaccessible_vehicle"],
    humanRoles: ["participant", "employer", "transport_operator", "support_worker"],
    policySourceKeys: ["privacy_act_1988", "wcag_2_2_aa"],
    requiredWarnings: ["Do not auto-notify an employer without approval."],
  }),
  def({
    code: "return_to_work",
    category: "EMPLOYMENT",
    title: "Returning to work",
    plainLanguageDescription:
      "Plan a return-to-work transition with participant-selected supports and timing.",
    likelyDomains: ["jobs", "care", "transport", "health"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["return_plan_slice", "adjustment_request"],
    commonHandoffs: ["clinician_to_navigator_nonclinical"],
    accessibilityBarriers: ["fatigue_unaccommodated", "inaccessible_schedule"],
    humanRoles: ["participant", "employer", "navigator", "clinical_coordinator"],
    policySourceKeys: ["privacy_act_1988", "ndis_code_of_conduct"],
    requiredWarnings: [
      "Clinical readiness remains clinician-controlled.",
      "ContinuityOS coordinates non-clinical dependencies only.",
    ],
  }),
  def({
    code: "change_role",
    category: "EMPLOYMENT",
    title: "Changing role",
    plainLanguageDescription: "Update workplace access and supports when a role changes.",
    likelyDomains: ["jobs", "access", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["role_change_notice"],
    commonHandoffs: ["employer_to_job_coach"],
    accessibilityBarriers: ["new_duties_inaccessible"],
    humanRoles: ["participant", "employer", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "change_workplace",
    category: "EMPLOYMENT",
    title: "Changing workplace",
    plainLanguageDescription: "Re-verify place access, transport and supports for a new site.",
    likelyDomains: ["jobs", "access", "transport", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["new_site_details"],
    commonHandoffs: ["transport_to_venue"],
    accessibilityBarriers: ["unverified_entrance"],
    humanRoles: ["participant", "employer", "transport_operator"],
    policySourceKeys: ["wcag_2_2_aa"],
    requiredWarnings: ["Do not treat an unverified venue claim as confirmed access."],
  }),
  def({
    code: "leave_employment",
    category: "EMPLOYMENT",
    title: "Leaving employment",
    plainLanguageDescription: "Wind down workplace supports and handoffs with participant control.",
    likelyDomains: ["jobs", "care", "rights"],
    milestones: [
      {
        code: "decision_made",
        label: "Decision made",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "handoff_accepted",
        label: "Handoff accepted",
        required: false,
        defaultOwnerRole: "navigator",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "consent_authority",
        label: "Disclosure authority for exit communications",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["exit_notice_draft"],
    commonHandoffs: ["navigator_to_provider"],
    accessibilityBarriers: ["inaccessible_exit_paperwork"],
    humanRoles: ["participant", "navigator", "rights_officer"],
    policySourceKeys: ["privacy_act_1988", "australian_consumer_law"],
    requiredWarnings: [],
  }),
  def({
    code: "retire",
    category: "EMPLOYMENT",
    title: "Retire",
    plainLanguageDescription: "Plan retirement transition across work, schemes and supports.",
    likelyDomains: ["jobs", "lifespan", "care", "rights"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: startJobDependencies.filter((d) => d.code === "participant_goal"),
    commonDocuments: ["scheme_transition_notes"],
    commonHandoffs: ["navigator_to_aged_care_partner"],
    accessibilityBarriers: ["inaccessible_scheme_forms"],
    humanRoles: ["participant", "navigator", "rights_officer"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Do not encode draft aged-care reforms as settled law."],
  }),
  def({
    code: "leave_school",
    category: "EDUCATION",
    title: "Leaving school",
    plainLanguageDescription: "Coordinate leaving-school transitions across pathways and supports.",
    likelyDomains: ["pathways", "care", "transport", "jobs"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "application_submitted", "outcome_reviewed"].includes(
        m.code
      )
    ),
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "communication_mode", "consent_authority"].includes(d.code)
    ),
    commonDocuments: ["school_exit_plan_slice"],
    commonHandoffs: ["school_to_navigator"],
    accessibilityBarriers: ["inaccessible_transition_meetings"],
    humanRoles: ["participant", "supporter", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Family authority rules may apply for minors — human review required."],
  }),
  def({
    code: "begin_university",
    category: "EDUCATION",
    title: "Beginning university",
    plainLanguageDescription: "Plan campus access, transport and support for university commencement.",
    likelyDomains: ["pathways", "access", "transport", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["enrolment_confirmation", "disability_support_registration"],
    commonHandoffs: ["navigator_to_campus_access"],
    accessibilityBarriers: ["campus_route_gaps"],
    humanRoles: ["participant", "navigator", "campus_access_officer"],
    policySourceKeys: ["wcag_2_2_aa", "privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "begin_tafe",
    category: "EDUCATION",
    title: "Beginning TAFE",
    plainLanguageDescription: "Plan TAFE commencement supports and access.",
    likelyDomains: ["pathways", "transport", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["enrolment_confirmation"],
    commonHandoffs: ["navigator_to_training_provider"],
    accessibilityBarriers: ["inaccessible_training_site"],
    humanRoles: ["participant", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "begin_school",
    category: "EDUCATION",
    title: "Beginning school",
    plainLanguageDescription: "Coordinate school commencement with family authority boundaries.",
    likelyDomains: ["kids", "care", "transport", "access"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["enrolment", "support_plan_slice"],
    commonHandoffs: ["family_to_school"],
    accessibilityBarriers: ["inaccessible_school_entry"],
    humanRoles: ["participant", "supporter", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Child safety and family authority require human review."],
  }),
  def({
    code: "change_school",
    category: "EDUCATION",
    title: "Changing school",
    plainLanguageDescription: "Transfer school-related supports and access information.",
    likelyDomains: ["kids", "care", "transport"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["transfer_pack"],
    commonHandoffs: ["school_to_school"],
    accessibilityBarriers: ["lost_adjustments"],
    humanRoles: ["participant", "supporter", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "begin_apprenticeship",
    category: "EDUCATION",
    title: "Beginning apprenticeship",
    plainLanguageDescription: "Coordinate apprenticeship workplace and training access.",
    likelyDomains: ["pathways", "jobs", "transport", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["apprenticeship_agreement_slice"],
    commonHandoffs: ["training_to_employer"],
    accessibilityBarriers: ["inaccessible_worksites"],
    humanRoles: ["participant", "employer", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "commence_placement",
    category: "EDUCATION",
    title: "Commencing placement",
    plainLanguageDescription: "Plan a time-bound education or training placement.",
    likelyDomains: ["pathways", "jobs", "transport"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["placement_brief"],
    commonHandoffs: ["campus_to_placement_site"],
    accessibilityBarriers: ["unverified_site_access"],
    humanRoles: ["participant", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "move_house",
    category: "HOME_AND_COMMUNITY",
    title: "Moving house",
    plainLanguageDescription: "Coordinate home access, equipment, supports and transport for a move.",
    likelyDomains: ["home", "equipment", "care", "transport"],
    milestones: [
      {
        code: "information_gathered",
        label: "Information gathered",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "property_selected",
        label: "Property selected",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "equipment_ordered",
        label: "Equipment arranged",
        required: false,
        defaultOwnerRole: "equipment_supplier",
      },
      {
        code: "support_roster_confirmed",
        label: "Support roster confirmed",
        required: false,
        defaultOwnerRole: "provider_manager",
      },
      {
        code: "handoff_accepted",
        label: "Handoff accepted",
        required: true,
        defaultOwnerRole: "navigator",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "home_access",
        label: "Home access (entrance, ramp, bathroom)",
        domain: "home",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "support_roster",
        label: "Support roster at new address",
        domain: "care",
        required: false,
        defaultOwnerRole: "provider_manager",
      },
      {
        code: "equipment_charger",
        label: "Essential equipment continuity",
        domain: "equipment",
        required: false,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["lease_slice", "modification_quote"],
    commonHandoffs: ["provider_to_provider", "equipment_supplier_to_repairer"],
    accessibilityBarriers: ["inaccessible_property", "equipment_delay"],
    humanRoles: ["participant", "navigator", "provider_manager", "equipment_supplier"],
    policySourceKeys: ["privacy_act_1988", "australian_consumer_law"],
    requiredWarnings: ["Do not guarantee battery range or clinical readiness."],
  }),
  def({
    code: "move_region",
    category: "HOME_AND_COMMUNITY",
    title: "Moving region",
    plainLanguageDescription: "Plan interstate or regional moves with capacity and provider changes.",
    likelyDomains: ["home", "regional", "care", "transport"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "support_roster", "accessible_transport"].includes(d.code)
    ),
    commonDocuments: ["address_change"],
    commonHandoffs: ["hub_to_spoke"],
    accessibilityBarriers: ["thin_market_capacity"],
    humanRoles: ["participant", "regional_navigator", "provider_manager"],
    policySourceKeys: ["privacy_act_1988", "mapable_masterplan_continuity"],
    requiredWarnings: ["Regional mutual aid never auto-assigns workers."],
  }),
  def({
    code: "search_for_housing",
    category: "HOME_AND_COMMUNITY",
    title: "Searching for housing",
    plainLanguageDescription: "Track housing search dependencies without scoring the participant.",
    likelyDomains: ["home", "rights"],
    milestones: [
      {
        code: "information_gathered",
        label: "Information gathered",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "property_selected",
        label: "Property shortlisted",
        required: false,
        defaultOwnerRole: "participant",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "home_access",
        label: "Access requirements for housing",
        domain: "home",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["housing_application_slice"],
    commonHandoffs: ["navigator_to_housing_partner"],
    accessibilityBarriers: ["inaccessible_listings"],
    humanRoles: ["participant", "navigator", "advocate"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "begin_independent_living",
    category: "HOME_AND_COMMUNITY",
    title: "Beginning independent living",
    plainLanguageDescription: "Plan independent living supports with participant authority.",
    likelyDomains: ["home", "care", "equipment"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["living_plan_slice"],
    commonHandoffs: ["family_to_adult_authority"],
    accessibilityBarriers: ["unsupported_daily_routines"],
    humanRoles: ["participant", "supporter", "navigator"],
    policySourceKeys: ["privacy_act_1988", "ndis_code_of_conduct"],
    requiredWarnings: ["Never infer cognitive capacity."],
  }),
  def({
    code: "home_modification",
    category: "HOME_AND_COMMUNITY",
    title: "Home modification",
    plainLanguageDescription: "Track home modification dependencies and temporary workarounds.",
    likelyDomains: ["home", "equipment", "care"],
    milestones: employmentMilestones,
    dependencies: [
      {
        code: "home_access",
        label: "Home access works",
        domain: "home",
        required: true,
        defaultOwnerRole: "equipment_supplier",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["modification_quote", "approval"],
    commonHandoffs: ["supplier_to_installer"],
    accessibilityBarriers: ["works_delay"],
    humanRoles: ["participant", "equipment_supplier", "navigator"],
    policySourceKeys: ["australian_consumer_law"],
    requiredWarnings: ["Temporary workarounds must have an expiry."],
  }),
  def({
    code: "change_household",
    category: "HOME_AND_COMMUNITY",
    title: "Changing household",
    plainLanguageDescription: "Update household support and disclosure boundaries.",
    likelyDomains: ["home", "care", "rights"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "consent_authority",
        label: "Authority and disclosure settings",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["authority_update"],
    commonHandoffs: ["supporter_change"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "rights_officer"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Family-violence safe mode may suppress default contacts."],
  }),
  def({
    code: "relationship_separation",
    category: "HOME_AND_COMMUNITY",
    title: "Relationship separation",
    plainLanguageDescription:
      "Support continuity planning during relationship separation with safety boundaries.",
    likelyDomains: ["home", "rights", "care"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "consent_authority",
        label: "Safe disclosure settings",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: [],
    commonHandoffs: ["specialist_human_pathway"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "rights_officer", "advocate"],
    policySourceKeys: ["privacy_act_1988", "family_violence_safe_handling"],
    requiredWarnings: [
      "Route safety concerns to authorised human services.",
      "AURA must never investigate or close the concern.",
    ],
    prohibitedAutomatedDecisions: [
      "assign_worker",
      "book_transport",
      "cancel_service",
      "approve_refund",
      "contact_supporter_by_default",
      "close_safeguarding_concern",
    ],
  }),
  def({
    code: "hospital_to_home",
    category: "HEALTH_AND_SUPPORT",
    title: "Hospital to home",
    plainLanguageDescription:
      "Coordinate non-clinical home, transport and support dependencies around a clinician-approved discharge.",
    likelyDomains: ["care", "transport", "home", "equipment"],
    milestones: [
      {
        code: "information_gathered",
        label: "Non-clinical dependencies listed",
        required: true,
        defaultOwnerRole: "navigator",
      },
      {
        code: "transport_arranged",
        label: "Transport arranged",
        required: false,
        defaultOwnerRole: "transport_operator",
      },
      {
        code: "support_roster_confirmed",
        label: "Home support roster confirmed",
        required: false,
        defaultOwnerRole: "provider_manager",
      },
      {
        code: "handoff_accepted",
        label: "Discharge handoff accepted",
        required: true,
        defaultOwnerRole: "discharge_coordinator",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "discharge_authority",
        label: "Clinician-approved discharge decision",
        domain: "health",
        required: true,
        defaultOwnerRole: "clinical_coordinator",
      },
      {
        code: "home_access",
        label: "Home access readiness",
        domain: "home",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "support_roster",
        label: "Home support roster",
        domain: "care",
        required: true,
        defaultOwnerRole: "provider_manager",
      },
      {
        code: "accessible_transport",
        label: "Accessible transport",
        domain: "transport",
        required: false,
        defaultOwnerRole: "transport_operator",
      },
    ],
    commonDocuments: ["discharge_summary_slice"],
    commonHandoffs: ["hospital_to_transport", "hospital_to_home_provider"],
    accessibilityBarriers: ["unconfirmed_ramp", "unconfirmed_roster"],
    humanRoles: [
      "participant",
      "clinical_coordinator",
      "discharge_coordinator",
      "navigator",
      "provider_manager",
    ],
    policySourceKeys: ["privacy_act_1988", "oaic_health_privacy_guide", "ndis_code_of_conduct"],
    requiredWarnings: [
      "Clinical readiness remains clinician-controlled.",
      "Mission must not become ready on AURA authority alone.",
      "Unknown home access must remain unknown until verified.",
    ],
  }),
  def({
    code: "hospital_admission",
    category: "HEALTH_AND_SUPPORT",
    title: "Hospital admission",
    plainLanguageDescription: "Pause or adapt community supports around a hospital admission.",
    likelyDomains: ["care", "transport", "rights"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "consent_authority",
        label: "Hospital disclosure authority",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: [],
    commonHandoffs: ["provider_to_hospital_liaison"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "navigator", "clinical_coordinator"],
    policySourceKeys: ["privacy_act_1988", "oaic_health_privacy_guide"],
    requiredWarnings: ["ContinuityOS is not a clinical record."],
  }),
  def({
    code: "rehabilitation_transition",
    category: "HEALTH_AND_SUPPORT",
    title: "Rehabilitation transition",
    plainLanguageDescription: "Coordinate non-clinical dependencies during rehabilitation transitions.",
    likelyDomains: ["care", "transport", "equipment"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["rehab_schedule_slice"],
    commonHandoffs: ["rehab_to_community_provider"],
    accessibilityBarriers: ["transport_timing"],
    humanRoles: ["participant", "navigator", "clinical_coordinator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Clinical decisions remain with authorised clinicians."],
  }),
  def({
    code: "new_equipment",
    category: "HEALTH_AND_SUPPORT",
    title: "New equipment",
    plainLanguageDescription: "Track ordering, delivery and setup of assistive equipment.",
    likelyDomains: ["equipment", "care", "transport"],
    milestones: [
      {
        code: "equipment_ordered",
        label: "Equipment ordered",
        required: true,
        defaultOwnerRole: "equipment_supplier",
      },
      {
        code: "service_commenced",
        label: "Equipment in use",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "equipment_charger",
        label: "Equipment and accessories",
        domain: "equipment",
        required: true,
        defaultOwnerRole: "equipment_supplier",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["equipment_passport_slice", "quote"],
    commonHandoffs: ["supplier_to_participant"],
    accessibilityBarriers: ["delivery_delay", "incompatible_accessory"],
    humanRoles: ["participant", "equipment_supplier", "repairer"],
    policySourceKeys: ["australian_consumer_law"],
    requiredWarnings: ["Do not guarantee equipment performance ranges."],
  }),
  def({
    code: "equipment_replacement",
    category: "HEALTH_AND_SUPPORT",
    title: "Equipment replacement",
    plainLanguageDescription: "Plan replacement while preserving temporary continuity options.",
    likelyDomains: ["equipment", "care", "transport"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "equipment_charger", "accessible_transport"].includes(d.code)
    ),
    commonDocuments: ["repair_record", "loan_options"],
    commonHandoffs: ["supplier_to_repairer"],
    accessibilityBarriers: ["no_loaner"],
    humanRoles: ["participant", "repairer", "navigator"],
    policySourceKeys: ["australian_consumer_law"],
    requiredWarnings: ["Separate temporary and long-term recovery."],
  }),
  def({
    code: "provider_change",
    category: "HEALTH_AND_SUPPORT",
    title: "Changing provider",
    plainLanguageDescription: "Hand over services between providers with minimal disclosure.",
    likelyDomains: ["care", "rights", "transport"],
    milestones: employmentMilestones,
    dependencies: [
      {
        code: "support_roster",
        label: "New provider roster",
        domain: "care",
        required: true,
        defaultOwnerRole: "provider_manager",
      },
      {
        code: "consent_authority",
        label: "Disclosure to new provider",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["service_agreement_slice"],
    commonHandoffs: ["provider_to_provider"],
    accessibilityBarriers: ["lost_preferences"],
    humanRoles: ["participant", "provider_manager", "rights_officer"],
    policySourceKeys: ["ndis_code_of_conduct", "privacy_act_1988"],
    requiredWarnings: ["Do not replace a provider automatically."],
  }),
  def({
    code: "primary_carer_loss",
    category: "HEALTH_AND_SUPPORT",
    title: "Primary carer unavailable",
    plainLanguageDescription:
      "Activate participant-approved continuity options when a primary informal carer is unavailable.",
    likelyDomains: ["care", "rights", "carer_continuity"],
    milestones: [
      {
        code: "information_gathered",
        label: "Approved continuity plan loaded",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "support_roster_confirmed",
        label: "Backup support confirmed",
        required: false,
        defaultOwnerRole: "navigator",
      },
      {
        code: "outcome_reviewed",
        label: "Coverage reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "backup_carer",
        label: "Backup support",
        domain: "care",
        required: false,
        defaultOwnerRole: "navigator",
      },
      {
        code: "consent_authority",
        label: "Handover disclosure limits",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["carer_continuity_plan_slice"],
    commonHandoffs: ["carer_to_backup_minimal"],
    accessibilityBarriers: ["no_backup_coverage"],
    humanRoles: ["participant", "navigator", "provider_manager"],
    policySourceKeys: ["privacy_act_1988", "ndis_code_of_conduct"],
    requiredWarnings: [
      "Do not grant the carer full account access.",
      "Distinguish planned respite from emergency support.",
    ],
  }),
  def({
    code: "new_support_arrangement",
    category: "HEALTH_AND_SUPPORT",
    title: "New support arrangement",
    plainLanguageDescription: "Set up a new support arrangement with clear responsibilities.",
    likelyDomains: ["care", "rights", "calendar"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "morning_support_worker", "consent_authority"].includes(d.code)
    ),
    commonDocuments: ["service_agreement_slice"],
    commonHandoffs: ["navigator_to_provider"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "provider_manager", "navigator"],
    policySourceKeys: ["ndis_code_of_conduct"],
    requiredWarnings: [],
  }),
  def({
    code: "become_a_parent",
    category: "FAMILY_AND_IDENTITY",
    title: "Becoming a parent",
    plainLanguageDescription: "Plan parenting-related support changes with participant control.",
    likelyDomains: ["care", "home", "rights"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "support_roster_confirmed", "outcome_reviewed"].includes(
        m.code
      )
    ),
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "support_roster",
        label: "Support roster changes",
        domain: "care",
        required: false,
        defaultOwnerRole: "provider_manager",
      },
    ],
    commonDocuments: [],
    commonHandoffs: ["navigator_to_family_support"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "navigator", "advocate"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "family_change",
    category: "FAMILY_AND_IDENTITY",
    title: "Family change",
    plainLanguageDescription: "Update family-related authority and support arrangements.",
    likelyDomains: ["rights", "care"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "consent_authority",
        label: "Authority settings",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: [],
    commonHandoffs: ["rights_officer_review"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "rights_officer"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "bereavement",
    category: "FAMILY_AND_IDENTITY",
    title: "Bereavement",
    plainLanguageDescription: "Support continuity after bereavement without rushing automation.",
    likelyDomains: ["care", "rights", "home"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "backup_carer",
        label: "Backup support",
        domain: "care",
        required: false,
        defaultOwnerRole: "navigator",
      },
    ],
    commonDocuments: [],
    commonHandoffs: ["human_coordinator"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "navigator", "advocate"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Prefer human coordination; avoid automated outreach pressure."],
  }),
  def({
    code: "transition_to_adult_authority",
    category: "FAMILY_AND_IDENTITY",
    title: "Transition to adult-controlled information",
    plainLanguageDescription:
      "Move from family-managed to adult-controlled information and authority with explicit approvals.",
    likelyDomains: ["rights", "vault", "care"],
    milestones: [
      {
        code: "decision_made",
        label: "Authority decision recorded",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "handoff_accepted",
        label: "Authority handoff accepted",
        required: true,
        defaultOwnerRole: "rights_officer",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "consent_authority",
        label: "Adult authority settings",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["authority_grant_update"],
    commonHandoffs: ["family_to_adult_authority"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "rights_officer", "supporter"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Never infer legal capacity."],
  }),
  def({
    code: "change_supporter_or_nominee",
    category: "FAMILY_AND_IDENTITY",
    title: "Changing supporter or nominee",
    plainLanguageDescription: "Update nominee/supporter access with purpose-bound permissions.",
    likelyDomains: ["rights", "vault"],
    milestones: employmentMilestones.filter((m) =>
      ["decision_made", "handoff_accepted", "outcome_reviewed"].includes(m.code)
    ),
    dependencies: [
      {
        code: "consent_authority",
        label: "Nominee authority",
        domain: "rights",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["authority_grant_update"],
    commonHandoffs: ["rights_officer_review"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "rights_officer"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "change_communication_method",
    category: "FAMILY_AND_IDENTITY",
    title: "Changing communication method",
    plainLanguageDescription: "Update accessible communication preferences across services.",
    likelyDomains: ["messaging", "access", "rights"],
    milestones: [
      {
        code: "decision_made",
        label: "Communication method selected",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "outcome_reviewed",
        label: "Outcome reviewed",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    dependencies: [
      {
        code: "communication_mode",
        label: "Communication mode",
        domain: "messaging",
        required: true,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: [],
    commonHandoffs: [],
    accessibilityBarriers: ["channel_unavailable"],
    humanRoles: ["participant"],
    policySourceKeys: ["wcag_2_2_aa"],
    requiredWarnings: [],
  }),
  def({
    code: "ndis_plan_change",
    category: "SCHEME_AND_SERVICE",
    title: "NDIS plan change",
    plainLanguageDescription: "Track dependencies when an NDIS plan changes — without legal determination.",
    likelyDomains: ["rights", "care", "billing"],
    milestones: employmentMilestones.filter((m) =>
      ["information_gathered", "decision_made", "application_submitted", "outcome_reviewed"].includes(
        m.code
      )
    ),
    dependencies: [
      {
        code: "funding_source",
        label: "Funding visibility",
        domain: "billing",
        required: false,
        defaultOwnerRole: "participant",
      },
      {
        code: "participant_goal",
        label: "Participant goal",
        domain: "mission",
        required: true,
        defaultOwnerRole: "participant",
      },
    ],
    commonDocuments: ["plan_summary_slice"],
    commonHandoffs: ["navigator_to_plan_manager"],
    accessibilityBarriers: ["inaccessible_plan_documents"],
    humanRoles: ["participant", "navigator", "rights_officer"],
    policySourceKeys: ["ndis_provider_responsibilities", "ndis_code_of_conduct"],
    requiredWarnings: [
      "ContinuityOS is not a legal-eligibility engine.",
      "Do not encode draft reforms as settled law.",
    ],
  }),
  def({
    code: "programme_transition",
    category: "SCHEME_AND_SERVICE",
    title: "Programme transition",
    plainLanguageDescription: "Coordinate transitions between government programmes.",
    likelyDomains: ["pathways", "rights", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) => d.code === "participant_goal"),
    commonDocuments: ["programme_referral_slice"],
    commonHandoffs: ["navigator_exchange"],
    accessibilityBarriers: ["inaccessible_forms"],
    humanRoles: ["participant", "navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Programme rules require human/source review before enforcement."],
  }),
  def({
    code: "aged_care_transition",
    category: "SCHEME_AND_SERVICE",
    title: "Aged-care transition",
    plainLanguageDescription: "Plan aged-care transitions without treating draft reforms as settled law.",
    likelyDomains: ["lifespan", "care", "rights"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "support_roster", "consent_authority"].includes(d.code)
    ),
    commonDocuments: ["scheme_transition_notes"],
    commonHandoffs: ["navigator_to_aged_care_partner"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "navigator", "rights_officer"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Support at Home and related reforms may be draft — human review required."],
  }),
  def({
    code: "employment_service_transition",
    category: "SCHEME_AND_SERVICE",
    title: "Employment-service transition",
    plainLanguageDescription: "Hand over between employment services with minimal disclosure.",
    likelyDomains: ["jobs", "rights"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "employer_contact", "consent_authority"].includes(d.code)
    ),
    commonDocuments: [],
    commonHandoffs: ["employment_service_to_employment_service"],
    accessibilityBarriers: [],
    humanRoles: ["participant", "navigator", "employment_service"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "interstate_move",
    category: "SCHEME_AND_SERVICE",
    title: "Interstate move",
    plainLanguageDescription: "Coordinate interstate moves across schemes, providers and transport.",
    likelyDomains: ["home", "regional", "care", "rights"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies,
    commonDocuments: ["address_change"],
    commonHandoffs: ["hub_to_spoke"],
    accessibilityBarriers: ["thin_market_capacity"],
    humanRoles: ["participant", "regional_navigator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: [],
  }),
  def({
    code: "international_travel",
    category: "SCHEME_AND_SERVICE",
    title: "Significant travel",
    plainLanguageDescription: "Plan significant travel dependencies and temporary workarounds.",
    likelyDomains: ["transport", "equipment", "care"],
    milestones: employmentMilestones,
    dependencies: startJobDependencies.filter((d) =>
      ["participant_goal", "accessible_transport", "equipment_charger"].includes(d.code)
    ),
    commonDocuments: ["travel_plan_slice"],
    commonHandoffs: ["provider_temporary_coverage"],
    accessibilityBarriers: ["inaccessible_travel_chain"],
    humanRoles: ["participant", "navigator", "transport_operator"],
    policySourceKeys: ["privacy_act_1988"],
    requiredWarnings: ["Temporary workarounds must expire."],
  }),
];

const BY_CODE = new Map(REGISTRY.map((item) => [item.code, item]));

export function listLifeEventTypes(): LifeEventTypeSummary[] {
  return REGISTRY.map((item) => ({
    code: item.code,
    category: item.category,
    version: item.version,
    title: item.title,
    plainLanguageDescription: item.plainLanguageDescription,
  }));
}

export function getLifeEventType(
  code: LifeEventTypeCode
): LifeEventTypeDefinition | undefined {
  return BY_CODE.get(code);
}

export function requireLifeEventType(code: string): LifeEventTypeDefinition {
  const found = BY_CODE.get(code as LifeEventTypeCode);
  if (!found) {
    throw new Error(`UNSUPPORTED_LIFE_EVENT_TYPE:${code}`);
  }
  return found;
}

export function listLifeEventTypeCodes(): LifeEventTypeCode[] {
  return REGISTRY.map((item) => item.code);
}

export const LIFE_EVENT_REGISTRY_VERSION = "2026-07-16.1";
