import type {
  AccessNeedProfile,
  TwinAssessment,
  TwinCompatibilityResult,
  TwinEvidence,
  TwinFeature,
  TwinIssue,
  TwinPathSegment,
  TwinPlace,
  TwinPlaceBundle,
  TwinZone,
} from "@/lib/digital-twin/types";
import { SCORING_DISCLAIMER } from "@/lib/digital-twin/constants";

const DEMO_NOW = "2026-06-01T00:00:00.000Z";

/** Demo TwinPlace: Sydney clinic with mixed accessibility. */
export const DEMO_PLACE_CLINIC: TwinPlace = {
  id: "twin-place-demo-clinic",
  name: "Harbourview Community Clinic (Demo)",
  slug: "harbourview-community-clinic",
  placeType: "clinic",
  description:
    "Fictional community health clinic near Sydney CBD. Mixed step-free access with some narrow corridors.",
  address: "42 Demo Lane, Haymarket NSW 2000",
  region: "Sydney CBD",
  geo: { lat: -33.879, lng: 151.205 },
  privacy: "public",
  status: "published",
  lastVerifiedAt: "2026-05-15T00:00:00.000Z",
  confidenceScore: 72,
  overallAccessibilityScore: 68,
  accessSummaryPlainLanguage:
    "Step-free entrance from street. Accessible toilet on ground floor. Some corridors are narrow for larger wheelchairs.",
  warnings: ["Corridor width varies; confirm turning space before appointment."],
  createdAt: DEMO_NOW,
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

/** Demo TwinPlace: accessible cafe with strong entrance, limited toilet. */
export const DEMO_PLACE_CAFE: TwinPlace = {
  id: "twin-place-demo-cafe",
  name: "Willow & Bean Café (Demo)",
  slug: "willow-bean-cafe",
  placeType: "venue",
  description:
    "Fictional café with excellent entrance and seating. Toilet access is limited and needs confirmation.",
  address: "88 Demo Street, Newtown NSW 2042",
  region: "Inner West Sydney",
  geo: { lat: -33.898, lng: 151.174 },
  privacy: "public",
  status: "published",
  lastVerifiedAt: "2026-05-20T00:00:00.000Z",
  confidenceScore: 81,
  overallAccessibilityScore: 74,
  accessSummaryPlainLanguage:
    "Level entry, wide doorway, flexible seating. Toilet is small and door width needs confirmation.",
  warnings: ["Accessible toilet information partially confirmed."],
  createdAt: DEMO_NOW,
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

/** Demo TwinPlace: transport hub with lift and platform paths. */
export const DEMO_PLACE_TRANSPORT: TwinPlace = {
  id: "twin-place-demo-transport",
  name: "Central Demo Station (Demo)",
  slug: "central-demo-station",
  placeType: "transport_hub",
  description:
    "Fictional transport interchange with lift status monitoring and platform path segments.",
  address: "1 Demo Plaza, Chatswood NSW 2067",
  region: "North Sydney",
  geo: { lat: -33.796, lng: 151.183 },
  privacy: "public",
  status: "published",
  lastVerifiedAt: "2026-05-18T00:00:00.000Z",
  confidenceScore: 85,
  overallAccessibilityScore: 78,
  accessSummaryPlainLanguage:
    "Step-free street to concourse. Lift available with occasional maintenance. Platform paths are wide with good lighting.",
  warnings: ["Lift may be temporarily unavailable during maintenance windows."],
  createdAt: DEMO_NOW,
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

/** Demo TwinPlace: workplace / interview site. */
export const DEMO_PLACE_WORKPLACE: TwinPlace = {
  id: "twin-place-demo-workplace",
  name: "Inclusive Works Demo Office (Demo)",
  slug: "inclusive-works-office",
  placeType: "workplace",
  description:
    "Fictional workplace and job interview site with adjustment-friendly features and quiet waiting area.",
  address: "Level 3, 15 Demo Avenue, Parramatta NSW 2150",
  region: "Western Sydney",
  geo: { lat: -33.815, lng: 151.0 },
  privacy: "public",
  status: "published",
  lastVerifiedAt: "2026-05-22T00:00:00.000Z",
  confidenceScore: 88,
  overallAccessibilityScore: 82,
  accessSummaryPlainLanguage:
    "Accessible drop-off, lift to level 3, quiet interview room, staff trained for written communication.",
  warnings: [],
  createdAt: DEMO_NOW,
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

export const DEMO_PLACES: TwinPlace[] = [
  DEMO_PLACE_CLINIC,
  DEMO_PLACE_CAFE,
  DEMO_PLACE_TRANSPORT,
  DEMO_PLACE_WORKPLACE,
];

export const DEMO_ZONES: TwinZone[] = [
  { id: "zone-clinic-ext", placeId: DEMO_PLACE_CLINIC.id, name: "Street approach", zoneType: "external_path", order: 1 },
  { id: "zone-clinic-ent", placeId: DEMO_PLACE_CLINIC.id, name: "Main entrance", zoneType: "entrance", order: 2 },
  { id: "zone-clinic-rec", placeId: DEMO_PLACE_CLINIC.id, name: "Reception", zoneType: "reception", order: 3, floorLabel: "Ground" },
  { id: "zone-clinic-cor", placeId: DEMO_PLACE_CLINIC.id, name: "Consult corridor", zoneType: "corridor", order: 4, floorLabel: "Ground" },
  { id: "zone-clinic-toilet", placeId: DEMO_PLACE_CLINIC.id, name: "Ground floor toilet", zoneType: "toilet", order: 5, floorLabel: "Ground" },
  { id: "zone-cafe-ext", placeId: DEMO_PLACE_CAFE.id, name: "Footpath", zoneType: "external_path", order: 1 },
  { id: "zone-cafe-ent", placeId: DEMO_PLACE_CAFE.id, name: "Café entrance", zoneType: "entrance", order: 2 },
  { id: "zone-cafe-seat", placeId: DEMO_PLACE_CAFE.id, name: "Indoor seating", zoneType: "seating", order: 3 },
  { id: "zone-cafe-toilet", placeId: DEMO_PLACE_CAFE.id, name: "Customer toilet", zoneType: "toilet", order: 4 },
  { id: "zone-trans-drop", placeId: DEMO_PLACE_TRANSPORT.id, name: "Kiss-and-ride", zoneType: "dropoff", order: 1 },
  { id: "zone-trans-con", placeId: DEMO_PLACE_TRANSPORT.id, name: "Concourse", zoneType: "reception", order: 2 },
  { id: "zone-trans-lift", placeId: DEMO_PLACE_TRANSPORT.id, name: "Platform lift", zoneType: "lift", order: 3 },
  { id: "zone-trans-plat", placeId: DEMO_PLACE_TRANSPORT.id, name: "Platform 2", zoneType: "platform", order: 4 },
  { id: "zone-work-drop", placeId: DEMO_PLACE_WORKPLACE.id, name: "Accessible drop-off", zoneType: "dropoff", order: 1 },
  { id: "zone-work-ent", placeId: DEMO_PLACE_WORKPLACE.id, name: "Building entrance", zoneType: "entrance", order: 2 },
  { id: "zone-work-rec", placeId: DEMO_PLACE_WORKPLACE.id, name: "Reception & waiting", zoneType: "reception", order: 3, floorLabel: "Level 3" },
  { id: "zone-work-quiet", placeId: DEMO_PLACE_WORKPLACE.id, name: "Quiet interview room", zoneType: "sensory_space", order: 4, floorLabel: "Level 3" },
];

export const DEMO_FEATURES: TwinFeature[] = [
  {
    id: "feat-clinic-entrance",
    placeId: DEMO_PLACE_CLINIC.id,
    zoneId: "zone-clinic-ent",
    featureType: "entrance",
    name: "Main entrance",
    description: "Automatic sliding door, level threshold",
    measurements: { doorwayWidthMm: 920 },
    availability: "available",
    accessibilityLevel: "silver",
    userImpactTags: ["step_free", "power_wheelchair"],
    sourceIds: ["ev-clinic-1"],
    lastCheckedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "feat-clinic-toilet",
    placeId: DEMO_PLACE_CLINIC.id,
    zoneId: "zone-clinic-toilet",
    featureType: "toilet",
    name: "Accessible toilet",
    availability: "available",
    accessibilityLevel: "silver",
    measurements: { turningCircleMm: 1500 },
    userImpactTags: ["accessible_toilet"],
    sourceIds: ["ev-clinic-2"],
    lastCheckedAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "feat-clinic-corridor",
    placeId: DEMO_PLACE_CLINIC.id,
    zoneId: "zone-clinic-cor",
    featureType: "corridor",
    name: "Consult corridor",
    measurements: { widthMm: 1100 },
    availability: "partial",
    accessibilityLevel: "bronze",
    userImpactTags: ["power_wheelchair", "turning_space"],
    sourceIds: ["ev-clinic-3"],
    lastCheckedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "feat-cafe-entrance",
    placeId: DEMO_PLACE_CAFE.id,
    zoneId: "zone-cafe-ent",
    featureType: "entrance",
    name: "Level café entrance",
    measurements: { doorwayWidthMm: 1050 },
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["step_free"],
    sourceIds: ["ev-cafe-1"],
    lastCheckedAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "feat-cafe-seating",
    placeId: DEMO_PLACE_CAFE.id,
    zoneId: "zone-cafe-seat",
    featureType: "seating",
    name: "Flexible seating",
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["fatigue_buffer", "mobility_aid"],
    sourceIds: ["ev-cafe-2"],
    lastCheckedAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "feat-cafe-toilet",
    placeId: DEMO_PLACE_CAFE.id,
    zoneId: "zone-cafe-toilet",
    featureType: "toilet",
    name: "Customer toilet",
    measurements: { doorwayWidthMm: 780 },
    availability: "partial",
    accessibilityLevel: "bronze",
    userImpactTags: ["accessible_toilet"],
    sourceIds: ["ev-cafe-3"],
    lastCheckedAt: "2026-04-01T00:00:00.000Z",
  },
  {
    id: "feat-trans-lift",
    placeId: DEMO_PLACE_TRANSPORT.id,
    zoneId: "zone-trans-lift",
    featureType: "lift",
    name: "Platform lift",
    availability: "partial",
    accessibilityLevel: "silver",
    userImpactTags: ["step_free", "lift_required"],
    sourceIds: ["ev-trans-1", "ev-trans-sensor"],
    lastCheckedAt: "2026-05-18T00:00:00.000Z",
  },
  {
    id: "feat-trans-path",
    placeId: DEMO_PLACE_TRANSPORT.id,
    zoneId: "zone-trans-plat",
    featureType: "path",
    name: "Platform walkway",
    measurements: { widthMm: 1800 },
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["power_wheelchair", "wide_paths"],
    sourceIds: ["ev-trans-2"],
    lastCheckedAt: "2026-05-18T00:00:00.000Z",
  },
  {
    id: "feat-trans-connection",
    placeId: DEMO_PLACE_TRANSPORT.id,
    featureType: "transport_connection",
    name: "Bus interchange connection",
    availability: "available",
    accessibilityLevel: "silver",
    userImpactTags: ["public_transport"],
    sourceIds: ["ev-trans-3"],
    lastCheckedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "feat-work-entrance",
    placeId: DEMO_PLACE_WORKPLACE.id,
    zoneId: "zone-work-ent",
    featureType: "entrance",
    name: "Level building entrance",
    measurements: { doorwayWidthMm: 1000 },
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["step_free", "power_wheelchair"],
    sourceIds: ["ev-work-ent"],
    lastCheckedAt: "2026-05-22T00:00:00.000Z",
  },
  {
    id: "feat-work-dropoff",
    placeId: DEMO_PLACE_WORKPLACE.id,
    zoneId: "zone-work-drop",
    featureType: "dropoff",
    name: "Ramp vehicle drop-off",
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["ramp_vehicle", "dropoff"],
    sourceIds: ["ev-work-1"],
    lastCheckedAt: "2026-05-22T00:00:00.000Z",
  },
  {
    id: "feat-work-quiet",
    placeId: DEMO_PLACE_WORKPLACE.id,
    zoneId: "zone-work-quiet",
    featureType: "acoustics",
    name: "Quiet waiting area",
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["quiet_space", "aac", "sensory"],
    sourceIds: ["ev-work-2"],
    lastCheckedAt: "2026-05-22T00:00:00.000Z",
  },
  {
    id: "feat-work-staff",
    placeId: DEMO_PLACE_WORKPLACE.id,
    zoneId: "zone-work-rec",
    featureType: "staff_training",
    name: "Written communication support",
    description: "Staff trained to read written notes and allow extra processing time",
    availability: "available",
    accessibilityLevel: "gold",
    userImpactTags: ["aac", "plain_language"],
    sourceIds: ["ev-work-3"],
    lastCheckedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "feat-work-toilet",
    placeId: DEMO_PLACE_WORKPLACE.id,
    featureType: "toilet",
    name: "Level 3 accessible toilet",
    availability: "available",
    accessibilityLevel: "silver",
    userImpactTags: ["accessible_toilet"],
    sourceIds: ["ev-work-4"],
    lastCheckedAt: "2026-05-22T00:00:00.000Z",
  },
];

export const DEMO_PATH_SEGMENTS: TwinPathSegment[] = [
  {
    id: "path-clinic-1",
    placeId: DEMO_PLACE_CLINIC.id,
    fromZoneId: "zone-clinic-ext",
    toZoneId: "zone-clinic-ent",
    distanceMeters: 25,
    widthMm: 1500,
    hasSteps: false,
    hasRamp: false,
    hasHandrails: true,
    lightingLevel: "good",
    notes: "Smooth concrete, slight cross-slope",
  },
  {
    id: "path-clinic-2",
    placeId: DEMO_PLACE_CLINIC.id,
    fromZoneId: "zone-clinic-ent",
    toZoneId: "zone-clinic-rec",
    distanceMeters: 8,
    widthMm: 1200,
    hasSteps: false,
    hasRamp: false,
    hasHandrails: false,
    lightingLevel: "adequate",
  },
  {
    id: "path-trans-1",
    placeId: DEMO_PLACE_TRANSPORT.id,
    fromZoneId: "zone-trans-drop",
    toZoneId: "zone-trans-con",
    distanceMeters: 40,
    widthMm: 2000,
    hasSteps: false,
    hasRamp: true,
    hasHandrails: true,
    lightingLevel: "good",
    routeGeometry: {
      type: "LineString",
      coordinates: [
        [151.183, -33.796],
        [151.1832, -33.7962],
      ],
    },
  },
  {
    id: "path-trans-2",
    placeId: DEMO_PLACE_TRANSPORT.id,
    fromZoneId: "zone-trans-con",
    toZoneId: "zone-trans-plat",
    distanceMeters: 60,
    widthMm: 1800,
    hasSteps: false,
    hasRamp: false,
    hasHandrails: true,
    lightingLevel: "good",
    notes: "Via lift — check lift status before travelling",
  },
  {
    id: "path-work-1",
    placeId: DEMO_PLACE_WORKPLACE.id,
    fromZoneId: "zone-work-drop",
    toZoneId: "zone-work-ent",
    distanceMeters: 15,
    widthMm: 1600,
    hasSteps: false,
    hasRamp: true,
    hasHandrails: true,
    lightingLevel: "good",
  },
];

export const DEMO_EVIDENCE: TwinEvidence[] = [
  {
    id: "ev-clinic-1",
    placeId: DEMO_PLACE_CLINIC.id,
    featureId: "feat-clinic-entrance",
    evidenceType: "measurement",
    title: "Doorway width measured",
    summary: "920mm clear opening at main entrance, measured with laser tape.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-15T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-clinic-2",
    placeId: DEMO_PLACE_CLINIC.id,
    featureId: "feat-clinic-toilet",
    evidenceType: "assessor_note",
    title: "Toilet inspection",
    summary: "Grab rails present, turning circle approximately 1500mm.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-10T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-clinic-3",
    placeId: DEMO_PLACE_CLINIC.id,
    featureId: "feat-clinic-corridor",
    evidenceType: "user_review",
    title: "Community note on corridor",
    summary: "Power wheelchair user reported tight turns near room 3.",
    sourceActorType: "user",
    capturedAt: "2026-05-01T00:00:00.000Z",
    confidence: "medium",
    status: "approved",
  },
  {
    id: "ev-cafe-1",
    placeId: DEMO_PLACE_CAFE.id,
    featureId: "feat-cafe-entrance",
    evidenceType: "photo",
    title: "Entrance photo",
    summary: "Level threshold and wide doorway visible in community photo.",
    sourceActorType: "user",
    capturedAt: "2026-05-20T00:00:00.000Z",
    confidence: "medium",
    status: "approved",
  },
  {
    id: "ev-cafe-2",
    placeId: DEMO_PLACE_CAFE.id,
    featureId: "feat-cafe-seating",
    evidenceType: "venue_declaration",
    title: "Venue seating statement",
    summary: "Staff confirm movable chairs and space for mobility aids.",
    sourceActorType: "venue",
    capturedAt: "2026-05-18T00:00:00.000Z",
    confidence: "medium",
    status: "approved",
  },
  {
    id: "ev-cafe-3",
    placeId: DEMO_PLACE_CAFE.id,
    featureId: "feat-cafe-toilet",
    evidenceType: "user_review",
    title: "Toilet width unconfirmed",
    summary: "Reviewer noted narrow door; measurement not yet verified.",
    sourceActorType: "user",
    capturedAt: "2026-04-01T00:00:00.000Z",
    confidence: "low",
    status: "approved",
  },
  {
    id: "ev-trans-1",
    placeId: DEMO_PLACE_TRANSPORT.id,
    featureId: "feat-trans-lift",
    evidenceType: "assessor_note",
    title: "Lift assessment",
    summary: "Lift operational during assessment; maintenance scheduled quarterly.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-18T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-trans-sensor",
    placeId: DEMO_PLACE_TRANSPORT.id,
    featureId: "feat-trans-lift",
    evidenceType: "sensor_status",
    title: "Lift sensor feed",
    summary: "Demo sensor reports lift operational as of last sync.",
    sourceActorType: "system",
    capturedAt: "2026-05-25T00:00:00.000Z",
    confidence: "medium",
    status: "approved",
  },
  {
    id: "ev-trans-2",
    placeId: DEMO_PLACE_TRANSPORT.id,
    featureId: "feat-trans-path",
    evidenceType: "measurement",
    title: "Platform path width",
    summary: "1800mm tactile-guided path on platform 2.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-18T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-work-ent",
    placeId: DEMO_PLACE_WORKPLACE.id,
    featureId: "feat-work-entrance",
    evidenceType: "measurement",
    title: "Entrance width measured",
    summary: "1000mm clear opening at level entrance.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-22T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-work-1",
    placeId: DEMO_PLACE_WORKPLACE.id,
    featureId: "feat-work-dropoff",
    evidenceType: "venue_declaration",
    title: "Drop-off bay reserved",
    summary: "Employer confirms accessible bay with kerb ramp.",
    sourceActorType: "venue",
    capturedAt: "2026-05-22T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-work-2",
    placeId: DEMO_PLACE_WORKPLACE.id,
    featureId: "feat-work-quiet",
    evidenceType: "assessor_note",
    title: "Quiet room verified",
    summary: "Interview room away from open plan, low background noise.",
    sourceActorType: "assessor",
    capturedAt: "2026-05-22T00:00:00.000Z",
    confidence: "high",
    status: "approved",
  },
  {
    id: "ev-work-3",
    placeId: DEMO_PLACE_WORKPLACE.id,
    featureId: "feat-work-staff",
    evidenceType: "staff_training_record",
    title: "Communication training",
    summary: "Reception staff completed AAC awareness module (demo record).",
    sourceActorType: "provider",
    capturedAt: "2026-05-15T00:00:00.000Z",
    confidence: "medium",
    status: "approved",
  },
];

export const DEMO_ASSESSMENTS: TwinAssessment[] = [
  {
    id: "assess-clinic",
    placeId: DEMO_PLACE_CLINIC.id,
    method: "hybrid",
    assessorName: "Demo Assessor",
    assessmentDate: "2026-05-15T00:00:00.000Z",
    domains: {
      external_path: 75,
      entry_exit: 80,
      interior_movement: 55,
      amenities_toilets: 70,
      information_sensory: 60,
      staff_services: 65,
      transport_connection: 50,
      online_information: 55,
    },
    totalScore: 68,
    tier: "bronze",
    disclaimer: SCORING_DISCLAIMER,
    nextReviewDue: "2026-11-15T00:00:00.000Z",
  },
  {
    id: "assess-cafe",
    placeId: DEMO_PLACE_CAFE.id,
    method: "community",
    assessmentDate: "2026-05-20T00:00:00.000Z",
    domains: {
      external_path: 85,
      entry_exit: 95,
      interior_movement: 80,
      amenities_toilets: 45,
      information_sensory: 70,
      staff_services: 75,
      transport_connection: 60,
      online_information: 50,
    },
    totalScore: 74,
    tier: "silver",
    disclaimer: SCORING_DISCLAIMER,
    nextReviewDue: "2026-11-20T00:00:00.000Z",
  },
  {
    id: "assess-transport",
    placeId: DEMO_PLACE_TRANSPORT.id,
    method: "professional",
    assessorName: "Demo Transport Assessor",
    assessmentDate: "2026-05-18T00:00:00.000Z",
    domains: {
      external_path: 80,
      entry_exit: 75,
      interior_movement: 85,
      amenities_toilets: 70,
      information_sensory: 75,
      staff_services: 70,
      transport_connection: 90,
      online_information: 65,
    },
    totalScore: 78,
    tier: "silver",
    disclaimer: SCORING_DISCLAIMER,
    nextReviewDue: "2026-08-18T00:00:00.000Z",
  },
  {
    id: "assess-workplace",
    placeId: DEMO_PLACE_WORKPLACE.id,
    method: "professional",
    assessorName: "Demo Workplace Assessor",
    assessmentDate: "2026-05-22T00:00:00.000Z",
    domains: {
      external_path: 90,
      entry_exit: 85,
      interior_movement: 88,
      amenities_toilets: 80,
      information_sensory: 92,
      staff_services: 95,
      transport_connection: 75,
      online_information: 70,
    },
    totalScore: 82,
    tier: "silver",
    disclaimer: SCORING_DISCLAIMER,
    nextReviewDue: "2026-11-22T00:00:00.000Z",
  },
];

export const DEMO_ISSUES: TwinIssue[] = [
  {
    id: "issue-clinic-corridor",
    placeId: DEMO_PLACE_CLINIC.id,
    featureId: "feat-clinic-corridor",
    issueType: "access_barrier",
    severity: "medium",
    status: "open",
    summary: "Corridor may be too narrow for some power wheelchairs near consult room 3.",
    createdAt: "2026-05-02T00:00:00.000Z",
    updatedAt: "2026-05-02T00:00:00.000Z",
  },
  {
    id: "issue-cafe-toilet",
    placeId: DEMO_PLACE_CAFE.id,
    featureId: "feat-cafe-toilet",
    issueType: "outdated_info",
    severity: "medium",
    status: "open",
    summary: "Toilet door width not professionally measured; community reports vary.",
    createdAt: "2026-04-05T00:00:00.000Z",
    updatedAt: "2026-04-05T00:00:00.000Z",
  },
  {
    id: "issue-trans-lift",
    placeId: DEMO_PLACE_TRANSPORT.id,
    featureId: "feat-trans-lift",
    issueType: "maintenance",
    severity: "high",
    status: "acknowledged",
    summary: "Lift scheduled for maintenance next month; alternate route may be required.",
    createdAt: "2026-05-20T00:00:00.000Z",
    updatedAt: "2026-05-21T00:00:00.000Z",
  },
  {
    id: "issue-work-resolved",
    placeId: DEMO_PLACE_WORKPLACE.id,
    issueType: "outdated_info",
    severity: "low",
    status: "resolved",
    summary: "Online parking instructions updated after community report.",
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-05-10T00:00:00.000Z",
  },
];

/** Demo profile: power wheelchair user. */
export const DEMO_PROFILE_WHEELCHAIR: AccessNeedProfile = {
  id: "demo-profile-wheelchair",
  ownerUserId: "demo-user-wheelchair",
  displayName: "Alex (Demo — power wheelchair)",
  mobilityAids: ["power_wheelchair"],
  communicationPreferences: ["plain_language"],
  sensoryPreferences: [],
  transportNeeds: ["ramp_vehicle", "step_free_paths"],
  supportPreferences: ["fatigue_buffer"],
  shareDefault: "private",
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

/** Demo profile: non-speaking AAC user. */
export const DEMO_PROFILE_AAC: AccessNeedProfile = {
  id: "demo-profile-aac",
  ownerUserId: "demo-user-aac",
  displayName: "Jordan (Demo — AAC user)",
  mobilityAids: [],
  communicationPreferences: ["aac", "written_only", "plain_language"],
  sensoryPreferences: ["quiet_space", "low_sensory"],
  transportNeeds: [],
  supportPreferences: ["staff_read_written_notes"],
  shareDefault: "private",
  updatedAt: DEMO_NOW,
  isDemoData: true,
};

export const DEMO_ACCESS_PROFILES: AccessNeedProfile[] = [
  DEMO_PROFILE_WHEELCHAIR,
  DEMO_PROFILE_AAC,
];

export const DEMO_COMPATIBILITY_RESULTS: TwinCompatibilityResult[] = [
  {
    placeId: DEMO_PLACE_WORKPLACE.id,
    profileId: DEMO_PROFILE_WHEELCHAIR.id,
    compatibilityScore: 88,
    matchedNeeds: [
      "Step-free entrance",
      "Ramp vehicle drop-off",
      "Accessible toilet",
      "Wide paths",
    ],
    barriers: [],
    unknowns: [],
    recommendedActions: ["Confirm lift status on arrival day"],
    confidence: "high",
    explanationPlainLanguage:
      "Strong match for a power wheelchair user. Drop-off, entrance, toilet, and paths meet common needs.",
  },
  {
    placeId: DEMO_PLACE_CAFE.id,
    profileId: DEMO_PROFILE_WHEELCHAIR.id,
    compatibilityScore: 62,
    matchedNeeds: ["Step-free entrance", "Flexible seating"],
    barriers: ["Toilet door may be too narrow"],
    unknowns: ["Exact toilet measurements"],
    recommendedActions: [
      "Confirm toilet access before visiting",
      "Ask staff about nearest accessible toilet if needed",
    ],
    confidence: "medium",
    explanationPlainLanguage:
      "Partial match. Entrance and seating work well, but toilet access needs confirmation.",
  },
  {
    placeId: DEMO_PLACE_CLINIC.id,
    profileId: DEMO_PROFILE_WHEELCHAIR.id,
    compatibilityScore: 45,
    matchedNeeds: ["Step-free entrance", "Accessible toilet on ground floor"],
    barriers: ["Corridor may be too narrow for turning"],
    unknowns: ["Consult room turning space"],
    recommendedActions: [
      "Contact clinic before appointment to discuss room allocation",
      "Allow extra time for internal movement",
    ],
    confidence: "medium",
    explanationPlainLanguage:
      "Some needs are met but internal corridors may be difficult. Confirm before your appointment.",
  },
];

export function getDemoPlaceBundle(placeId: string): TwinPlaceBundle | undefined {
  const place = DEMO_PLACES.find((p) => p.id === placeId);
  if (!place) return undefined;
  return {
    place,
    zones: DEMO_ZONES.filter((z) => z.placeId === placeId),
    features: DEMO_FEATURES.filter((f) => f.placeId === placeId),
    pathSegments: DEMO_PATH_SEGMENTS.filter((p) => p.placeId === placeId),
    evidence: DEMO_EVIDENCE.filter((e) => e.placeId === placeId),
    assessment:
      DEMO_ASSESSMENTS.find((a) => a.placeId === placeId) ?? DEMO_ASSESSMENTS[0],
    issues: DEMO_ISSUES.filter((i) => i.placeId === placeId),
  };
}

export function getDemoPlaceBySlug(slug: string): TwinPlaceBundle | undefined {
  const place = DEMO_PLACES.find((p) => p.slug === slug);
  if (!place) return undefined;
  return getDemoPlaceBundle(place.id);
}

export function getAllDemoPlaceBundles(): TwinPlaceBundle[] {
  return DEMO_PLACES.map((p) => getDemoPlaceBundle(p.id)!);
}
