import type { AiCapabilityRegistration } from "./types";

/**
 * Registers existing MapAble AI-labelled capabilities without changing product behaviour.
 * Maturity/claim status reflects main as of foundation PR.
 */
export const SEEDED_CAPABILITIES: AiCapabilityRegistration[] = [
  {
    key: "search.nl_interpreter",
    publicName: "Natural-language search interpreter",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator", "anonymous_search"],
    intendedPurpose: "Parse natural language into structured provider search filters.",
    prohibitedUses: ["invent_providers", "infer_diagnosis", "execute_bookings"],
    maturity: "production_supported",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_INTERPRETER_ENABLED",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "search-interpreter-v1",
    toolAllowlist: [],
    inputSchemaRef: "NaturalLanguageSearchFilters",
    outputSchemaRef: "SearchInterpretation",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "deterministic_passthrough_rules",
    maxLatencyMs: 8000,
    tokenBudget: 4000,
    costBudgetUsd: 0.05,
    evaluationSuite: "ai-evals/search-interpreter",
    algorithmRegisterRef: "alg.search_interpreter",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "search.nl_interpreter",
  },
  {
    key: "search.access_needs_interpreter",
    publicName: "Access-needs interpreter",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Resolve free-text access needs into catalog access-need IDs.",
    prohibitedUses: ["infer_diagnosis", "certify_accessibility"],
    maturity: "production_supported",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_NEEDS_INTERPRETER_LLM",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "access-needs-v1",
    toolAllowlist: [],
    inputSchemaRef: "AccessNeedResolutionInput",
    outputSchemaRef: "AccessNeedResolution",
    permittedDataClasses: ["public", "operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "keyword_only",
    maxLatencyMs: 8000,
    tokenBudget: 3000,
    costBudgetUsd: 0.05,
    evaluationSuite: "ai-evals/access-needs",
    algorithmRegisterRef: "alg.access_needs_interpreter",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "search.access_needs_interpreter",
  },
  {
    key: "provider_finder.reply_generator",
    publicName: "Provider Finder reply generator",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant"],
    intendedPurpose: "Stream assistant replies grounded in search results.",
    prohibitedUses: ["invent_availability", "book_services"],
    maturity: "controlled_pilot",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "provider-finder-stream-v1",
    toolAllowlist: ["ndis_search", "clarify"],
    inputSchemaRef: "ProviderFinderTurn",
    outputSchemaRef: "UIMessageStream",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "financial"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "template_reply",
    maxLatencyMs: 20000,
    tokenBudget: 6000,
    costBudgetUsd: 0.1,
    evaluationSuite: "ai-evals/provider-finder",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "provider_finder.reply_generator",
  },
  {
    key: "agent.disability_services",
    publicName: "Disability-services agent",
    internalOwner: "agent-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Bounded tool-loop agent for disability service discovery.",
    prohibitedUses: ["assign_worker", "alter_consent", "submit_claims"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "DISABILITY_SERVICES_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "disability-services-agent-v1",
    toolAllowlist: ["search_providers", "explain_provider", "clarify"],
    inputSchemaRef: "DisabilityServicesAgentInput",
    outputSchemaRef: "DisabilityServicesAgentOutput",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "refuse_when_unconfigured",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "ai-evals/disability-agent",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.disability_services",
  },
  {
    key: "agent.booking_services",
    publicName: "Booking-services agent",
    internalOwner: "agent-platform",
    responsibleDomain: "bookings",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Auth-scoped booking retrieval via tool loop.",
    prohibitedUses: ["create_booking_without_confirm", "cross_tenant_read"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "BOOKING_SERVICES_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "booking-services-agent-v1",
    toolAllowlist: ["booking_rag_search", "list_bookings"],
    inputSchemaRef: "BookingServicesAgentInput",
    outputSchemaRef: "BookingServicesAgentOutput",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "refuse_when_unconfigured",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "ai-evals/booking-agent",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.booking_services",
  },
  {
    key: "case.deterministic_engine",
    publicName: "Case deterministic engine",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Rules-based case risk, next actions, and NL search over cases.",
    prohibitedUses: [
      "close_case",
      "determine_allegation",
      "determine_reportability",
      "contact_external_party",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "CASE_MANAGEMENT_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseAIInput",
    outputSchemaRef: "CaseAIInsight",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "no_insight",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-management",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.deterministic_engine",
  },
  {
    key: "case.extractive_summary",
    publicName: "Case extractive summary",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Extractive (rules) case summary — not a generative narrative.",
    prohibitedUses: ["authoritative_single_narrative_when_sources_conflict"],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "CASE_MANAGEMENT_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseSummaryInput",
    outputSchemaRef: "CaseSummary",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "empty_summary",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-management",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.extractive_summary",
  },
  {
    key: "billing.copilot",
    publicName: "Billing Copilot",
    internalOwner: "billing",
    responsibleDomain: "billing",
    intendedUsers: ["provider_admin", "coordinator"],
    intendedPurpose: "Editable billing suggestions grounded in invoice/agreement records.",
    prohibitedUses: [
      "auto_approve_invoice",
      "auto_pay",
      "auto_claim",
      "change_rate_without_human",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "BILLING_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "BillingCopilotInput",
    outputSchemaRef: "BillingCopilotSuggestion",
    permittedDataClasses: ["financial", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "no_suggestions",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/billing-a11y",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "billing.copilot",
  },
  {
    key: "matching.care_rules",
    publicName: "Care matching (deterministic)",
    internalOwner: "matching",
    responsibleDomain: "care",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Deterministic worker matching with explainable factors.",
    prohibitedUses: [
      "diagnosis_based_matching",
      "universal_worker_quality_score",
      "pay_to_rank",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "MATCHING_ENGINE_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CareMatchInput",
    outputSchemaRef: "MatchRun",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "empty_candidates",
    maxLatencyMs: 10000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/mapable-phase5",
    algorithmRegisterRef: "alg.care_matching_rules",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "matching.care_rules",
  },
  {
    key: "matching.ai_overlay",
    publicName: "Care matching overlay (optional model commentary)",
    internalOwner: "matching",
    responsibleDomain: "care",
    intendedPurpose:
      "Optional overlay around rule matching. Model commentary is null when no model runs.",
    intendedUsers: ["coordinator", "admin"],
    prohibitedUses: ["fabricate_ai_score", "override_hard_requirements"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "AI_MATCHING_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "AiMatchInput",
    outputSchemaRef: "AiMatchRun",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "deterministic_only",
    maxLatencyMs: 15000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-matching",
    algorithmRegisterRef: "alg.ai_matching_overlay",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "matching.ai_overlay",
  },
  {
    key: "accesscast.forecast",
    publicName: "AccessCast forecast",
    internalOwner: "access-intelligence",
    responsibleDomain: "access",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Deterministic access-usability forecast for places/journeys.",
    prohibitedUses: ["ai_state_decision", "certify_venue_accessible"],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_ACCESSCAST_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "AccessCastInput",
    outputSchemaRef: "AccessCastForecast",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "unavailable",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/accesscast",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "accesscast.forecast",
  },
  {
    key: "case.copilot",
    publicName: "Case Copilot",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose:
      "Cited chronology, source-separated summary, drafts, and correction workflow.",
    prohibitedUses: [
      "close_case",
      "determine_allegation",
      "determine_reportability",
      "recommend_restrictive_practice",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_CASE_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseSnapshot",
    outputSchemaRef: "CaseCopilotPack",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "disabled_surface",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-copilot",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.copilot",
  },
  {
    key: "mission.copilot",
    publicName: "Mission Copilot (Starting Work)",
    internalOwner: "mission-portfolio",
    responsibleDomain: "missions",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose:
      "Read-only explanations of Starting Work mission status, unknowns, and decisions.",
    prohibitedUses: [
      "book",
      "cancel",
      "assign",
      "pay",
      "claim",
      "alter_consent",
      "modify_mission",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_MISSION_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "MissionCopilotQuestion",
    outputSchemaRef: "MissionCopilotResponse",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "disabled_surface",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/mission-copilot",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "mission.copilot",
  },
  {
    key: "access_intelligence_next.preflight",
    publicName: "Access Intelligence journey preflight",
    internalOwner: "access-intelligence",
    responsibleDomain: "access",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Deterministic journey preflight over Living Access Fabric contracts.",
    prohibitedUses: [
      "ai_auto_publish",
      "ai_certification",
      "ai_execution",
      "universal_accessibility_score",
    ],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_ACCESS_INTELLIGENCE_NEXT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "JourneyPreflightInput",
    outputSchemaRef: "JourneyPreflightResult",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "unavailable",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/access-intelligence-next",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "access_intelligence_next.preflight",
  },
];
