/**
 * Accessibility feature and hazard taxonomies for VisionAccessOS.
 * Classifications describe the environment — never the participant.
 */

export const VISION_FEATURE_CLASSES = [
  // Entrance
  "entrance_candidate",
  "step_free_entrance_candidate",
  "revolving_door",
  "hinged_door",
  "sliding_door",
  "automatic_door",
  "door_button",
  "threshold",
  "entrance_obstruction",
  "intercom",
  "after_hours_barrier",
  // Pathway
  "clear_pathway",
  "narrowed_pathway",
  "blocked_pathway",
  "uneven_surface",
  "loose_surface",
  "wet_surface",
  "pothole",
  "cable",
  "temporary_furniture",
  "construction_barrier",
  "low_obstacle",
  "overhead_obstacle",
  "drop_off",
  "kerb",
  "kerb_ramp",
  "tactile_indicator",
  // Vertical
  "stairs",
  "ramp",
  "lift",
  "escalator",
  "platform_lift",
  "missing_handrail_candidate",
  "blocked_landing",
  "lift_notice",
  // Toilet
  "toilet_entrance",
  "accessible_toilet_sign",
  "toilet_pan",
  "transfer_space_candidate",
  "grab_rail",
  "basin",
  "changing_table",
  "emergency_cord",
  "toilet_obstruction",
  // Parking
  "accessible_bay",
  "access_aisle",
  "blocked_bay",
  "kerb_zone",
  "passenger_loading",
  "ramp_deployment_space",
  "illegal_obstruction_candidate",
  // Wayfinding
  "directional_sign",
  "tactile_sign_candidate",
  "room_sign",
  "high_glare_sign",
  "obstructed_sign",
  "missing_continuation_sign_candidate",
  // Sensory / communication (sign-level only)
  "hearing_loop_sign",
  "quiet_space_sign",
  "visual_clutter",
  "glare",
] as const;

export type VisionFeatureClass = (typeof VISION_FEATURE_CLASSES)[number];

export const VISION_HAZARD_CLASSES = [
  // Static trip / collision
  "cable",
  "low_object",
  "protruding_object",
  "open_drawer",
  "bollard",
  "temporary_furniture",
  "loose_mat",
  "damaged_surface",
  "pothole",
  // Level change
  "step",
  "stair",
  "kerb",
  "platform_edge",
  "drop_off",
  "uncovered_opening",
  // Route blockage
  "construction",
  "crowd",
  "parked_vehicle",
  "scooter",
  "bin",
  "locked_gate",
  "closed_door",
  "temporary_barrier",
  // Surface
  "wet",
  "reflective",
  "loose",
  "gravel",
  "mud",
  "snow_or_ice",
  "uneven_pavers",
  // Moving
  "moving_vehicle",
  "bicycle",
  "moving_scooter",
  "moving_door",
  "crowd_movement",
  // Operational notice
  "lift_unavailable",
  "entrance_closed",
  "temporary_route",
  "wet_floor_warning",
  "maintenance_sign",
] as const;

export type VisionHazardClass = (typeof VISION_HAZARD_CLASSES)[number];

/** Wave 1 / pilot allowlist — narrow classes only. */
export const VISION_PILOT_ALLOWLIST = [
  "entrance_candidate",
  "hinged_door",
  "sliding_door",
  "automatic_door",
  "temporary_barrier",
  "blocked_pathway",
  "stairs",
  "step",
  "stair",
  "path_occlusion",
  "lift_notice",
  "lift_unavailable",
  "illegal_obstruction_candidate",
  "access_aisle",
  "blocked_bay",
] as const;

export const VISION_FEATURE_LABELS: Record<VisionFeatureClass, string> = {
  entrance_candidate: "Entrance candidate",
  step_free_entrance_candidate: "Step-free entrance candidate",
  revolving_door: "Revolving door",
  hinged_door: "Hinged door",
  sliding_door: "Sliding door",
  automatic_door: "Automatic door",
  door_button: "Door button",
  threshold: "Threshold",
  entrance_obstruction: "Entrance obstruction",
  intercom: "Intercom",
  after_hours_barrier: "After-hours barrier",
  clear_pathway: "Clear pathway",
  narrowed_pathway: "Narrowed pathway",
  blocked_pathway: "Blocked pathway",
  uneven_surface: "Uneven surface",
  loose_surface: "Loose surface",
  wet_surface: "Wet surface",
  pothole: "Pothole",
  cable: "Cable",
  temporary_furniture: "Temporary furniture",
  construction_barrier: "Construction barrier",
  low_obstacle: "Low obstacle",
  overhead_obstacle: "Overhead obstacle",
  drop_off: "Drop-off",
  kerb: "Kerb",
  kerb_ramp: "Kerb ramp",
  tactile_indicator: "Tactile indicator",
  stairs: "Stairs",
  ramp: "Ramp",
  lift: "Lift",
  escalator: "Escalator",
  platform_lift: "Platform lift",
  missing_handrail_candidate: "Missing handrail candidate",
  blocked_landing: "Blocked landing",
  lift_notice: "Lift notice",
  toilet_entrance: "Toilet entrance",
  accessible_toilet_sign: "Accessible toilet sign",
  toilet_pan: "Toilet pan",
  transfer_space_candidate: "Transfer space candidate",
  grab_rail: "Grab rail",
  basin: "Basin",
  changing_table: "Changing table",
  emergency_cord: "Emergency cord",
  toilet_obstruction: "Toilet obstruction",
  accessible_bay: "Accessible parking bay",
  access_aisle: "Access aisle",
  blocked_bay: "Blocked bay",
  kerb_zone: "Kerb zone",
  passenger_loading: "Passenger loading",
  ramp_deployment_space: "Ramp deployment space",
  illegal_obstruction_candidate: "Possible parking obstruction",
  directional_sign: "Directional sign",
  tactile_sign_candidate: "Tactile sign candidate",
  room_sign: "Room sign",
  high_glare_sign: "High-glare sign",
  obstructed_sign: "Obstructed sign",
  missing_continuation_sign_candidate: "Missing continuation sign candidate",
  hearing_loop_sign: "Hearing loop sign",
  quiet_space_sign: "Quiet space sign",
  visual_clutter: "Visual clutter",
  glare: "Glare",
};

export const VISION_HAZARD_LABELS: Record<VisionHazardClass, string> = {
  cable: "Cable",
  low_object: "Low object",
  protruding_object: "Protruding object",
  open_drawer: "Open drawer",
  bollard: "Bollard",
  temporary_furniture: "Temporary furniture",
  loose_mat: "Loose mat",
  damaged_surface: "Damaged surface",
  pothole: "Pothole",
  step: "Step",
  stair: "Stair",
  kerb: "Kerb",
  platform_edge: "Platform edge",
  drop_off: "Drop-off",
  uncovered_opening: "Uncovered opening",
  construction: "Construction",
  crowd: "Crowd",
  parked_vehicle: "Parked vehicle",
  scooter: "Scooter",
  bin: "Bin",
  locked_gate: "Locked gate",
  closed_door: "Closed door",
  temporary_barrier: "Temporary barrier",
  wet: "Wet surface",
  reflective: "Reflective surface",
  loose: "Loose surface",
  gravel: "Gravel",
  mud: "Mud",
  snow_or_ice: "Snow or ice",
  uneven_pavers: "Uneven pavers",
  moving_vehicle: "Moving vehicle",
  bicycle: "Bicycle",
  moving_scooter: "Moving scooter",
  moving_door: "Moving door",
  crowd_movement: "Crowd movement",
  lift_unavailable: "Lift unavailable notice",
  entrance_closed: "Entrance closed notice",
  temporary_route: "Temporary route notice",
  wet_floor_warning: "Wet-floor warning",
  maintenance_sign: "Maintenance sign",
};

/** Outputs that VisionAccess must never produce. */
export const VISION_PROHIBITED_OUTPUTS = [
  "facial_identity",
  "person_reidentification",
  "disability_inference",
  "diagnosis_inference",
  "emotion_inference",
  "vulnerability_score",
  "participant_risk_score",
  "legal_compliance_claim",
  "building_certification",
  "safe_path_guarantee",
  "usable_entrance_proof",
  "ramp_standard_compliance",
  "journey_completion_proof",
  "emergency_route",
  "licence_plate_identity",
  "biometric_template",
] as const;

export type VisionProhibitedOutput = (typeof VISION_PROHIBITED_OUTPUTS)[number];
