import {
  EMPTY_CAPABILITY_FACTS,
  type AccessExplorationDto,
} from "@/lib/access/experience/access-exploration-dto";
import type { PlaceAccessProfile } from "@/lib/access/fit/types";
import type { GaisEvidenceState } from "@/lib/gais/contracts/evidence";

const EMPTY_PLACE_PROFILE: PlaceAccessProfile = {
  stepFreeEntry: null,
  doorWidthMm: null,
  internalStepFree: null,
  accessibleToilet: null,
  accessibleParking: null,
  dropOffPoint: null,
  lowSensoryOption: null,
  hearingLoop: null,
  staffTraining: null,
  assistanceAnimalWelcome: null,
  publicTransportNearby: null,
  transportBookable: null,
  lastVerified: null,
  confidence: "unknown",
};

function scaffoldPlace(input: {
  id: string;
  name: string;
  category: string;
  suburb: string;
  state: string;
  latitude: number;
  longitude: number;
  evidenceState: GaisEvidenceState;
  confidence: "high" | "medium" | "low" | "unknown";
  observedAt: string | null;
  profile: Partial<PlaceAccessProfile>;
}): AccessExplorationDto {
  const placeProfile: PlaceAccessProfile = {
    ...EMPTY_PLACE_PROFILE,
    ...input.profile,
    lastVerified: input.observedAt,
    confidence: input.confidence,
  };

  return {
    accessPlaceId: input.id,
    name: input.name,
    category: input.category,
    suburb: input.suburb,
    stateOrRegion: input.state,
    addressText: `${input.suburb}, ${input.state}`,
    hasCoordinates: true,
    latitude: input.latitude,
    longitude: input.longitude,
    reviewCount: 0,
    placeProfile,
    capabilityFacts: {
      ...EMPTY_CAPABILITY_FACTS,
      doorWidthMm: placeProfile.doorWidthMm,
      pathWidthMm: placeProfile.pathWidthMm ?? null,
      maxGradientPercent: placeProfile.maxGradientPercent ?? null,
      kerbRampPresent: placeProfile.kerbRampPresent ?? null,
      liftPresent: placeProfile.liftPresent ?? null,
      changingPlacesPresent: placeProfile.changingPlacesPresent ?? null,
      captioningAvailable: placeProfile.captioningAvailable ?? null,
      highContrastSignage: placeProfile.highContrastSignage ?? null,
      tactileCues: placeProfile.tactileCues ?? null,
      quietArea: placeProfile.quietArea ?? placeProfile.lowSensoryOption,
      lowStimulusEnvironment:
        placeProfile.lowStimulusEnvironment ?? placeProfile.lowSensoryOption,
      textAacCommunication: placeProfile.textAacCommunication ?? null,
      surfaceFirmness: placeProfile.surfaceFirmness ?? null,
    },
    evidence: {
      dominantState: input.evidenceState,
      freshnessLabel: input.observedAt
        ? `Synthetic fixture date ${input.observedAt}`
        : "Synthetic fixture — freshness not supplied",
      lastObservedAt: input.observedAt,
      confidenceLabel: input.confidence,
      disputed: false,
      refs: [
        {
          sourceType: input.evidenceState,
          sourceLabel:
            "Synthetic UI scaffold fixture — not live MapAble accessibility evidence",
          observedAt: input.observedAt ?? undefined,
        },
      ],
    },
    accreditation: null,
  };
}

/**
 * Synthetic fixtures for /access/scaffold only.
 *
 * These deliberately use the production AccessExplorationDto contract so the
 * scaffold cannot drift into a second accessibility domain model. They are not
 * live venues, verified accessibility records, or production discovery data.
 */
export const ACCESS_UI_SCAFFOLD_PLACES: AccessExplorationDto[] = [
  scaffoldPlace({
    id: "scaffold-sydney-library",
    name: "Sydney Access Library — scaffold",
    category: "library",
    suburb: "Sydney",
    state: "NSW",
    latitude: -33.8688,
    longitude: 151.2093,
    evidenceState: "AUTHORITATIVE_SOURCE",
    confidence: "high",
    observedAt: "2026-09-12",
    profile: {
      stepFreeEntry: true,
      internalStepFree: true,
      accessibleToilet: true,
      accessibleParking: true,
      dropOffPoint: true,
      lowSensoryOption: true,
      hearingLoop: null,
      staffTraining: true,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      doorWidthMm: 930,
      liftPresent: true,
      quietArea: true,
      textAacCommunication: true,
    },
  }),
  scaffoldPlace({
    id: "scaffold-melbourne-gallery",
    name: "Melbourne Arts Centre — scaffold",
    category: "arts_culture",
    suburb: "Melbourne",
    state: "VIC",
    latitude: -37.8136,
    longitude: 144.9631,
    evidenceState: "VERIFIED",
    confidence: "high",
    observedAt: "2026-08-28",
    profile: {
      stepFreeEntry: true,
      internalStepFree: true,
      accessibleToilet: null,
      accessibleParking: true,
      dropOffPoint: true,
      lowSensoryOption: null,
      hearingLoop: true,
      staffTraining: true,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      doorWidthMm: 1000,
      liftPresent: true,
      captioningAvailable: true,
    },
  }),
  scaffoldPlace({
    id: "scaffold-brisbane-market",
    name: "Brisbane Market Hall — scaffold",
    category: "shopping",
    suburb: "Brisbane",
    state: "QLD",
    latitude: -27.4698,
    longitude: 153.0251,
    evidenceState: "COMMUNITY_REPORTED",
    confidence: "medium",
    observedAt: "2026-10-01",
    profile: {
      stepFreeEntry: true,
      internalStepFree: null,
      accessibleToilet: null,
      accessibleParking: false,
      dropOffPoint: true,
      lowSensoryOption: false,
      hearingLoop: null,
      staffTraining: null,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      doorWidthMm: null,
      liftPresent: null,
    },
  }),
  scaffoldPlace({
    id: "scaffold-adelaide-hub",
    name: "Adelaide Civic Hub — scaffold",
    category: "community",
    suburb: "Adelaide",
    state: "SA",
    latitude: -34.9285,
    longitude: 138.6007,
    evidenceState: "AUTHORITATIVE_SOURCE",
    confidence: "medium",
    observedAt: "2026-09-07",
    profile: {
      stepFreeEntry: true,
      internalStepFree: true,
      accessibleToilet: true,
      accessibleParking: null,
      dropOffPoint: true,
      lowSensoryOption: null,
      hearingLoop: null,
      staffTraining: null,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      liftPresent: null,
    },
  }),
  scaffoldPlace({
    id: "scaffold-perth-interchange",
    name: "Perth Interchange — scaffold",
    category: "transport",
    suburb: "Perth",
    state: "WA",
    latitude: -31.9523,
    longitude: 115.8613,
    evidenceState: "VERIFIED",
    confidence: "high",
    observedAt: "2026-09-21",
    profile: {
      stepFreeEntry: true,
      internalStepFree: true,
      accessibleToilet: true,
      accessibleParking: true,
      dropOffPoint: true,
      lowSensoryOption: null,
      hearingLoop: true,
      staffTraining: true,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      liftPresent: true,
      captioningAvailable: true,
    },
  }),
  scaffoldPlace({
    id: "scaffold-hobart-museum",
    name: "Hobart Discovery Centre — scaffold",
    category: "museum",
    suburb: "Hobart",
    state: "TAS",
    latitude: -42.8821,
    longitude: 147.3272,
    evidenceState: "COMMUNITY_REPORTED",
    confidence: "medium",
    observedAt: "2026-09-25",
    profile: {
      stepFreeEntry: true,
      internalStepFree: null,
      accessibleToilet: true,
      accessibleParking: null,
      dropOffPoint: true,
      lowSensoryOption: true,
      hearingLoop: null,
      staffTraining: null,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      liftPresent: null,
    },
  }),
  scaffoldPlace({
    id: "scaffold-darwin-pavilion",
    name: "Darwin Waterfront Pavilion — scaffold",
    category: "community",
    suburb: "Darwin",
    state: "NT",
    latitude: -12.4634,
    longitude: 130.8456,
    evidenceState: "UNKNOWN",
    confidence: "unknown",
    observedAt: null,
    profile: {
      stepFreeEntry: null,
      internalStepFree: null,
      accessibleToilet: null,
      accessibleParking: null,
      dropOffPoint: null,
      lowSensoryOption: null,
      hearingLoop: null,
      staffTraining: null,
      assistanceAnimalWelcome: null,
      publicTransportNearby: null,
      transportBookable: null,
      liftPresent: null,
    },
  }),
  scaffoldPlace({
    id: "scaffold-canberra-commons",
    name: "Canberra Learning Commons — scaffold",
    category: "library",
    suburb: "Canberra",
    state: "ACT",
    latitude: -35.2809,
    longitude: 149.13,
    evidenceState: "VERIFIED",
    confidence: "high",
    observedAt: "2026-09-30",
    profile: {
      stepFreeEntry: true,
      internalStepFree: true,
      accessibleToilet: true,
      accessibleParking: true,
      dropOffPoint: true,
      lowSensoryOption: true,
      hearingLoop: null,
      staffTraining: true,
      assistanceAnimalWelcome: true,
      publicTransportNearby: true,
      transportBookable: null,
      liftPresent: true,
      quietArea: true,
      textAacCommunication: true,
    },
  }),
];
