import type { AiCapabilityRegistration } from "./types";

/**
 * Registers existing MapAble AI-labelled capabilities without changing product behaviour.
 * Maturity/claim status reflects main as of foundation PR.
 */
export const SEEDED_CAPABILITIES: AiCapabilityRegistration[] = [
  {
    key: "search.nl_interpreter",
    publicName: "Natural-language search interpreter",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator", "anonymous_search"],
    intendedPurpose: "Parse natural language into structured provider search filters.",
    prohibitedUses: ["invent_providers", "infer_diagnosis", "execute_bookings"],
    maturity: "production_supported",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_INTERPRETER_ENABLED",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "search-interpreter-v1",
    toolAllowlist: [],
    inputSchemaRef: "NaturalLanguageSearchFilters",
    outputSchemaRef: "SearchInterpretation",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "deterministic_passthrough_rules",
    maxLatencyMs: 8000,
    tokenBudget: 4000,
    costBudgetUsd: 0.05,
    evaluationSuite: "ai-evals/search-interpreter",
    algorithmRegisterRef: "alg.search_interpreter",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "search.nl_interpreter",
  },
  {
    key: "search.access_needs_interpreter",
    publicName: "Access-needs interpreter",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Resolve free-text access needs into catalog access-need IDs.",
    prohibitedUses: ["infer_diagnosis", "certify_accessibility"],
    maturity: "production_supported",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_NEEDS_INTERPRETER_LLM",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "access-needs-v1",
    toolAllowlist: [],
    inputSchemaRef: "AccessNeedResolutionInput",
    outputSchemaRef: "AccessNeedResolution",
    permittedDataClasses: ["public", "operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "keyword_only",
    maxLatencyMs: 8000,
    tokenBudget: 3000,
    costBudgetUsd: 0.05,
    evaluationSuite: "ai-evals/access-needs",
    algorithmRegisterRef: "alg.access_needs_interpreter",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "search.access_needs_interpreter",
  },
  {
    key: "provider_finder.reply_generator",
    publicName: "Provider Finder reply generator",
    internalOwner: "search-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant"],
    intendedPurpose: "Stream assistant replies grounded in search results.",
    prohibitedUses: ["invent_availability", "book_services"],
    maturity: "controlled_pilot",
    productionClaimStatus: "internal_only",
    featureFlag: "SEARCH_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "provider-finder-stream-v1",
    toolAllowlist: ["ndis_search", "clarify"],
    inputSchemaRef: "ProviderFinderTurn",
    outputSchemaRef: "UIMessageStream",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "financial"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "template_reply",
    maxLatencyMs: 20000,
    tokenBudget: 6000,
    costBudgetUsd: 0.1,
    evaluationSuite: "ai-evals/provider-finder",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "provider_finder.reply_generator",
  },
  {
    key: "agent.disability_services",
    publicName: "Disability-services agent",
    internalOwner: "agent-platform",
    responsibleDomain: "provider-finder",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Bounded tool-loop agent for disability service discovery.",
    prohibitedUses: ["assign_worker", "alter_consent", "submit_claims"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "DISABILITY_SERVICES_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "disability-services-agent-v1",
    toolAllowlist: ["search_providers", "explain_provider", "clarify"],
    inputSchemaRef: "DisabilityServicesAgentInput",
    outputSchemaRef: "DisabilityServicesAgentOutput",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "refuse_when_unconfigured",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "ai-evals/disability-agent",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.disability_services",
  },
  {
    key: "agent.booking_services",
    publicName: "Booking-services agent",
    internalOwner: "agent-platform",
    responsibleDomain: "bookings",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Auth-scoped booking retrieval via tool loop.",
    prohibitedUses: ["create_booking_without_confirm", "cross_tenant_read"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "BOOKING_SERVICES_AGENT_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "booking-services-agent-v1",
    toolAllowlist: ["booking_rag_search", "list_bookings"],
    inputSchemaRef: "BookingServicesAgentInput",
    outputSchemaRef: "BookingServicesAgentOutput",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "refuse_when_unconfigured",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "ai-evals/booking-agent",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.booking_services",
  },
  {
    key: "case.deterministic_engine",
    publicName: "Case deterministic engine",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Rules-based case risk, next actions, and NL search over cases.",
    prohibitedUses: [
      "close_case",
      "determine_allegation",
      "determine_reportability",
      "contact_external_party",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "CASE_MANAGEMENT_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseAIInput",
    outputSchemaRef: "CaseAIInsight",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "no_insight",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-management",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.deterministic_engine",
  },
  {
    key: "case.extractive_summary",
    publicName: "Case extractive summary",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Extractive (rules) case summary — not a generative narrative.",
    prohibitedUses: ["authoritative_single_narrative_when_sources_conflict"],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "CASE_MANAGEMENT_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseSummaryInput",
    outputSchemaRef: "CaseSummary",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "empty_summary",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-management",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.extractive_summary",
  },
  {
    key: "billing.copilot",
    publicName: "Billing Copilot",
    internalOwner: "billing",
    responsibleDomain: "billing",
    intendedUsers: ["provider_admin", "coordinator"],
    intendedPurpose: "Editable billing suggestions grounded in invoice/agreement records.",
    prohibitedUses: [
      "auto_approve_invoice",
      "auto_pay",
      "auto_claim",
      "change_rate_without_human",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "BILLING_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "BillingCopilotInput",
    outputSchemaRef: "BillingCopilotSuggestion",
    permittedDataClasses: ["financial", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "no_suggestions",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/billing-a11y",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "billing.copilot",
  },
  {
    key: "billing.evidence_copilot",
    publicName: "Billing Evidence Copilot",
    internalOwner: "billing",
    responsibleDomain: "billing",
    intendedUsers: ["provider_admin", "coordinator"],
    intendedPurpose:
      "Cited evidence packs, discrepancy explanations, and editable human-confirmed drafts.",
    prohibitedUses: [
      "automatic_invoice_approval",
      "payment_approval",
      "claim_approval",
      "change_rate",
      "change_funding_route",
      "send_messages_automatically",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_BILLING_EVIDENCE_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "BillingEvidencePackInput",
    outputSchemaRef: "BillingEvidencePack",
    permittedDataClasses: ["financial", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "disabled_surface",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/billing/evidence-pack",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "billing.evidence_copilot",
  },
  {
    key: "matching.care_rules",
    publicName: "Care matching (deterministic)",
    internalOwner: "matching",
    responsibleDomain: "care",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose: "Deterministic worker matching with explainable factors.",
    prohibitedUses: [
      "diagnosis_based_matching",
      "universal_worker_quality_score",
      "pay_to_rank",
    ],
    maturity: "deterministic",
    productionClaimStatus: "internal_only",
    featureFlag: "MATCHING_ENGINE_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CareMatchInput",
    outputSchemaRef: "MatchRun",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "empty_candidates",
    maxLatencyMs: 10000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/mapable-phase5",
    algorithmRegisterRef: "alg.care_matching_rules",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "matching.care_rules",
  },
  {
    key: "matching.ai_overlay",
    publicName: "Care matching overlay (optional model commentary)",
    internalOwner: "matching",
    responsibleDomain: "care",
    intendedPurpose:
      "Optional overlay around rule matching. Model commentary is null when no model runs.",
    intendedUsers: ["coordinator", "admin"],
    prohibitedUses: ["fabricate_ai_score", "override_hard_requirements"],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "AI_MATCHING_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "AiMatchInput",
    outputSchemaRef: "AiMatchRun",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "deterministic_only",
    maxLatencyMs: 15000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-matching",
    algorithmRegisterRef: "alg.ai_matching_overlay",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "matching.ai_overlay",
  },
  {
    key: "accesscast.forecast",
    publicName: "AccessCast forecast",
    internalOwner: "access-intelligence",
    responsibleDomain: "access",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Deterministic access-usability forecast for places/journeys.",
    prohibitedUses: ["ai_state_decision", "certify_venue_accessible"],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_ACCESSCAST_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "AccessCastInput",
    outputSchemaRef: "AccessCastForecast",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "unavailable",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/accesscast",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "accesscast.forecast",
  },
  {
    key: "case.copilot",
    publicName: "Case Copilot",
    internalOwner: "case-management",
    responsibleDomain: "cases",
    intendedUsers: ["coordinator", "admin"],
    intendedPurpose:
      "Cited chronology, source-separated summary, drafts, and correction workflow.",
    prohibitedUses: [
      "close_case",
      "determine_allegation",
      "determine_reportability",
      "recommend_restrictive_practice",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_CASE_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "CaseSnapshot",
    outputSchemaRef: "CaseCopilotPack",
    permittedDataClasses: ["operational", "participant_pii", "safeguarding"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "disabled_surface",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/case-copilot",
    algorithmRegisterRef: "alg.case_rules_v1",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "case.copilot",
  },
  {
    key: "mission.copilot",
    publicName: "Mission Copilot (Starting Work)",
    internalOwner: "mission-portfolio",
    responsibleDomain: "missions",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose:
      "Read-only explanations of Starting Work mission status, unknowns, and decisions.",
    prohibitedUses: [
      "book",
      "cancel",
      "assign",
      "pay",
      "claim",
      "alter_consent",
      "modify_mission",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_MISSION_COPILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "MissionCopilotQuestion",
    outputSchemaRef: "MissionCopilotResponse",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "disabled_surface",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/mission-copilot",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "mission.copilot",
  },
  {
    key: "access_intelligence_next.preflight",
    publicName: "Access Intelligence journey preflight",
    internalOwner: "access-intelligence",
    responsibleDomain: "access",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose: "Deterministic journey preflight over Living Access Fabric contracts.",
    prohibitedUses: [
      "ai_auto_publish",
      "ai_certification",
      "ai_execution",
      "universal_accessibility_score",
    ],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_ACCESS_INTELLIGENCE_NEXT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "JourneyPreflightInput",
    outputSchemaRef: "JourneyPreflightResult",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "unavailable",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/access-intelligence-next",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "access_intelligence_next.preflight",
  },
  {
    key: "intake.document_classify",
    publicName: "Evidence intake document classification",
    internalOwner: "ai-platform",
    responsibleDomain: "documents",
    intendedUsers: ["participant", "coordinator", "provider_admin"],
    intendedPurpose:
      "Propose a document class candidate for review-first evidence intake.",
    prohibitedUses: [
      "canonical_write",
      "execute_retrieved_instructions",
      "skip_human_review",
      "live_ocr_without_flag",
    ],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_AI_INTAKE_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "IntakeDocument",
    outputSchemaRef: "IntakeDocumentClass",
    permittedDataClasses: ["operational", "participant_pii", "financial"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "manual_classification",
    maxLatencyMs: 5000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/intake",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "intake.document_classify",
  },
  {
    key: "intake.field_extract",
    publicName: "Evidence intake field extraction",
    internalOwner: "ai-platform",
    responsibleDomain: "documents",
    intendedUsers: ["participant", "coordinator", "provider_admin"],
    intendedPurpose:
      "Propose field extraction candidates with provenance for human or participant review.",
    prohibitedUses: [
      "canonical_write",
      "auto_approve_invoice",
      "auto_approve_agreement",
      "execute_retrieved_instructions",
      "live_ocr_without_flag",
    ],
    maturity: "synthetic_only",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_AI_INTAKE_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "IntakeDocument",
    outputSchemaRef: "ExtractionCandidate",
    permittedDataClasses: ["operational", "participant_pii", "financial"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "manual_entry",
    maxLatencyMs: 15000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/intake",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "intake.field_extract",
  },
  {
    key: "mission.evidence_graph",
    publicName: "Mission Evidence Graph",
    internalOwner: "ai-platform",
    responsibleDomain: "mission",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose:
      "Project Starting Work canonical relationships into an evidence graph for citation.",
    prohibitedUses: [
      "second_mission_source_of_truth",
      "authoritative_model_edges",
      "operational_writes",
      "cross_tenant_traversal",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_MISSION_GRAPH_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "GoldenJourneyState",
    outputSchemaRef: "MissionEvidenceGraph",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "mission_portfolio_projection",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/mission-graph",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "mission.evidence_graph",
  },
  {
    key: "mission.semantic_retrieval",
    publicName: "Mission hybrid semantic retrieval",
    internalOwner: "ai-platform",
    responsibleDomain: "mission",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose:
      "Tenant-first hybrid keyword and graph retrieval over Starting Work evidence chunks.",
    prohibitedUses: [
      "retrieve_then_filter",
      "cross_tenant_embedding",
      "operational_writes",
      "embeddings_without_delete_path",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_SEMANTIC_RETRIEVAL_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "HybridRetrievalQuery",
    outputSchemaRef: "HybridRetrievalResult",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "keyword_only_or_unavailable",
    maxLatencyMs: 4000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/mission-graph",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "mission.semantic_retrieval",
  },
  {
    key: "edge.visit_pack_summary",
    publicName: "Offline Visit Pack summary",
    internalOwner: "companion",
    responsibleDomain: "companion",
    intendedUsers: ["worker", "participant"],
    intendedPurpose:
      "Deterministic local summary of an offline Visit Pack with a processing receipt.",
    prohibitedUses: [
      "require_ai_device",
      "app_store_ai_claim",
      "cloud_without_consent",
      "operational_writes",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_EDGE_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "VisitPackSummaryInput",
    outputSchemaRef: "EdgeBrokerResult",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "raw_visit_pack_ui",
    maxLatencyMs: 500,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/edge",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "edge.visit_pack_summary",
  },
  {
    key: "edge.what_changed_explain",
    publicName: "Local What Changed explanation",
    internalOwner: "companion",
    responsibleDomain: "mission",
    intendedUsers: ["participant", "worker", "coordinator"],
    intendedPurpose:
      "Deterministic local explanation of mission dependency changes with a processing receipt.",
    prohibitedUses: [
      "require_ai_device",
      "app_store_ai_claim",
      "operational_writes",
    ],
    maturity: "controlled_pilot",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_EDGE_AI_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "WhatChangedEntry[]",
    outputSchemaRef: "EdgeBrokerResult",
    permittedDataClasses: ["operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "raw_what_changed_list",
    maxLatencyMs: 500,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/ai-platform/edge",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "edge.what_changed_explain",
  },
  {
    key: "understanding.contextual",
    publicName: "Understanding contextual companion",
    internalOwner: "ai-platform",
    responsibleDomain: "understanding",
    intendedUsers: ["participant", "coordinator"],
    intendedPurpose:
      "Synthesise goals, routines, informal supports, and living-arrangement review signals under DDA/NDIS constraints.",
    prohibitedUses: [
      "invent_diagnosis",
      "determine_sda_sil_eligibility",
      "override_plan_manager",
      "autonomous_bookings",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_UNDERSTANDING_ENABLED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "understanding-dda-ndis-v1",
    toolAllowlist: [
      "getParticipantKnowledgeGraph",
      "listInformalSupports",
      "getLivingArrangementRiskSignal",
    ],
    inputSchemaRef: "UnderstandingAgentTurnInput",
    outputSchemaRef: "UnderstandingAgentTurnResult",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "refuse_when_unconfigured",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "tests/understanding",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "understanding.contextual",
  },
  {
    key: "agent.aura_harness",
    version: "1.0.0",
    publicName: "AURA agentic risk harness",
    internalOwner: "ai-platform",
    responsibleDomain: "aura-harness",
    intendedUsers: ["system", "coordinator"],
    intendedPurpose:
      "Evaluate tool actions for risk (gamma/concentration) and require HITL when thresholds trip.",
    prohibitedUses: [
      "auto_execute_consequential_writes",
      "grant_runtime_authority",
      "infer_capacity",
      "alter_consent",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_AURA_HARNESS_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "AuraToolEvaluationInput",
    outputSchemaRef: "HarnessDecision",
    permittedDataClasses: ["operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "NO_OPERATIONAL_AUTHORITY",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "fail_closed_block_tool",
    maxLatencyMs: 2000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/aura-harness",
    algorithmRegisterRef: "alg.aura_harness",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.aura_harness",
  },
  {
    key: "agent.aura_recognise",
    version: "1.0.0",
    publicName: "AURA Recognise evaluators",
    internalOwner: "ai-platform",
    responsibleDomain: "aura-harness",
    intendedUsers: ["system"],
    intendedPurpose:
      "Score autonomy-relevant dimensions (capability dependence, irreversibility, cascading impact).",
    prohibitedUses: [
      "grant_runtime_authority",
      "capacity_scoring",
      "participant_dangerousness_labels",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_AURA_HARNESS_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "RecogniseEvaluationInput",
    outputSchemaRef: "RecogniseAutonomyScores",
    permittedDataClasses: ["operational"],
    prohibitedDataClasses: ["credentials_secrets"],
    authorityCeiling: "NO_OPERATIONAL_AUTHORITY",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "omit_recognise_block",
    maxLatencyMs: 1000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/aura-harness",
    algorithmRegisterRef: "alg.aura_recognise",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "agent.aura_recognise",
  },
  {
    key: "navigator.provider_search.interpret",
    version: "1.0.0",
    publicName: "Navigator provider-search interpreter",
    internalOwner: "search-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate"],
    intendedPurpose:
      "Interpret a participant provider-search request into structured filters under consent.",
    prohibitedUses: [
      "invent_providers",
      "infer_diagnosis",
      "determine_ndis_eligibility",
      "execute_bookings",
      "clinical_decision",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_PILOT_ENABLED",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "navigator-interpret-v1",
    toolAllowlist: ["ndis_search_interpret"],
    inputSchemaRef: "NavigatorInterpretInput",
    outputSchemaRef: "SearchInterpretation",
    permittedDataClasses: ["public", "operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding", "financial"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 30,
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "deterministic_passthrough_or_escalate",
    maxLatencyMs: 8000,
    tokenBudget: 4000,
    costBudgetUsd: 0.05,
    evaluationSuite: "tests/navigator",
    algorithmRegisterRef: "alg.navigator_interpret",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.provider_search.interpret",
  },
  {
    key: "navigator.provider_search.reply",
    version: "1.0.0",
    publicName: "Navigator provider-search reply",
    internalOwner: "search-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate"],
    intendedPurpose:
      "Optional accessible commentary grounded in deterministic shortlist results.",
    prohibitedUses: [
      "invent_availability",
      "book_services",
      "override_hard_constraints",
      "clinical_decision",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_PILOT_MODEL_ASSISTED",
    backend: "model_backed",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "navigator-reply-v1",
    toolAllowlist: ["clarify"],
    inputSchemaRef: "NavigatorReplyInput",
    outputSchemaRef: "NavigatorReplyStream",
    permittedDataClasses: ["public", "operational"],
    prohibitedDataClasses: ["credentials_secrets", "financial", "safeguarding"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 30,
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: false,
    participantApprovalRequired: false,
    fallbackBehaviour: "template_reply_without_model",
    maxLatencyMs: 20000,
    tokenBudget: 6000,
    costBudgetUsd: 0.1,
    evaluationSuite: "tests/navigator",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.provider_search.reply",
  },
  {
    key: "navigator.provider_search.match",
    version: "1.0.0",
    publicName: "Navigator deterministic provider match",
    internalOwner: "search-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate"],
    intendedPurpose:
      "Apply hard constraints then participant-controlled ranking to approved provider data.",
    prohibitedUses: [
      "relax_hard_constraints",
      "rank_by_complexity_or_desirability",
      "disability_derived_proxies",
      "execute_bookings",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_PILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: ["ndis_provider_hard_filter", "preference_rank"],
    inputSchemaRef: "NavigatorMatchInput",
    outputSchemaRef: "NavigatorShortlist",
    permittedDataClasses: ["public", "operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 60,
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: false,
    participantApprovalRequired: true,
    fallbackBehaviour: "explicit_no_match",
    maxLatencyMs: 5000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/navigator",
    algorithmRegisterRef: "alg.navigator_match",
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.provider_search.match",
  },
  {
    key: "navigator.provider_search.draft_service_request",
    version: "1.0.0",
    publicName: "Navigator service-request draft envelope",
    internalOwner: "search-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate"],
    intendedPurpose:
      "Create a draft-only service-request or filter-transfer action envelope for human approval.",
    prohibitedUses: [
      "book_or_cancel_service",
      "approve_or_pay",
      "change_participant_records",
      "submit_incident_or_regulatory_report",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_PILOT_ENVELOPES",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "GovernedActionEnvelopeCreate",
    outputSchemaRef: "GovernedActionEnvelope",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets", "financial"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 30,
    authorityCeiling: "DRAFT_ONLY",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "refuse_and_escalate",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/navigator",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.provider_search.draft_service_request",
  },
  {
    key: "navigator.provider_search.escalate",
    version: "1.0.0",
    publicName: "Navigator human escalation",
    internalOwner: "ai-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate", "coordinator"],
    intendedPurpose:
      "Escalate unsafe, unsupported, or uncertain Navigator requests to a human reviewer.",
    prohibitedUses: [
      "allege_fraud_abuse_or_misconduct",
      "disclose_to_alleged_perpetrator",
      "auto_execute_after_escalation",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_PILOT_ENABLED",
    backend: "deterministic",
    modelIdentifier: null,
    promptVersion: null,
    toolAllowlist: [],
    inputSchemaRef: "NavigatorEscalationInput",
    outputSchemaRef: "ActHandoff",
    permittedDataClasses: ["operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 120,
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    humanReviewRequired: true,
    participantApprovalRequired: false,
    fallbackBehaviour: "queue_and_notify",
    maxLatencyMs: 3000,
    tokenBudget: null,
    costBudgetUsd: null,
    evaluationSuite: "tests/navigator",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.provider_search.escalate",
  },
  {
    key: "navigator.agents_sdk.manager",
    version: "1.0.0",
    publicName: "Navigator Agents SDK manager",
    internalOwner: "ai-platform",
    responsibleDomain: "navigator-pilot",
    intendedUsers: ["participant", "authorised_delegate"],
    intendedPurpose:
      "Governed multi-agent orchestration adapter for participant Navigator workflows. Access domain live only in first slice.",
    prohibitedUses: [
      "book_or_cancel_service",
      "approve_or_pay",
      "assign_worker",
      "alter_consent",
      "clinical_decision",
      "safeguarding_finding",
      "regulatory_submission",
      "broaden_tool_allowlist",
    ],
    maturity: "experimental",
    productionClaimStatus: "not_claimable",
    featureFlag: "MAPABLE_NAVIGATOR_AGENTS_SDK_ENABLED",
    backend: "hybrid",
    modelIdentifier: "SEARCH_INTERPRETER_MODEL",
    promptVersion: "navigator-agents-sdk-v1",
    toolAllowlist: [
      "access_provider_search",
      "care_consult",
      "transport_consult",
      "jobs_consult",
      "safeguarding_draft_escalation",
      "compliance_read_draft",
      "propose_draft_summary",
      "consult_access_specialist",
      "consult_care_specialist",
      "consult_transport_specialist",
      "consult_jobs_specialist",
      "consult_safeguarding_specialist",
      "consult_compliance_specialist",
    ],
    inputSchemaRef: "AgentsSdkManagerTurnInput",
    outputSchemaRef: "AgentsSdkManagerTurnResult",
    permittedDataClasses: ["public", "operational", "participant_pii"],
    prohibitedDataClasses: ["credentials_secrets", "safeguarding", "financial"],
    requiredConsentScopes: ["profile.read"],
    approvalExpiryMinutes: 30,
    authorityCeiling: "READ_ONLY_EXPLAIN",
    humanReviewRequired: true,
    participantApprovalRequired: true,
    fallbackBehaviour: "deterministic_fallback_or_refuse",
    maxLatencyMs: 30000,
    tokenBudget: 8000,
    costBudgetUsd: 0.2,
    evaluationSuite: "tests/agents-sdk",
    algorithmRegisterRef: null,
    reviewDueDate: "2026-12-31",
    killSwitchKey: "navigator.agents_sdk.manager",
  },
];
