export const GUARDIAN_REASON_CODES = [
  "GUARDIAN_DISABLED",
  "PURPOSE_NOT_ALLOWED",
  "PURPOSE_MARKETING_PROHIBITED",
  "INSUFFICIENT_AUTHORITY",
  "CONSENT_SCOPE_MISSING",
  "CONSENT_REVOKED_OR_ABSENT",
  "CROSS_TENANT_DENIED",
  "MINIMUM_NECESSARY_VIOLATION",
  "PURPOSE_SCOPE_EXCEEDED",
  "SENSITIVITY_REQUIRES_PRIVATE",
  "SENSITIVITY_NO_GENERAL_PURPOSE_MODEL",
  "EXTERNAL_PROCESSING_DISABLED",
  "PRIVATE_INFERENCE_UNAVAILABLE",
  "PRIVATE_FAILOVER_NO_CLOUD",
  "PROCESSOR_NOT_APPROVED",
  "PROCESSOR_PROHIBITED_DATA_CLASS",
  "PROCESSOR_PURPOSE_NOT_PERMITTED",
  "CLOUD_BYPASS_REJECTED",
  "SAFEGUARDING_CUE_DETECTED",
  "ROUTE_HUMAN_REVIEW",
  "ROUTE_INCIDENT_TRIAGE",
  "ROUTE_COMPLAINTS",
  "REDACTION_REQUIRED",
  "PARTICIPANT_CONFIRMATION_REQUIRED",
  "SECURITY_QUARANTINE",
  "DETERMINISTIC_FALLBACK",
  "ALLOW_WITHIN_POLICY",
  "MODEL_INFERENCE_DISABLED",
] as const;

export type GuardianReasonCode = (typeof GUARDIAN_REASON_CODES)[number];

export function isGuardianReasonCode(value: string): value is GuardianReasonCode {
  return (GUARDIAN_REASON_CODES as readonly string[]).includes(value);
}
