import type { MapAbleAgentManifest } from "./types";

/**
 * Canonical operational agent manifests.
 * Capability keys reference lib/ai/platform/capabilities/registry.ts only.
 * Model/prompt/tool config lives on capabilities — not duplicated here.
 */
export const MAPABLE_AGENT_MANIFESTS: readonly MapAbleAgentManifest[] = [
  {
    id: "mission_orchestrator",
    version: "1.0.0",
    name: "Mission Orchestrator",
    description:
      "Accepts a participant-approved objective, selects bounded specialists, uses the mission graph, and combines results without executing domain actions.",
    role: "orchestrate_mission",
    domains: ["core"],
    capabilityKeys: [
      "mission.copilot",
      "mission.evidence_graph",
      "mission.semantic_retrieval",
      "relational.interpret",
      "relational.explain",
    ],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    activation: "always_for_participant_missions",
    handoffs: [
      "participant_authority",
      "evidence_intelligence",
      "access_mobility",
      "support_participation",
      "work_participation",
      "continuity_assurance",
      "finance_administration",
    ],
    requiredConsentScopes: [],
    requiredHumanReviewFor: [
      "authority_exception",
      "unresolved_specialist_conflict",
    ],
    prohibitedActions: [
      "assign_support_worker",
      "confirm_transport",
      "approve_or_pay_invoice",
      "approve_ndis_claim",
      "alter_funding_route",
      "accept_service_agreement",
      "alter_consent",
      "determine_incident_reportability",
      "substantiate_or_dismiss_allegation",
      "close_incident_or_complaint",
      "approve_restrictive_practice",
      "contact_emergency_services",
      "modify_own_policies_prompts_tools_or_authority",
    ],
    fallbackAgentId: "participant_authority",
    evaluationSuite: "tests/ai-platform/agent-registry",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "participant_authority",
    version: "1.0.0",
    name: "Participant Authority",
    description:
      "Preserves participant instructions, preferences, exclusions, consent scopes, AAC requirements, and non-AI paths. Does not infer consent or capacity.",
    role: "protect_participant_authority",
    domains: ["core"],
    capabilityKeys: [
      "agent.aura_harness",
      "agent.aura_recognise",
      "relational.clarify",
      "relational.draft",
      "human.help.request",
      "access.search.read",
    ],
    authorityCeiling: "NO_OPERATIONAL_AUTHORITY",
    activation: "always_for_participant_missions",
    handoffs: ["mission_orchestrator", "continuity_assurance"],
    requiredConsentScopes: [],
    requiredHumanReviewFor: [
      "missing_consent",
      "disclosure_boundary",
      "authority_exception",
    ],
    prohibitedActions: [
      "infer_consent_from_behaviour",
      "infer_capacity_from_communication_style",
      "alter_consent",
      "create_legal_delegation",
      "publish_participant_information",
      "retain_hidden_long_term_memory",
    ],
    fallbackAgentId: "non_ai_path",
    evaluationSuite: "tests/ai-platform/agent-authority",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "evidence_intelligence",
    version: "1.0.0",
    name: "Evidence Intelligence",
    description:
      "Retrieves authorised evidence with provenance, flags stale/conflicting/missing evidence, and never converts inference into verified fact.",
    role: "evidence_retrieval",
    domains: ["core", "care", "access"],
    capabilityKeys: [
      "intake.document_classify",
      "intake.field_extract",
      "mission.evidence_graph",
      "mission.semantic_retrieval",
      "edge.visit_pack_summary",
      "edge.what_changed_explain",
    ],
    authorityCeiling: "DRAFT_ONLY",
    activation: "domain_gated",
    handoffs: ["mission_orchestrator", "participant_authority"],
    requiredConsentScopes: [],
    requiredHumanReviewFor: ["conflicting_evidence", "stale_evidence"],
    prohibitedActions: [
      "execute_instructions_from_retrieved_documents",
      "clinical_decision",
      "definitive_legal_conclusion",
      "determine_incident_reportability",
    ],
    fallbackAgentId: "mission_orchestrator",
    evaluationSuite: "tests/ai-platform/mission-graph",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "access_mobility",
    version: "1.0.0",
    name: "Access and Mobility",
    description:
      "Analyses venue accessibility, route constraints and transport readiness. May recommend options; cannot confirm or dispatch transport.",
    role: "access_and_transport_analysis",
    domains: ["access", "transport"],
    capabilityKeys: [
      "search.nl_interpreter",
      "search.access_needs_interpreter",
      "navigator.provider_search.interpret",
      "navigator.provider_search.reply",
      "access_intelligence_next.preflight",
      "accesscast.forecast",
    ],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    activation: "domain_gated",
    handoffs: ["mission_orchestrator", "continuity_assurance", "support_participation"],
    requiredConsentScopes: [],
    requiredHumanReviewFor: ["transport_continuity", "access_verification"],
    prohibitedActions: ["confirm_transport", "assign_support_worker"],
    fallbackAgentId: "non_ai_path",
    evaluationSuite: "tests/ai-platform/agent-activation",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "support_participation",
    version: "1.0.0",
    name: "Support Participation",
    description:
      "Evaluates support request readiness and compatibility evidence. May draft service requests and propose matches; cannot assign workers or accept agreements.",
    role: "care_and_support_analysis",
    domains: ["care"],
    capabilityKeys: [
      "agent.disability_services",
      "agent.booking_services",
      "matching.care_rules",
      "matching.ai_overlay",
      "navigator.provider_search.match",
      "navigator.provider_search.draft_service_request",
      "navigator.provider_search.escalate",
    ],
    authorityCeiling: "SUGGEST_WITH_HUMAN_REVIEW",
    activation: "domain_gated",
    handoffs: [
      "mission_orchestrator",
      "participant_authority",
      "continuity_assurance",
    ],
    requiredConsentScopes: [],
    requiredHumanReviewFor: [
      "worker_assignment_boundary",
      "service_agreement_boundary",
    ],
    prohibitedActions: [
      "assign_support_worker",
      "accept_service_agreement",
      "declare_worker_competent",
    ],
    fallbackAgentId: "non_ai_path",
    evaluationSuite: "tests/ai-platform/agent-activation",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "work_participation",
    version: "1.0.0",
    name: "Work Participation",
    description:
      "Jobs reasoning: accessible job discovery, workplace adjustment planning, and employment support coordination under participant-controlled disclosure.",
    role: "jobs_and_employment_analysis",
    domains: ["jobs"],
    // Phase 1: shared read-only retrieval only; jobs-specific keys are Phase 2.
    capabilityKeys: ["mission.semantic_retrieval"],
    authorityCeiling: "READ_ONLY_EXPLAIN",
    activation: "domain_gated",
    handoffs: ["mission_orchestrator", "participant_authority", "access_mobility"],
    requiredConsentScopes: ["disability_disclosure"],
    requiredHumanReviewFor: ["disability_disclosure"],
    prohibitedActions: [
      "publish_participant_information",
      "infer_goals_from_diagnosis",
    ],
    fallbackAgentId: "non_ai_path",
    evaluationSuite: "tests/ai-platform/agent-activation",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "continuity_assurance",
    version: "1.0.0",
    name: "Continuity Assurance",
    description:
      "Detects missing dependencies and likely mission failure points, produces recovery options, and routes safeguarding/financial/legal/clinical/authority exceptions to human review.",
    role: "continuity_and_exception_routing",
    domains: ["core", "care", "transport", "access"],
    capabilityKeys: ["mission.evidence_graph", "mission.semantic_retrieval"],
    // Ceiling capped by shared mission graph/retrieval capabilities (READ_ONLY).
    authorityCeiling: "READ_ONLY_EXPLAIN",
    activation: "domain_gated",
    handoffs: ["mission_orchestrator", "participant_authority"],
    requiredConsentScopes: [],
    requiredHumanReviewFor: [
      "safeguarding",
      "financial_exception",
      "legal_exception",
      "clinical_exception",
      "authority_exception",
    ],
    prohibitedActions: [
      "determine_incident_reportability",
      "substantiate_or_dismiss_allegation",
      "close_incident_or_complaint",
      "approve_restrictive_practice",
      "clinical_decision",
      "contact_emergency_services",
    ],
    fallbackAgentId: "human",
    evaluationSuite: "tests/ai-platform/agent-safeguarding",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
  {
    id: "finance_administration",
    version: "1.0.0",
    name: "Finance Administration",
    description:
      "Explains invoices, evidence, funding records and discrepancies; prepares review questions and drafts. Cannot approve claims, pay invoices, or alter funding routes.",
    role: "finance_explanation",
    domains: ["payments"],
    capabilityKeys: ["billing.copilot", "billing.evidence_copilot"],
    authorityCeiling: "DRAFT_ONLY",
    activation: "domain_gated",
    handoffs: ["mission_orchestrator", "participant_authority"],
    requiredConsentScopes: [],
    requiredHumanReviewFor: ["invoice_discrepancy", "funding_route_change"],
    prohibitedActions: [
      "approve_ndis_claim",
      "approve_or_pay_invoice",
      "alter_funding_route",
    ],
    fallbackAgentId: "non_ai_path",
    evaluationSuite: "tests/billing-a11y",
    owner: "mapable-ai-platform",
    lastReview: "2026-08-24",
  },
] as const;
