import { sql } from "drizzle-orm";
  import { pgTable, text, varchar, integer, boolean, timestamp, decimal, pgEnum, jsonb, json, serial, uuid } from "drizzle-orm/pg-core";
  import { createInsertSchema } from "drizzle-zod";
  import { z } from "zod";
  
  import { userRoleEnum } from "./common";

  export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  role: userRoleEnum("role").notNull().default("participant"),
  location: text("location"),
  bio: text("bio"),
  avatar: text("avatar"),
  isVerified: boolean("is_verified").default(false),
  accessNeeds: text("access_needs").array(),
  languages: text("languages").array(),
  skills: text("skills").array(),
  ndisNumber: text("ndis_number"),
  planStartDate: text("plan_start_date"),
  planEndDate: text("plan_end_date"),
  phoneNumber: text("phone_number"),
  auth0Sub: text("auth0_sub"),
  stripeCustomerId: text("stripe_customer_id"),
  orbCustomerId: text("orb_customer_id"),
  orbSubscriptionId: text("orb_subscription_id"),
  managementType: text("management_type"),
  providerAbn: text("provider_abn"),
  providerBusinessName: text("provider_business_name"),
  providerRegistrationGroups: text("provider_registration_groups").array(),
  abn: text("abn"),
  qbAccessToken: text("qb_access_token"),
  qbRefreshToken: text("qb_refresh_token"),
  qbRealmId: text("qb_realm_id"),
  qbTokenExpiresAt: timestamp("qb_token_expires_at"),
  qbConnectedAt: timestamp("qb_connected_at"),
  notifyOrderUpdates: boolean("notify_order_updates").notNull().default(true),
  autoDebitEnabled: boolean("auto_debit_enabled").notNull().default(false),
  autoDebitGraceDays: integer("auto_debit_grace_days").notNull().default(2),
  defaultBecsPaymentMethodId: text("default_becs_payment_method_id"),
  stripeAccountId: text("stripe_account_id"),
  stripeAccountStatus: text("stripe_account_status"),
  stripeChargesEnabled: boolean("stripe_charges_enabled").notNull().default(false),
  stripePayoutsEnabled: boolean("stripe_payouts_enabled").notNull().default(false),
  stripeRequirementsDue: jsonb("stripe_requirements_due"),
});

export const workers = pgTable("workers", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull(),
  title: text("title").notNull(),
  specializations: text("specializations").array(),
  hourlyRate: decimal("hourly_rate", { precision: 10, scale: 2 }),
  transportCapable: boolean("transport_capable").default(false),
  transportType: text("transport_type"),
  wheelchairAccessible: boolean("wheelchair_accessible").default(false),
  ndisVerified: boolean("ndis_verified").default(false),
  rating: decimal("rating", { precision: 3, scale: 2 }).default("0"),
  reviewCount: integer("review_count").default(0),
  availability: text("availability"),
  photo: text("photo"),
  abn: text("abn"),
  abnVerified: boolean("abn_verified").default(false),
  insuranceExpiry: text("insurance_expiry"),
  firstAidExpiry: text("first_aid_expiry"),
  wwccNumber: text("wwcc_number"),
  wwccExpiry: text("wwcc_expiry"),
  screeningNumber: text("screening_number"),
  screeningClearanceStatus: text("screening_clearance_status"),
  screeningExpiry: text("screening_expiry"),
});
  export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
  fullName: true,
  email: true,
  role: true,
  location: true,
  bio: true,
  avatar: true,
  accessNeeds: true,
  languages: true,
  skills: true,
  ndisNumber: true,
  planStartDate: true,
  planEndDate: true,
  phoneNumber: true,
  managementType: true,
  providerAbn: true,
  providerBusinessName: true,
  providerRegistrationGroups: true,
  abn: true,
}).extend({
  id: z.string().optional(),
  auth0Sub: z.string().optional(),
  isVerified: z.boolean().optional(),
});

export const insertWorkerSchema = createInsertSchema(workers).pick({
  userId: true,
  title: true,
  specializations: true,
  hourlyRate: true,
  transportCapable: true,
  transportType: true,
  wheelchairAccessible: true,
  ndisVerified: true,
  availability: true,
  photo: true,
  abn: true,
  abnVerified: true,
  insuranceExpiry: true,
  firstAidExpiry: true,
  wwccNumber: true,
  wwccExpiry: true,
  screeningNumber: true,
  screeningClearanceStatus: true,
  screeningExpiry: true,
});
  export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertWorker = z.infer<typeof insertWorkerSchema>;
export type Worker = typeof workers.$inferSelect;
  