import type { DomainSeed } from "@/lib/convergence-os/types";

/** Verified inventory from main + open PR audit (ConvergenceOS Wave 0). */
export const CANONICAL_DOMAIN_SEEDS: DomainSeed[] = [
  {
    domainKey: "identity.user",
    name: "User",
    purpose: "Root authentication identity for all MapAble roles",
    canonicalModel: "User",
    canonicalService: "lib/auth/",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "identity.organisation",
    name: "Organisation",
    purpose: "Ops tenancy for care, transport, NDIS, incidents",
    canonicalModel: "Organisation",
    canonicalService: "lib/auth/permissions.ts",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
    duplicateImplementations: ["Provider (marketplace parallel)"],
  },
  {
    domainKey: "identity.membership",
    name: "OrganisationMember",
    purpose: "Org membership spine",
    canonicalModel: "OrganisationMember",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
    notes: "Also ProviderUserRole, TenantMembership for other planes",
  },
  {
    domainKey: "participant.profile",
    name: "ParticipantProfile",
    purpose: "Participant demographics and NDIS references",
    canonicalModel: "ParticipantProfile",
    canonicalApi: "/api/participant-profile",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "participant.accessibility_profile",
    name: "AccessibilityProfile",
    purpose: "Presentation and access preferences",
    canonicalModel: "AccessibilityProfile",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "participant.access_passport",
    name: "AccessPassport",
    purpose: "Participant-selected functional access needs (not diagnosis)",
    canonicalModel: "AiAccessPassport",
    owningProgramme: "Access Intelligence",
    authoritativePath: "PR #273 target rename",
    status: "target",
    compatibilityAliases: ["AiAccessPassport"],
    notes: "Not on main; rename target from Access Intelligence PRs",
  },
  {
    domainKey: "participant.consent",
    name: "ConsentRecord",
    purpose: "Sharing and consent records",
    canonicalModel: "ConsentRecord",
    canonicalService: "lib/consent/consent-service.ts",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "missions.case",
    name: "Case",
    purpose: "Interim mission/case management on main",
    canonicalModel: "Case",
    canonicalService: "lib/cases/",
    canonicalApi: "/api/cases",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "interim",
    notes: "Bridge via CaseMissionAdapter until CareOSMission lands",
  },
  {
    domainKey: "missions.careos_mission",
    name: "CareOSMission",
    purpose: "Canonical mission source of truth for CareOS and programmes",
    canonicalModel: "CareOSMission",
    owningProgramme: "CareOS",
    authoritativePath: "PR #252 agent/careos-platform-completion",
    status: "target",
    duplicateImplementations: [
      "AURA tip schema",
      "ContinuityOS #287",
      "CareOS foundation #232",
    ],
    migrationState: "awaiting_canonical_merge",
    notes:
      "Triple-add collision: only #252 should own DDL; others must extend or rebase",
  },
  {
    domainKey: "missions.case_mission_adapter",
    name: "CaseMissionAdapter",
    purpose: "Compatibility adapter writing Case as mission view",
    canonicalModel: "Case",
    canonicalService: "lib/programmes/adapters/case-mission-adapter.ts",
    owningProgramme: "Shared Programme Foundation",
    authoritativePath: "PR #279",
    status: "adapter",
  },
  {
    domainKey: "aura.proposal",
    name: "AuraActionProposal",
    purpose: "Immutable AURA proposals with shadow review",
    canonicalModel: "AuraActionProposal",
    canonicalService: "lib/aura/",
    canonicalApi: "/api/intelligence/aura/",
    owningProgramme: "AURA",
    authoritativePath: "PR #267–#277",
    status: "experimental",
  },
  {
    domainKey: "aura.execution",
    name: "AuraExecutionApproval",
    purpose: "Approved AURA execution receipts (must stay gated off)",
    canonicalModel: "AuraExecutionApproval",
    canonicalService: "lib/aura/execution/",
    owningProgramme: "AURA",
    authoritativePath: "PR #272",
    status: "experimental",
    notes: "Execution flags must default false",
  },
  {
    domainKey: "places.access_place",
    name: "AccessPlace",
    purpose: "Public accessible place identity",
    canonicalModel: "AccessPlace",
    canonicalService: "lib/access-*/",
    owningProgramme: "Access",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
    duplicateImplementations: ["AccessiblePlace", "AiAccessPlace"],
  },
  {
    domainKey: "places.accessible_place",
    name: "AccessiblePlace",
    purpose: "Legacy parallel place stack",
    canonicalModel: "AccessiblePlace",
    owningProgramme: "Access",
    authoritativePath: "prisma/schema.prisma",
    status: "deprecated",
    deprecationState: "no_new_writes",
    notes: "New writes must target AccessPlace only",
  },
  {
    domainKey: "places.floor_plan",
    name: "AccessFloorPlan",
    purpose: "Indoor floor plans on main",
    canonicalModel: "AccessFloorPlan",
    canonicalService: "lib/indoor-accessibility/",
    owningProgramme: "Indoor Accessibility",
    authoritativePath: "prisma/migrations/20260716120000_indoor_accessibility_platform",
    status: "canonical",
    notes: "Many open tips delete this — rebase hazard",
  },
  {
    domainKey: "places.ai_access_place",
    name: "AiAccessPlace",
    purpose: "Access Intelligence place fork on open PRs",
    canonicalModel: "AiAccessPlace",
    owningProgramme: "Access Intelligence",
    authoritativePath: "PR #266/#273",
    status: "duplicate",
    notes: "Must become extension of AccessPlace, not second SoR",
  },
  {
    domainKey: "places.civic_asset",
    name: "CivicAsset",
    purpose: "Civic asset registry and static accessibility projection",
    canonicalModel: "CivicAsset",
    canonicalService: "lib/civic-access/",
    owningProgramme: "Civic Access Infrastructure",
    authoritativePath: "PR #284",
    status: "target",
  },
  {
    domainKey: "places.accessibility_asset",
    name: "AccessibilityAsset",
    purpose: "AccessibilityOps asset and shadow rule evaluation",
    canonicalModel: "AccessibilityAsset",
    canonicalService: "lib/accessibility-ops/",
    owningProgramme: "AccessibilityOps",
    authoritativePath: "PR #282",
    status: "target",
    notes: "Related to CivicAsset but distinct ops domain; bind via AccessPlace FK",
  },
  {
    domainKey: "transport.trip",
    name: "TransportTrip",
    purpose: "Canonical accessible transport trip lifecycle",
    canonicalModel: "TransportTrip",
    canonicalService: "lib/transport/transport-trip-service.ts",
    owningProgramme: "Transport",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "transport.booking_legacy",
    name: "TransportBooking",
    purpose: "Legacy transport booking still written by orchestration",
    canonicalModel: "TransportBooking",
    canonicalService: "lib/transport/transport-booking-service.ts",
    owningProgramme: "Transport",
    authoritativePath: "prisma/schema.prisma",
    status: "deprecated",
    deprecationState: "active_writers_remain",
    notes: "Bridge via TRANSPORT_BOOKING_BRIDGE_ENABLED",
  },
  {
    domainKey: "care.shift",
    name: "CareShift",
    purpose: "Care shift operations",
    canonicalModel: "CareShift",
    canonicalService: "lib/care/care-shift-service.ts",
    owningProgramme: "Care",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "finance.invoice",
    name: "Invoice families",
    purpose: "Era-split invoicing stacks",
    canonicalModel: "BillingInvoice",
    owningProgramme: "Billing",
    authoritativePath: "prisma/schema.prisma",
    status: "interim",
    duplicateImplementations: ["Invoice", "BillingInvoice", "NdisInvoice"],
  },
  {
    domainKey: "finance.funding",
    name: "Funding sources",
    purpose: "Participant vs billing funding routes",
    canonicalModel: "ParticipantFundingSource",
    owningProgramme: "NDIS Gateway",
    authoritativePath: "PR #286 compatibility facades",
    status: "interim",
    duplicateImplementations: [
      "ParticipantFundingSource",
      "BillingFundingSource",
    ],
  },
  {
    domainKey: "ndis.gateway",
    name: "NDIS Gateway domain",
    purpose: "Canonical claim/funding-route facades without new Prisma tables",
    canonicalService: "lib/ndis-gateway/",
    owningProgramme: "NDIS Gateway",
    authoritativePath: "PR #286",
    status: "target",
    migrationState: "migration_free_wave1",
  },
  {
    domainKey: "rights.purpose",
    name: "RightsPurpose",
    purpose: "RightsOS purpose registry and shadow firewall",
    canonicalModel: "RightsPurpose",
    canonicalService: "lib/rights-os/",
    owningProgramme: "RightsOS",
    authoritativePath: "PR #280",
    status: "target",
    notes: "Default shadow mode; must not redefine Vault",
  },
  {
    domainKey: "vault.personal_access",
    name: "Personal Access Vault",
    purpose: "Vault item registry and selective disclosure",
    canonicalModel: "VaultItem",
    canonicalService: "lib/vault/",
    owningProgramme: "Personal Access Vault",
    authoritativePath: "PR #281",
    status: "target",
    duplicateImplementations: [
      "PersonalVault/PersonalVaultItem on RightsOS #280",
      "PersonalDataVaultRequest on main",
    ],
  },
  {
    domainKey: "governance.audit",
    name: "AuditEvent",
    purpose: "Platform audit trail",
    canonicalModel: "AuditEvent",
    canonicalService: "lib/audit/audit-event-service.ts",
    owningProgramme: "MapAble Core",
    authoritativePath: "prisma/schema.prisma",
    status: "canonical",
  },
  {
    domainKey: "governance.outbox",
    name: "CloudEventOutbox",
    purpose: "Transactional outbox target (not on main)",
    canonicalModel: "CloudEventOutbox",
    owningProgramme: "CareOS",
    authoritativePath: "PR #252",
    status: "target",
  },
  {
    domainKey: "governance.programme_source",
    name: "ProgrammeSourceRecord",
    purpose: "Programme source registry",
    canonicalModel: "ProgrammeSourceRecord",
    owningProgramme: "Shared Programme Foundation",
    authoritativePath: "PR #279",
    status: "target",
    notes: "Coordinate with Platform Assurance #278",
  },
  {
    domainKey: "assurance.platform",
    name: "Platform Assurance",
    purpose: "Standards version registry and worker trust gaps",
    canonicalService: "lib/platform-assurance/",
    owningProgramme: "Platform Assurance",
    authoritativePath: "PR #278",
    status: "target",
  },
  {
    domainKey: "convergence.control_plane",
    name: "ConvergenceOS",
    purpose: "Architecture, schema, branch, migration and release control plane",
    canonicalService: "lib/convergence-os/",
    canonicalApi: "/api/convergence/",
    owningProgramme: "Platform Assurance",
    authoritativePath: "lib/convergence-os/",
    status: "canonical",
    notes: "Records and validates; humans approve; GitHub/CI execute",
  },
  {
    domainKey: "pbs.positive_behaviour_support",
    name: "Positive Behaviour Support",
    purpose:
      "Controlled-pilot practitioner-led PBS workspace (not clinical substitution)",
    canonicalModel: "PbsEngagement / PbsPlan",
    canonicalService: "lib/positive-behaviour-support/",
    canonicalApi: "/api/positive-behaviour-support/",
    owningProgramme: "Positive Behaviour Support",
    authoritativePath: "lib/positive-behaviour-support/",
    status: "canonical",
    notes:
      "publicClaimAllowed false; DRAFT_ONLY AI; assignment/org scoped access",
  },
];
