import type { CapabilitySeed } from "@/lib/convergence-os/types";

export const CAPABILITY_SEEDS: CapabilitySeed[] = [
  {
    capabilityKey: "access.place_search",
    name: "Accessibility place search",
    programme: "Access",
    userValue: "Find accessible places matching needs",
    canonicalOwner: "places.access_place",
    implementationPaths: ["app/access/", "lib/access-fit/"],
    authorityLevel: "read",
    readWrite: "read",
    maturity: "production_gated",
    persistenceType: "prisma",
    runtimeMode: "live",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: true,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "access.indoor_floor_plan",
    name: "Indoor floor-plan viewing",
    programme: "Indoor Accessibility",
    userValue: "View indoor floor plans for venues",
    canonicalOwner: "places.floor_plan",
    implementationPaths: ["lib/indoor-accessibility/", "lib/floor-plan/"],
    featureFlags: ["floorPlanAuthoring", "INDOOR_FLAG_*"],
    maturity: "pilot",
    persistenceType: "prisma",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.trip_request",
    name: "Transport request",
    programme: "Transport",
    userValue: "Request accessible transport trips",
    canonicalOwner: "transport.trip",
    implementationPaths: ["lib/transport/", "app/api/transport/"],
    maturity: "production_gated",
    persistenceType: "prisma",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: true,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.driver_vehicle_verification",
    name: "Driver and vehicle verification",
    programme: "Transport",
    canonicalOwner: "transport.trip",
    implementationPaths: ["PR #276 app/api/provider/transport/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "aura.mission_planning",
    name: "AURA mission planning",
    programme: "AURA",
    canonicalOwner: "aura.proposal",
    implementationPaths: ["lib/aura/", "app/api/intelligence/aura/"],
    authorityLevel: "propose",
    maturity: "shadow",
    persistenceType: "prisma_and_memory",
    runtimeMode: "shadow",
    productionClaimStatus: "fixture_only",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "aura.approved_execution",
    name: "Approved AURA execution",
    programme: "AURA",
    canonicalOwner: "aura.execution",
    implementationPaths: ["lib/aura/execution/"],
    authorityLevel: "execution",
    externalSideEffects: true,
    participantApprovalRequired: true,
    maturity: "fixture_only",
    persistenceType: "prisma",
    runtimeMode: "gated_off",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Keep execution flags false; no auto-enable",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "rights.purpose_evaluation",
    name: "RightsOS purpose evaluation",
    programme: "RightsOS",
    canonicalOwner: "rights.purpose",
    implementationPaths: ["lib/rights-os/", "PR #280"],
    featureFlags: ["MAPABLE_RIGHTSOS_*"],
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "vault.disclosure_preview",
    name: "Vault disclosure preview",
    programme: "Personal Access Vault",
    canonicalOwner: "vault.personal_access",
    implementationPaths: ["lib/vault/", "PR #281"],
    featureFlags: ["MAPABLE_PERSONAL_ACCESS_VAULT_ENABLED"],
    participantApprovalRequired: true,
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "civic.asset_registry",
    name: "Civic asset registry",
    programme: "Civic Access Infrastructure",
    canonicalOwner: "places.civic_asset",
    implementationPaths: ["lib/civic-access/", "PR #284"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "a11yops.shadow_rules",
    name: "AccessibilityOps shadow rule evaluation",
    programme: "AccessibilityOps",
    canonicalOwner: "places.accessibility_asset",
    implementationPaths: ["lib/accessibility-ops/", "PR #282"],
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.funding_route_validation",
    name: "NDIS funding-route validation",
    programme: "NDIS Gateway",
    canonicalOwner: "ndis.gateway",
    implementationPaths: ["lib/ndis-gateway/", "PR #286"],
    maturity: "scaffolded",
    persistenceType: "none",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.claim_submission",
    name: "Claim submission",
    programme: "NDIS Gateway",
    canonicalOwner: "ndis.gateway",
    implementationPaths: ["lib/ndis/claiming/", "lib/integrations/adapters/"],
    featureFlags: ["NDIA_REAL_SUBMISSION_ENABLED"],
    externalSideEffects: true,
    maturity: "fixture_only",
    persistenceType: "prisma",
    runtimeMode: "mock",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "careos.mission_sor",
    name: "CareOS mission source of truth",
    programme: "CareOS",
    canonicalOwner: "missions.careos_mission",
    implementationPaths: ["PR #252"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "programmes.foundation",
    name: "Shared programme foundation",
    programme: "Shared Programme Foundation",
    implementationPaths: ["lib/programmes/", "PR #279"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "convergence.control_plane",
    name: "ConvergenceOS control plane",
    programme: "Platform Assurance",
    canonicalOwner: "convergence.control_plane",
    implementationPaths: ["lib/convergence-os/", "app/admin/convergence/"],
    featureFlags: ["MAPABLE_CONVERGENCE_OS_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    runtimeMode: "audit",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "access.intelligence_next",
    name: "Access Intelligence Next (Living Access Fabric)",
    programme: "Access Intelligence Next",
    canonicalOwner: "places.access_place",
    implementationPaths: ["lib/access-intelligence-next/"],
    featureFlags: ["MAPABLE_ACCESS_INTELLIGENCE_NEXT_*"],
    maturity: "shadow",
    persistenceType: "fixture_only",
    runtimeMode: "synthetic_shadow",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "accesscast.outlook",
    name: "AccessCast journey/place outlook",
    programme: "AccessCast",
    canonicalOwner: "places.access_place",
    implementationPaths: ["lib/accesscast/", "app/api/accesscast/", "app/accesscast/"],
    featureFlags: ["MAPABLE_ACCESSCAST_ENABLED", "MAPABLE_ACCESSCAST_MODE"],
    maturity: "fixture_only",
    persistenceType: "fixture_only",
    runtimeMode: "synthetic",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Keep AccessCast flags false; never present synthetic outlook as live truth",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.quotes",
    name: "Transport quotes (versioned, expiring)",
    programme: "Transport",
    userValue: "Receive accessible transport quotes before exact address disclosure",
    canonicalOwner: "transport.trip",
    implementationPaths: [
      "lib/transport/quotes/",
      "lib/transport/privacy/location-disclosure.ts",
      "app/api/transport/quotes/",
      "prisma/migrations/20260717120000_transport_quotes_persistent/",
    ],
    maturity: "scaffolded",
    persistenceType: "prisma",
    runtimeMode: "gated_off",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Prisma TransportQuote + versions; quote ≠ funding approval; acceptance ≠ exact address for providers",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "workforce.readiness",
    name: "Workforce assignment readiness (no auto-assign)",
    programme: "WorkforceOS",
    canonicalOwner: "org.membership",
    implementationPaths: ["lib/workforce-readiness/", "app/api/workforce/readiness/"],
    authorityLevel: "evaluate",
    featureFlags: ["MAPABLE_WORKFORCE_READINESS_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Never enable auto-assignment or worker scoring",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "mobile.companion",
    name: "Native MapAble Companion",
    programme: "Companion",
    canonicalOwner: "mobile.companion",
    implementationPaths: [
      "mobile-contracts/",
      "apps/companion/",
      "lib/companion/",
      "app/api/companion/",
    ],
    featureFlags: ["MAPABLE_COMPANION_ENABLED", "MAPABLE_COMPANION_VISIT_PACK_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "provider.ops_attention",
    name: "Provider Operations attention queue",
    programme: "Provider Operations",
    canonicalOwner: "provider.ops_projection",
    implementationPaths: [
      "lib/provider-ops/",
      "app/api/provider-ops/",
      "app/provider-ops/",
    ],
    featureFlags: ["MAPABLE_PROVIDER_OPS_ENABLED"],
    readWrite: "read",
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Read-only projection — never a second operational writer",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "billing.centre",
    name: "Billing Centre (BillingInvoice)",
    programme: "Billing",
    canonicalOwner: "finance.billing_invoice",
    implementationPaths: ["lib/billing/", "app/api/billing/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "care.request_loop",
    name: "Care request to evidence loop",
    programme: "Care",
    canonicalOwner: "care.case",
    implementationPaths: ["lib/care/", "app/api/care/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "care.recurring_schedules",
    name: "Recurring Care schedules and agreement amend",
    programme: "Care",
    canonicalOwner: "care.case",
    implementationPaths: [
      "lib/care/care-recurring-schedule-service.ts",
      "lib/care/care-agreement-service.ts",
      "app/api/care/bookings/",
      "prisma/migrations/20260717130000_care_recurring_schedules/",
    ],
    featureFlags: ["MAPABLE_CARE_RECURRING_SCHEDULES_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Flag default off; schedule is not a second agreement SoT; cancel Care ≠ cancel Transport",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "communication.passport",
    name: "Communication Passport",
    programme: "Access Passport",
    canonicalOwner: "access.passport",
    implementationPaths: [
      "lib/communication-passport/",
      "app/api/communication-passport/",
      "app/communication-passport/",
    ],
    participantApprovalRequired: true,
    featureFlags: ["MAPABLE_COMMUNICATION_PASSPORT_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "outcomes.ledger",
    name: "Outcomes and Impact Ledger",
    programme: "Outcomes",
    canonicalOwner: "outcomes.ledger",
    implementationPaths: ["lib/outcomes/"],
    maturity: "concept",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "pilot.starting_work",
    name: "Starting Work controlled pilot",
    programme: "Productisation Pilot",
    canonicalOwner: "missions.case",
    implementationPaths: [
      "docs/productisation/STARTING_WORK_PILOT.md",
      "lib/pilot/starting-work/",
      "app/api/pilot/starting-work/",
      "prisma/migrations/20260717140000_pilot_starting_work_runs/",
    ],
    featureFlags: [
      "MAPABLE_STARTING_WORK_PILOT_ENABLED",
      "MAPABLE_STARTING_WORK_SYNTHETIC_ONLY",
    ],
    maturity: "fixture_only",
    persistenceType: "prisma",
    runtimeMode: "synthetic",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Persists PilotStartingWorkRun with seed integration refs; syntheticOnly default; never market as live booking engine",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "continuity.participant_recovery",
    name: "Participant-controlled Continuity recovery",
    programme: "Continuity",
    canonicalOwner: "missions.case",
    implementationPaths: [
      "lib/continuity/participant-recovery-service.ts",
      "app/api/continuity/recovery/",
      "prisma/migrations/20260717150000_continuity_recovery_cases/",
    ],
    featureFlags: ["MAPABLE_CONTINUITY_RECOVERY_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Care cancel never auto-cancels Transport; participant approval required; no emergency automation",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "managed.support_delivery",
    name: "MapAble Managed Support (direct regulated delivery)",
    programme: "Managed Support",
    canonicalOwner: "care.case",
    implementationPaths: ["docs/strategy/OPERATING_LANES.md"],
    maturity: "concept",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Blocked by registration — do not fabricate NDIS registration or employed-workforce claims",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
];
