/**
 * Productisation + leadership train — PR action ledger.
 * Actions: merge | rebase | recreate | split | consolidate | supersede | close | archive | defer | retain_as_reference | retire_after_migration
 * Verified against live GitHub state at ledger refresh (2026-07-17T19:18Z, main fb80bc83); descriptions are not evidence of main source.
 */

export type PrLedgerAction =
  | "merge"
  | "rebase"
  | "recreate"
  | "split"
  | "consolidate"
  | "supersede"
  | "close"
  | "archive"
  | "defer"
  | "retain_as_reference"
  | "retire_after_migration";

export type PrActionLedgerEntry = {
  number: number;
  title: string;
  state: "OPEN" | "MERGED" | "CLOSED";
  isDraft: boolean;
  baseBranch: string;
  mergeable?: string;
  schemaImpact: "none" | "low" | "medium" | "high";
  canonicalDomains: string[];
  action: PrLedgerAction;
  reason: string;
  supersedes?: number[];
  supersededBy?: number;
  dependencies: number[];
  operatingModeNote: string;
  productionClaimAllowed: boolean;
  /** Unmerged stack depth when base is not main (informational). */
  stackDepth?: number;
};

/**
 * Superseded PRs that must be closed (or labelled supersede) before merge-train progress.
 * Includes AccessCast duplicates after #324 landed on main.
 */
export const SUPERSEDED_CLOSE_TARGETS: number[] = [
  289, 290, 291, 264, 287, 288, 320, 321, 322, 325, 202,
  // Opportunity-train duplicates / migration collisions (recreate after Moat)
  332, 333, 334, 335,
];

/** Maximum unmerged PR stack depth allowed by productisation policy. */
export const MAX_UNMERGED_STACK_DEPTH = 3;

/**
 * Immediate leadership train on current main (depth ≤ 3).
 * Strategy #331 → Trust Fabric #328 → Access Evidence #329.
 * #330 Starting Work DB queues when a slot frees; Transport/Care recreate after #330.
 */
export const PRODUCTISATION_TRAIN_HEADS: number[] = [331, 328, 329];

export const PR_ACTION_LEDGER: PrActionLedgerEntry[] = [
  {
    number: 300,
    title: "Repository controls and CI gates",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "retain_as_reference",
    reason: "Remediation CI landed on main; reference for gate expansion.",
    dependencies: [],
    operatingModeNote: "limited_release CI",
    productionClaimAllowed: false,
  },
  {
    number: 302,
    title: "ConvergenceOS Repository Twin and Architecture Constitution",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["convergence.control_plane"],
    action: "retain_as_reference",
    reason: "Constitution + twin on main; Wave 0 extends registries only.",
    dependencies: [300],
    operatingModeNote: "internal_alpha audit",
    productionClaimAllowed: false,
  },
  {
    number: 303,
    title: "Access Intelligence Next ontology foundation",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["places.access_place", "access.intelligence_next"],
    action: "retain_as_reference",
    reason: "AI Next foundation on main; do not fork legacy AI place writers.",
    dependencies: [],
    operatingModeNote: "synthetic_demo → shadow",
    productionClaimAllowed: false,
  },
  {
    number: 304,
    title: "Access Intelligence Next temporal evidence",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence_next"],
    action: "retain_as_reference",
    reason: "Temporal evidence on main.",
    dependencies: [303],
    operatingModeNote: "shadow",
    productionClaimAllowed: false,
  },
  {
    number: 306,
    title: "Access Intelligence Next door-to-room preflight",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence_next", "places.floor_plan"],
    action: "retain_as_reference",
    reason: "Preflight on main; unknown must remain unknown.",
    dependencies: [304],
    operatingModeNote: "shadow",
    productionClaimAllowed: false,
  },
  {
    number: 295,
    title: "Billing and Invoicing Centre",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["finance.billing_invoice"],
    action: "retain_as_reference",
    reason: "BillingInvoice canonical; legacy Invoice retire_after_migration.",
    dependencies: [],
    operatingModeNote: "internal_alpha",
    productionClaimAllowed: false,
  },
  {
    number: 297,
    title: "Transport MVP shell (Prompt 0–1)",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["transport.trip"],
    action: "retain_as_reference",
    reason: "Consolidate writers onto TransportTrip; Booking retire_after_migration.",
    dependencies: [],
    operatingModeNote: "scaffold → synthetic",
    productionClaimAllowed: false,
  },
  {
    number: 274,
    title: "Indoor Accessibility",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["places.floor_plan"],
    action: "retain_as_reference",
    reason: "Indoor on main; authoring canvas still incomplete.",
    dependencies: [],
    operatingModeNote: "controlled_pilot candidate",
    productionClaimAllowed: false,
  },
  {
    number: 324,
    title: "AccessCast synthetic outlook + Starting Work contracts",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["access.cast"],
    action: "retain_as_reference",
    reason:
      "AccessCast synthetic foundation on main; duplicate AccessCast stacks #320–#322/#325 must close.",
    supersedes: [320, 321, 322, 325],
    dependencies: [306],
    operatingModeNote: "synthetic_demo — no production claim",
    productionClaimAllowed: false,
  },
  {
    number: 312,
    title: "Productisation Wave 0 — canonical repo reconciliation",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "retain_as_reference",
    reason: "Merged 2026-07-17 — Wave 0 registries on main.",
    dependencies: [300, 302, 324],
    operatingModeNote: "advisory registries",
    productionClaimAllowed: false,
  },
  {
    number: 313,
    title: "Wave 1 high-risk API and tenant hardening",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["security.encryption", "platform.tenancy"],
    action: "retain_as_reference",
    reason: "Merged 2026-07-17 — encryption/tenant hardening on main.",
    dependencies: [312],
    operatingModeNote: "security — flags default off",
    productionClaimAllowed: false,
  },
  {
    number: 314,
    title: "Communication Passport → readiness vertical slice",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["communication.passport", "workforce.readiness"],
    action: "retain_as_reference",
    reason: "Merged 2026-07-17 — passport readiness on main; no auto-assign.",
    dependencies: [313],
    operatingModeNote: "internal_alpha slice",
    productionClaimAllowed: false,
  },
  {
    number: 315,
    title: "Native Expo Companion foundation and Visit Pack",
    state: "CLOSED",
    isDraft: true,
    baseBranch: "main",
    schemaImpact: "low",
    canonicalDomains: ["mobile.companion"],
    action: "retain_as_reference",
    reason: "Closed as stack tip; Companion foundation landed via #327.",
    dependencies: [314, 327],
    operatingModeNote: "foundation on main via #327",
    productionClaimAllowed: false,
  },
  {
    number: 316,
    title: "Provider Ops read-only daily attention queue",
    state: "CLOSED",
    isDraft: true,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["provider.ops_attention"],
    action: "retain_as_reference",
    reason: "Closed as stack tip; Provider Ops foundation landed via #327.",
    dependencies: [327],
    operatingModeNote: "scaffold on main via #327 — read only",
    productionClaimAllowed: false,
  },
  {
    number: 317,
    title: "Starting Work golden journey and operating loop status",
    state: "CLOSED",
    isDraft: true,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["journeys.starting_work"],
    action: "retain_as_reference",
    reason: "Closed as stack tip; synthetic Starting Work landed via #327; durable projection is #330.",
    dependencies: [327],
    operatingModeNote: "synthetic on main; DB projection queued as #330",
    productionClaimAllowed: false,
  },
  {
    number: 327,
    title: "Care/Transport/Billing slices, Companion, Provider Ops, Starting Work",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: [
      "care.agreements",
      "transport.quotes",
      "billing.service_record",
      "mobile.companion",
      "provider.ops_attention",
      "journeys.starting_work",
    ],
    action: "retain_as_reference",
    reason:
      "Merged 2026-07-17 (fb80bc83). Process-local transport quotes; synthetic Starting Work; Companion + Provider Ops foundations.",
    supersedes: [315, 316, 317],
    dependencies: [312, 313, 314, 324],
    operatingModeNote: "internal_alpha — flags default off",
    productionClaimAllowed: false,
  },
  {
    number: 331,
    title: "Strategy — capabilities, documentation and operating lanes",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "merge",
    reason: "Leadership train slot 1 — docs/strategy + capability honesty; no product migration.",
    dependencies: [327],
    operatingModeNote: "documentation / claim discipline",
    productionClaimAllowed: false,
    stackDepth: 1,
  },
  {
    number: 328,
    title: "Trust Fabric — Participant Access Receipts and Trust History",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["trust.fabric", "rights.access_receipts"],
    action: "merge",
    reason:
      "Leadership train slot 2 — rebase after #331; keeps MIG 20260717120000; RightsOS #280 extract-only.",
    dependencies: [331],
    operatingModeNote: "internal_alpha — flags default off",
    productionClaimAllowed: false,
    stackDepth: 1,
  },
  {
    number: 329,
    title: "Persistent Access Evidence Envelope and Human Change Review",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["access.intelligence_next", "access.evidence"],
    action: "merge",
    reason:
      "Leadership train slot 3 — rebase after #331; keeps MIG 20260717130000; do not merge #308 wholesale.",
    dependencies: [331],
    operatingModeNote: "synthetic → internal_alpha",
    productionClaimAllowed: false,
    stackDepth: 1,
  },
  {
    number: 330,
    title: "Database-Backed Starting Work Golden Journey",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["journeys.starting_work"],
    action: "rebase",
    reason:
      "Queued after #328/#329 capacity frees; MIG 20260717140000; temporary projection only — no CareOSMission.",
    dependencies: [328, 329, 327],
    operatingModeNote: "controlled_pilot projection — flags default off",
    productionClaimAllowed: false,
  },
  {
    number: 332,
    title: "Persistent TransportQuote (colliding migration tip)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/strategic-opportunity-reconciliation-e909",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["transport.quotes"],
    action: "close",
    reason:
      "Migration timestamp 20260717120000 collides with Trust Fabric #328; close and recreate after #330 with 20260717150000.",
    supersededBy: undefined,
    dependencies: [331],
    operatingModeNote: "blocked — recreate required",
    productionClaimAllowed: false,
    stackDepth: 2,
  },
  {
    number: 333,
    title: "Recurring Care schedules (colliding migration tip)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/persistent-transport-quotes-e909",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["care.recurring"],
    action: "close",
    reason:
      "Migration timestamp 20260717130000 collides with Access Evidence #329; close and recreate after Transport quotes.",
    dependencies: [332],
    operatingModeNote: "blocked — recreate required",
    productionClaimAllowed: false,
    stackDepth: 3,
  },
  {
    number: 334,
    title: "Starting Work DB duplicate Opportunity-train tip",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/recurring-care-agreements-e909",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["journeys.starting_work"],
    action: "close",
    reason: "Duplicates open Moat #330; do not open starting-work-db-journey-e909.",
    supersededBy: 330,
    dependencies: [333],
    operatingModeNote: "superseded by #330",
    productionClaimAllowed: false,
    stackDepth: 4,
  },
  {
    number: 335,
    title: "Worker cancel recovery (premature Opportunity tip)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/starting-work-db-journey-e909",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["continuity.recovery"],
    action: "close",
    reason:
      "Exceeds max stack depth; Continuity recovery waits until Care/Transport completion; extract from #301 later only.",
    dependencies: [334],
    operatingModeNote: "deferred Prompt 3",
    productionClaimAllowed: false,
    stackDepth: 5,
  },
  {
    number: 319,
    title: "Replay Lab Mission Simulator kernel",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "none",
    canonicalDomains: ["assurance.replay_lab"],
    action: "defer",
    reason:
      "Behind main by multiple commits; rebase/recreate after Trust/Evidence/Starting Work/Transport/Care land (Prompt 13).",
    dependencies: [330],
    operatingModeNote: "synthetic assurance gate — not production safety proof",
    productionClaimAllowed: false,
  },
  {
    number: 323,
    title: "Release candidate 1 consolidation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["release.rc1"],
    action: "split",
    reason:
      "Never merge giant RC branch (~100k+ LOC). Cherry-pick inventories only; domain-owned PRs required.",
    dependencies: [],
    operatingModeNote: "non-mergeable mega-branch",
    productionClaimAllowed: false,
  },
  {
    number: 320,
    title: "AccessCast shared contracts (duplicate stack)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "none",
    canonicalDomains: ["access.cast"],
    action: "close",
    reason: "Superseded by merged #324 AccessCast on main.",
    supersededBy: 324,
    dependencies: [],
    operatingModeNote: "retired duplicate",
    productionClaimAllowed: false,
  },
  {
    number: 321,
    title: "AccessCast Starting Work journey (duplicate stack)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/accesscast-synthetic-outlook-1c07",
    mergeable: "MERGEABLE",
    schemaImpact: "none",
    canonicalDomains: ["access.cast"],
    action: "close",
    reason: "Superseded by merged #324.",
    supersededBy: 324,
    dependencies: [320],
    operatingModeNote: "retired duplicate",
    productionClaimAllowed: false,
    stackDepth: 2,
  },
  {
    number: 322,
    title: "AccessCast Companion offline Visit Pack (duplicate)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/accesscast-starting-work-journey-1c07",
    mergeable: "MERGEABLE",
    schemaImpact: "none",
    canonicalDomains: ["access.cast", "mobile.companion"],
    action: "close",
    reason: "Superseded by merged #324/#326 AccessCast path.",
    supersededBy: 324,
    dependencies: [321],
    operatingModeNote: "retired duplicate",
    productionClaimAllowed: false,
    stackDepth: 3,
  },
  {
    number: 325,
    title: "AccessCast Starting Work timeline (duplicate tip)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/accesscast-synthetic-outlook-57ca",
    mergeable: "MERGEABLE",
    schemaImpact: "none",
    canonicalDomains: ["access.cast"],
    action: "close",
    reason: "Base #324 already merged; tip work should land as follow-up on main if still needed.",
    supersededBy: 324,
    dependencies: [324],
    operatingModeNote: "retired duplicate tip",
    productionClaimAllowed: false,
  },
  {
    number: 289,
    title: "ConvergenceOS read-only Canonical Domain and PR Registry",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "close",
    reason: "Superseded by merged #302.",
    supersededBy: 302,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 290,
    title: "ConvergenceOS Iteration 2 Repository Twin + Constitution",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["convergence.control_plane"],
    action: "close",
    reason: "Superseded by merged #302.",
    supersededBy: 302,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 291,
    title: "VisionAccess shared contracts and synthetic Access Lens",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["access.vision"],
    action: "close",
    reason: "Superseded by #308 VisionAccess bridge into Living Access Fabric.",
    supersededBy: 308,
    dependencies: [],
    operatingModeNote: "retired standalone",
    productionClaimAllowed: false,
  },
  {
    number: 264,
    title: "Legacy Access Intelligence branch",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence"],
    action: "close",
    reason: "Superseded by #273 expansion + AI Next on main.",
    supersededBy: 273,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 287,
    title: "ContinuityOS Life Events registry",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "close",
    reason: "Superseded by #301 Continuity direction; avoid dual Continuity SoT.",
    supersededBy: 301,
    dependencies: [],
    operatingModeNote: "retired predecessor",
    productionClaimAllowed: false,
  },
  {
    number: 288,
    title: "ContinuityOS Life Event Registry foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "close",
    reason: "Superseded by #301 Continuity direction.",
    supersededBy: 301,
    dependencies: [],
    operatingModeNote: "retired predecessor",
    productionClaimAllowed: false,
  },
  {
    number: 202,
    title: "Migrate from NextAuth to Supabase Auth",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["auth.sessions"],
    action: "close",
    reason: "Conflicts with declared NextAuth ownership in DOMAIN_OWNERSHIP.md.",
    dependencies: [],
    operatingModeNote: "retired — wrong auth SoT",
    productionClaimAllowed: false,
  },
  {
    number: 310,
    title: "Connected Capability Programme foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["programmes.connected_capability"],
    action: "rebase",
    reason: "CONFLICTING with main; rebase after #312/#313 — no new participant SoT.",
    dependencies: [312],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 286,
    title: "NDIS Gateway canonical domain and funding facades",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["ndis.gateway", "finance.funding"],
    action: "rebase",
    reason: "Merge after security wave; keep real NDIA submission disabled.",
    dependencies: [313],
    operatingModeNote: "scaffold — adapters off",
    productionClaimAllowed: false,
  },
  {
    number: 273,
    title: "Access Intelligence Production Expansion (Waves 0–5)",
    state: "OPEN",
    isDraft: false,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence", "places.access_place"],
    action: "consolidate",
    reason:
      "Consolidate with AI Next on main; refuse second AccessPlace writer (AiAccessPlace).",
    dependencies: [306, 313],
    operatingModeNote: "shadow / internal_alpha — flags default off",
    productionClaimAllowed: false,
  },
  {
    number: 266,
    title: "Access Intelligence Wave 0–5 production expansion (sibling)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence", "places.access_place"],
    action: "supersede",
    reason: "Sibling of #273; rebuild/consolidate onto AI Next — do not merge both.",
    supersededBy: 273,
    dependencies: [],
    operatingModeNote: "superseded sibling",
    productionClaimAllowed: false,
  },
  {
    number: 308,
    title: "Living Access Fabric Waves 8–11 + VisionAccess bridge",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["access.intelligence_next", "access.vision"],
    action: "rebase",
    reason: "Bridge VisionAccess after consolidate #273; supersedes #291.",
    supersedes: [291],
    dependencies: [273],
    operatingModeNote: "synthetic_demo / shadow",
    productionClaimAllowed: false,
  },
  {
    number: 307,
    title: "Public Accountability Portal foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["accountability.portal"],
    action: "defer",
    reason: "After security + billing honesty; unify with #311 later.",
    dependencies: [313],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 301,
    title: "Continuity life event graph and service recovery",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "defer",
    reason:
      "Mega-branch — extract ContinuityCase recovery slice later only; never merge wholesale; supersedes #287/#288 as references.",
    supersedes: [287, 288],
    dependencies: [330],
    operatingModeNote: "extract-only — Prompt 3 later",
    productionClaimAllowed: false,
  },
  {
    number: 309,
    title: "AccessOps civic digital twin",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["access.ops", "places.civic_asset"],
    action: "defer",
    reason:
      "Mega-branch — extract Harbour venue AccessOps pilot later; never merge wholesale.",
    dependencies: [329],
    operatingModeNote: "extract-only — venue pilot later",
    productionClaimAllowed: false,
  },
  {
    number: 311,
    title: "Public algorithm register appeals and oversight",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["accountability.governance"],
    action: "defer",
    reason: "After #307; unify appeals path.",
    dependencies: [307],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 296,
    title: "Multi-organisation production scaling",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["platform.tenancy"],
    action: "split",
    reason: "Do not merge mega-stack #296→#298→#299 unchanged.",
    dependencies: [],
    operatingModeNote: "concept",
    productionClaimAllowed: false,
  },
  {
    number: 298,
    title: "Credentials and consent federation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["consent", "identity.credentials"],
    action: "split",
    reason: "Split from mega-stack; extend consent on main — no new person SoT.",
    dependencies: [296],
    operatingModeNote: "concept",
    productionClaimAllowed: false,
  },
  {
    number: 299,
    title: "AURA participant-controlled agent layer",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["aura.proposal"],
    action: "defer",
    reason: "Land only after security + consent; L≤3 propose; no authority writes.",
    dependencies: [298, 313],
    operatingModeNote: "concept — ceiling L3_PROPOSE",
    productionClaimAllowed: false,
  },
  {
    number: 283,
    title: "Transport MVP adapted to Next.js/Prisma",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["transport.trip"],
    action: "retire_after_migration",
    reason: "Conflicts with TransportTrip canonical on main (#297 path).",
    dependencies: [297],
    operatingModeNote: "retire writers after Trip migration",
    productionClaimAllowed: false,
  },
  {
    number: 231,
    title: "CareOS agentic network and Intelligence Fabric",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["care.careos_parallel"],
    action: "archive",
    reason:
      "Parallel platform risk — defer/archive; extract adapters only after ADR. Case/Care on main remain writers.",
    dependencies: [],
    operatingModeNote: "archived parallel stack root",
    productionClaimAllowed: false,
  },
  {
    number: 252,
    title: "CareOS platform completion — mission SoR",
    state: "OPEN",
    isDraft: true,
    baseBranch: "agent/careos-national-platform",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["care.careos_parallel"],
    action: "defer",
    reason: "Second CareOSMission writer — blocked without architecture decision.",
    dependencies: [231],
    operatingModeNote: "deferred — kill criterion if merged as SoT",
    productionClaimAllowed: false,
    stackDepth: 3,
  },
];

export function ledgerEntriesByAction(action: PrLedgerAction): PrActionLedgerEntry[] {
  return PR_ACTION_LEDGER.filter((e) => e.action === action);
}

export function assertSupersededCloseTargetsInLedger(): void {
  for (const n of SUPERSEDED_CLOSE_TARGETS) {
    const entry = PR_ACTION_LEDGER.find((e) => e.number === n);
    if (!entry || entry.action !== "close") {
      throw new Error(
        `Superseded PR #${n} must appear in PR_ACTION_LEDGER with action=close`,
      );
    }
  }
}

/** Entries with stackDepth > MAX_UNMERGED_STACK_DEPTH must not use action=merge. */
export function assertStackDepthPolicy(): void {
  for (const entry of PR_ACTION_LEDGER) {
    if (
      entry.stackDepth !== undefined &&
      entry.stackDepth > MAX_UNMERGED_STACK_DEPTH &&
      entry.action === "merge"
    ) {
      throw new Error(
        `PR #${entry.number} stackDepth=${entry.stackDepth} exceeds ${MAX_UNMERGED_STACK_DEPTH} and must not merge as-is`,
      );
    }
  }
}

export function assertProductisationTrainDepth(): void {
  if (PRODUCTISATION_TRAIN_HEADS.length > MAX_UNMERGED_STACK_DEPTH) {
    throw new Error(
      `Productisation train heads exceed max depth ${MAX_UNMERGED_STACK_DEPTH}`,
    );
  }
}
