/**
 * Productisation Wave 0 — PR action ledger.
 * Actions: merge | rebase | split | consolidate | supersede | close | retain_as_reference | retire_after_migration
 * Verified against live GitHub state at ledger refresh; descriptions are not evidence of main source.
 */

export type PrLedgerAction =
  | "merge"
  | "rebase"
  | "split"
  | "consolidate"
  | "supersede"
  | "close"
  | "retain_as_reference"
  | "retire_after_migration";

export type PrActionLedgerEntry = {
  number: number;
  title: string;
  state: "OPEN" | "MERGED" | "CLOSED";
  isDraft: boolean;
  baseBranch: string;
  mergeable?: string;
  schemaImpact: "none" | "low" | "medium" | "high";
  canonicalDomains: string[];
  action: PrLedgerAction;
  reason: string;
  supersedes?: number[];
  supersededBy?: number;
  dependencies: number[];
  operatingModeNote: string;
  productionClaimAllowed: boolean;
};

/** Superseded PRs that must be closed (or labelled supersede) before merge-train progress. */
export const SUPERSEDED_CLOSE_TARGETS: number[] = [289, 290, 291, 264, 287, 288];

export const PR_ACTION_LEDGER: PrActionLedgerEntry[] = [
  {
    number: 300,
    title: "Repository controls and CI gates",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "retain_as_reference",
    reason: "Remediation CI landed on main; reference for gate expansion.",
    dependencies: [],
    operatingModeNote: "limited_release CI",
    productionClaimAllowed: false,
  },
  {
    number: 302,
    title: "ConvergenceOS Repository Twin and Architecture Constitution",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["convergence.control_plane"],
    action: "retain_as_reference",
    reason: "Constitution + twin on main; extend registries in productisation Wave 0.",
    dependencies: [300],
    operatingModeNote: "internal_alpha audit",
    productionClaimAllowed: false,
  },
  {
    number: 303,
    title: "Access Intelligence Next ontology foundation",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["places.access_place", "access.intelligence_next"],
    action: "retain_as_reference",
    reason: "AI Next foundation on main; do not fork legacy AI.",
    dependencies: [],
    operatingModeNote: "synthetic_demo → shadow",
    productionClaimAllowed: false,
  },
  {
    number: 304,
    title: "Access Intelligence Next temporal evidence",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence_next"],
    action: "retain_as_reference",
    reason: "Temporal evidence on main.",
    dependencies: [303],
    operatingModeNote: "shadow",
    productionClaimAllowed: false,
  },
  {
    number: 306,
    title: "Access Intelligence Next door-to-room preflight",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence_next", "places.floor_plan"],
    action: "retain_as_reference",
    reason: "Preflight on main; unknown must remain unknown.",
    dependencies: [304],
    operatingModeNote: "shadow",
    productionClaimAllowed: false,
  },
  {
    number: 295,
    title: "Billing and Invoicing Centre",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["finance.billing_invoice"],
    action: "retain_as_reference",
    reason: "BillingInvoice canonical; legacy Invoice retire_after_migration.",
    dependencies: [],
    operatingModeNote: "internal_alpha",
    productionClaimAllowed: false,
  },
  {
    number: 297,
    title: "Transport MVP shell",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "medium",
    canonicalDomains: ["transport.trip"],
    action: "retain_as_reference",
    reason: "Consolidate writers onto TransportTrip; Booking retire_after_migration.",
    dependencies: [],
    operatingModeNote: "scaffold → synthetic",
    productionClaimAllowed: false,
  },
  {
    number: 274,
    title: "Indoor Accessibility",
    state: "MERGED",
    isDraft: false,
    baseBranch: "main",
    schemaImpact: "high",
    canonicalDomains: ["places.floor_plan"],
    action: "retain_as_reference",
    reason: "Indoor on main; authoring canvas still incomplete.",
    dependencies: [],
    operatingModeNote: "controlled_pilot candidate",
    productionClaimAllowed: false,
  },
  {
    number: 289,
    title: "ConvergenceOS read-only Canonical Domain and PR Registry",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "none",
    canonicalDomains: ["convergence.control_plane"],
    action: "close",
    reason: "Superseded by merged #302.",
    supersededBy: 302,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 290,
    title: "ConvergenceOS Iteration 2 Repository Twin + Constitution",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["convergence.control_plane"],
    action: "close",
    reason: "Superseded by merged #302.",
    supersededBy: 302,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 291,
    title: "VisionAccess shared contracts and synthetic Access Lens",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["access.vision"],
    action: "close",
    reason: "Superseded by #308 VisionAccess bridge into Living Access Fabric.",
    supersededBy: 308,
    dependencies: [],
    operatingModeNote: "retired standalone",
    productionClaimAllowed: false,
  },
  {
    number: 264,
    title: "Legacy Access Intelligence branch",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence"],
    action: "close",
    reason: "Superseded by #273 expansion + AI Next on main.",
    supersededBy: 273,
    dependencies: [],
    operatingModeNote: "retired",
    productionClaimAllowed: false,
  },
  {
    number: 287,
    title: "ContinuityOS Life Events registry",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "close",
    reason: "Superseded by #301 Continuity direction; avoid dual Continuity SoT.",
    supersededBy: 301,
    dependencies: [],
    operatingModeNote: "retired predecessor",
    productionClaimAllowed: false,
  },
  {
    number: 288,
    title: "ContinuityOS Life Event Registry foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "close",
    reason: "Superseded by #301 Continuity direction.",
    supersededBy: 301,
    dependencies: [],
    operatingModeNote: "retired predecessor",
    productionClaimAllowed: false,
  },
  {
    number: 310,
    title: "Connected Capability Programme foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["programmes.connected_capability"],
    action: "merge",
    reason: "Early Wave 0 train — capability foundation without new participant SoT.",
    dependencies: [302],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 286,
    title: "NDIS Gateway canonical domain and funding facades",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["ndis.gateway", "finance.funding"],
    action: "rebase",
    reason: "Merge after security wave; keep real NDIA submission disabled.",
    dependencies: [],
    operatingModeNote: "scaffold — adapters off",
    productionClaimAllowed: false,
  },
  {
    number: 273,
    title: "Access Intelligence Production Expansion (Waves 0–5)",
    state: "OPEN",
    isDraft: false,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "high",
    canonicalDomains: ["access.intelligence", "places.access_place"],
    action: "merge",
    reason: "Merge after reconciliation; then consolidate with AI Next namespaces.",
    dependencies: [306],
    operatingModeNote: "shadow / internal_alpha — flags default off",
    productionClaimAllowed: false,
  },
  {
    number: 308,
    title: "Living Access Fabric Waves 8–11 + VisionAccess bridge",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["access.intelligence_next", "access.vision"],
    action: "merge",
    reason: "Bridge VisionAccess; supersedes #291.",
    supersedes: [291],
    dependencies: [273],
    operatingModeNote: "synthetic_demo / shadow",
    productionClaimAllowed: false,
  },
  {
    number: 307,
    title: "Public Accountability Portal foundation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "MERGEABLE",
    schemaImpact: "medium",
    canonicalDomains: ["accountability.portal"],
    action: "rebase",
    reason: "Wave 18 prep; unify with #311 later.",
    dependencies: [],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 301,
    title: "Continuity life event graph and service recovery",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["continuity.os"],
    action: "consolidate",
    reason: "Single ContinuityOS; supersedes #287/#288; no dual mission DDL.",
    supersedes: [287, 288],
    dependencies: [],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 309,
    title: "AccessOps civic digital twin",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["access.ops", "places.civic_asset"],
    action: "consolidate",
    reason: "One AccessOps adapter layer; supersede parallel CivicAsset SoT concepts.",
    dependencies: [308],
    operatingModeNote: "concept → scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 311,
    title: "Public algorithm register appeals and oversight",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "medium",
    canonicalDomains: ["accountability.governance"],
    action: "rebase",
    reason: "After #307; unify appeals path.",
    dependencies: [307],
    operatingModeNote: "scaffold",
    productionClaimAllowed: false,
  },
  {
    number: 296,
    title: "Multi-organisation production scaling",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["platform.tenancy"],
    action: "split",
    reason: "Do not merge mega-stack #296→#298→#299 unchanged.",
    dependencies: [],
    operatingModeNote: "concept",
    productionClaimAllowed: false,
  },
  {
    number: 298,
    title: "Credentials and consent federation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["consent", "identity.credentials"],
    action: "split",
    reason: "Split from mega-stack; extend consent on main — no new person SoT.",
    dependencies: [296],
    operatingModeNote: "concept",
    productionClaimAllowed: false,
  },
  {
    number: 299,
    title: "AURA participant-controlled agent layer",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["aura.proposal"],
    action: "split",
    reason: "Land only after security + consent; L≤3 propose; no authority writes.",
    dependencies: [298],
    operatingModeNote: "concept — ceiling L3_PROPOSE",
    productionClaimAllowed: false,
  },
  {
    number: 283,
    title: "Transport MVP adapted to Next.js/Prisma",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    mergeable: "CONFLICTING",
    schemaImpact: "high",
    canonicalDomains: ["transport.trip"],
    action: "retire_after_migration",
    reason: "Conflicts with TransportTrip canonical on main (#297 path).",
    dependencies: [297],
    operatingModeNote: "retire writers after Trip migration",
    productionClaimAllowed: false,
  },
];

export function ledgerEntriesByAction(action: PrLedgerAction): PrActionLedgerEntry[] {
  return PR_ACTION_LEDGER.filter((e) => e.action === action);
}

export function assertSupersededCloseTargetsInLedger(): void {
  for (const n of SUPERSEDED_CLOSE_TARGETS) {
    const entry = PR_ACTION_LEDGER.find((e) => e.number === n);
    if (!entry || entry.action !== "close") {
      throw new Error(
        `Superseded PR #${n} must appear in PR_ACTION_LEDGER with action=close`,
      );
    }
  }
}
