/**
 * Keys that must never appear in external ad context.
 * Used by sanitiser tests and runtime stripping.
 */
export const SENSITIVE_AD_CONTEXT_KEYS = [
  "diagnosis",
  "disability",
  "disabilityType",
  "disabilityProfile",
  "participantStatus",
  "ndisNumber",
  "ndisParticipantStatus",
  "ndisStatus",
  "planBalance",
  "fundingAmount",
  "fundingCategory",
  "medicalNotes",
  "medicalConditions",
  "medication",
  "clinicalNotes",
  "incidentData",
  "behaviourSupport",
  "restrictivePractice",
  "aacPreference",
  "aacRequirement",
  "supportWorkerNotes",
  "personalCare",
  "supportIntensity",
  "mobilityDevice",
  "employmentDisclosure",
  "delegate",
  "homeAddress",
  "exactHomeLocation",
  "email",
  "phone",
  "userId",
  "participantId",
  "providerUserId",
  "accountId",
  "accountIdentifier",
  "preciseLocation",
  "historicalLocation",
  "gps",
  "viewportBBox",
  "mapCenter",
  "searchQuery",
  "searchContext",
] as const;

export type SensitiveAdContextKey = (typeof SENSITIVE_AD_CONTEXT_KEYS)[number];

export const ALLOWED_EXTERNAL_CATEGORY_TAXONOMY = [
  "hospitality",
  "tourism",
  "retail",
  "allied_services",
  "community",
  "employment",
  "education",
  "transport",
  "general",
] as const;

export const ALLOWED_EXTERNAL_REGION_CODES = [
  "sydney",
  "melbourne",
  "brisbane",
  "perth",
  "adelaide",
  "hobart",
  "darwin",
  "canberra",
  "nsw",
  "vic",
  "qld",
  "wa",
  "sa",
  "tas",
  "nt",
  "act",
  "national",
] as const;
