/**
 * Harbour Civic Centre — Living Building (clearly fictional demonstration).
 * Shared by Visit / Learn / Operate / Improve. Same graph powers deterministic engines.
 */
import type {
  AccessFeature,
  BuildingElement,
  Evidence,
  LiveIncident,
  Place,
  RouteEdge,
  RouteNode,
} from "../schemas";
import type { AccessGraph } from "../types";

import type { LivingAccessTwin, TemporalRule, VenueMutation } from "./schemas";

const RECENT = "2026-06-27T10:00:00.000Z";
const EIGHTEEN_DAYS_AGO = "2026-06-27T10:00:00.000Z"; // relative to demo “today” Jul 15 → ~18 days
const SIX_MONTHS_AGO = "2025-12-15T10:00:00.000Z";
const COMMUNITY_RECENT = "2026-07-10T09:00:00.000Z";

export const HARBOUR_PLACE_ID = "place-harbour-civic";

const PLACE: Place = {
  id: HARBOUR_PLACE_ID,
  name: "Harbour Civic Centre",
  address: "100 Synthetic Quay, Demo Harbour NSW 2000",
  category: "civic",
  coordinates: { lat: -33.86, lng: 151.21 },
  operator: "Demo Harbour Council",
  openingHours: "Mon–Fri 8:00–17:00; Entrance B until 18:00 unless special access arranged",
  baselineScore: 72,
  accreditationTier: "synthetic-demo",
  lastVerifiedAt: RECENT,
};

const elements: BuildingElement[] = [
  { id: "hcc-dropoff", placeId: HARBOUR_PLACE_ID, type: "drop_off", name: "Accessible vehicle drop-off", level: "G" },
  { id: "hcc-parking", placeId: HARBOUR_PLACE_ID, type: "parking", name: "Accessible parking", level: "G" },
  { id: "hcc-path-exposed", placeId: HARBOUR_PLACE_ID, type: "path", name: "Exposed shorter external path", level: "G" },
  { id: "hcc-path-shelter", placeId: HARBOUR_PLACE_ID, type: "path", name: "Sheltered longer external path", level: "G" },
  { id: "hcc-ent-a", placeId: HARBOUR_PLACE_ID, type: "entrance", name: "Entrance A (steps)", level: "G" },
  { id: "hcc-ent-b", placeId: HARBOUR_PLACE_ID, type: "entrance", name: "Entrance B (level)", level: "G" },
  { id: "hcc-reception", placeId: HARBOUR_PLACE_ID, type: "reception", name: "Reception", level: "G" },
  { id: "hcc-quiet-g", placeId: HARBOUR_PLACE_ID, type: "quiet_space", name: "Quiet waiting room", level: "G" },
  { id: "hcc-lift", placeId: HARBOUR_PLACE_ID, type: "lift", name: "Main lift", level: "G-3" },
  { id: "hcc-lift-west", placeId: HARBOUR_PLACE_ID, type: "lift", name: "Western lift", level: "G-3" },
  { id: "hcc-corr-3", placeId: HARBOUR_PLACE_ID, type: "corridor", name: "Level 3 main corridor (1350 mm)", level: "3" },
  { id: "hcc-corr-west", placeId: HARBOUR_PLACE_ID, type: "corridor", name: "Level 3 western corridor (1250 mm)", level: "3" },
  { id: "hcc-room", placeId: HARBOUR_PLACE_ID, type: "room", name: "Interview Room 3.12", level: "3" },
  { id: "hcc-toilet-2", placeId: HARBOUR_PLACE_ID, type: "toilet", name: "Accessible toilet", level: "2" },
  { id: "hcc-display", placeId: HARBOUR_PLACE_ID, type: "corridor", name: "Temporary corridor display", level: "3" },
];

const evidence: Evidence[] = [
  {
    id: "ev-hcc-ent-a-steps",
    type: "measurement",
    title: "Entrance A — three steps, no ramp",
    description: "Assessor-verified stepped public entrance.",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 3, unit: "steps" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-ent-b-level",
    type: "measurement",
    title: "Entrance B — level entry",
    capturedAt: EIGHTEEN_DAYS_AGO,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: true },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-ent-b-width",
    type: "measurement",
    title: "Entrance B clear opening 910 mm",
    capturedAt: EIGHTEEN_DAYS_AGO,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 910, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-lift-door",
    type: "measurement",
    title: "Main lift door width 900 mm",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 900, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-west-lift",
    type: "measurement",
    title: "Western lift door width 900 mm",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 900, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-corridor",
    type: "measurement",
    title: "Level 3 main corridor 1350 mm",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 1350, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-corr-west",
    type: "measurement",
    title: "Western corridor 1250 mm",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 1250, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-room-door",
    type: "measurement",
    title: "Room 3.12 clear door opening 880 mm",
    capturedAt: RECENT,
    sourceName: "Synthetic assessor",
    sourceType: "qualified_assessor",
    measurement: { value: 880, unit: "mm" },
    calibrationConfirmed: true,
    status: "verified",
  },
  {
    id: "ev-hcc-toilet-stale",
    type: "photograph",
    title: "Accessible toilet on level 2 (six months old)",
    description: "Presence verified; operational status not confirmed recently.",
    capturedAt: SIX_MONTHS_AGO,
    sourceName: "Trained mapper",
    sourceType: "trained_mapper",
    status: "provisional",
  },
  {
    id: "ev-hcc-venue-hours",
    type: "venue_statement",
    title: "Entrance B closes at 18:00 unless special access arranged",
    capturedAt: RECENT,
    sourceName: "Demo Harbour Council attestation",
    sourceType: "venue_attestation",
    status: "provisional",
  },
  {
    id: "ev-hcc-community-queue",
    type: "community_observation",
    title: "Reception desk queue sometimes long (community)",
    capturedAt: COMMUNITY_RECENT,
    sourceName: "Community reporter (demo)",
    sourceType: "community_report",
    status: "provisional",
  },
  {
    id: "ev-hcc-disputed-loop",
    type: "document",
    title: "Hearing loop presence — disputed claim",
    capturedAt: RECENT,
    sourceName: "Conflicting reports",
    sourceType: "community_report",
    status: "disputed",
  },
];

const features: AccessFeature[] = [
  {
    id: "f-hcc-a-steps",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-ent-a",
    featureType: "step_free",
    value: false,
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-ent-a-steps"],
    confidence: 1,
    disputed: false,
    notes: "Entrance A has three steps and no ramp.",
  },
  {
    id: "f-hcc-b-level",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-ent-b",
    featureType: "step_free",
    value: true,
    sourceType: "qualified_assessor",
    observedAt: EIGHTEEN_DAYS_AGO,
    evidenceIds: ["ev-hcc-ent-b-level"],
    confidence: 1,
    disputed: false,
  },
  {
    id: "f-hcc-b-width",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-ent-b",
    featureType: "clear_door_width_mm",
    value: 910,
    unit: "mm",
    sourceType: "qualified_assessor",
    observedAt: EIGHTEEN_DAYS_AGO,
    evidenceIds: ["ev-hcc-ent-b-width"],
    confidence: 1,
    disputed: false,
  },
  {
    id: "f-hcc-lift",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-lift",
    featureType: "lift",
    value: true,
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-lift-door"],
    confidence: 0.95,
    disputed: false,
  },
  {
    id: "f-hcc-lift-door",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-lift",
    featureType: "lift_door_width_mm",
    value: 900,
    unit: "mm",
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-lift-door"],
    confidence: 1,
    disputed: false,
  },
  {
    id: "f-hcc-west-lift",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-lift-west",
    featureType: "lift",
    value: true,
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-west-lift"],
    confidence: 0.95,
    disputed: false,
  },
  {
    id: "f-hcc-corridor",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-corr-3",
    featureType: "corridor_width_mm",
    value: 1350,
    unit: "mm",
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-corridor"],
    confidence: 1,
    disputed: false,
  },
  {
    id: "f-hcc-room-door",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-room",
    featureType: "clear_door_width_mm",
    value: 880,
    unit: "mm",
    sourceType: "qualified_assessor",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-room-door"],
    confidence: 1,
    disputed: false,
    notes: "Internal doorway to Room 3.12.",
  },
  {
    id: "f-hcc-toilet",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-toilet-2",
    featureType: "accessible_toilet",
    value: "unknown_operational",
    sourceType: "trained_mapper",
    observedAt: SIX_MONTHS_AGO,
    evidenceIds: ["ev-hcc-toilet-stale"],
    confidence: 0.45,
    disputed: false,
    notes: "Toilet presence photographed six months ago; operational status unknown.",
  },
  {
    id: "f-hcc-quiet",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-quiet-g",
    featureType: "quiet_waiting_area",
    value: true,
    sourceType: "venue_attestation",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-venue-hours"],
    confidence: 0.75,
    disputed: false,
  },
  {
    id: "f-hcc-staff",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-reception",
    featureType: "staff_assistance",
    value: "unknown",
    sourceType: "community_report",
    observedAt: COMMUNITY_RECENT,
    evidenceIds: ["ev-hcc-community-queue"],
    confidence: 0.4,
    disputed: false,
    notes: "Reception assistance is not guaranteed unless confirmed.",
  },
  {
    id: "f-hcc-hearing-disputed",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-reception",
    featureType: "hearing_augmentation",
    value: true,
    sourceType: "community_report",
    observedAt: RECENT,
    evidenceIds: ["ev-hcc-disputed-loop"],
    confidence: 0.3,
    disputed: true,
    notes: "Hearing loop claim is disputed.",
  },
];

const nodes: RouteNode[] = [
  { id: "n-hcc-drop", placeId: HARBOUR_PLACE_ID, elementId: "hcc-dropoff", label: "Accessible drop-off", level: "G", nodeType: "drop_off", coordinates: { x: -20, y: 0 } },
  { id: "n-hcc-a", placeId: HARBOUR_PLACE_ID, elementId: "hcc-ent-a", label: "Entrance A", level: "G", nodeType: "entrance", coordinates: { x: 0, y: 0 } },
  { id: "n-hcc-b", placeId: HARBOUR_PLACE_ID, elementId: "hcc-ent-b", label: "Entrance B", level: "G", nodeType: "entrance", coordinates: { x: 65, y: 0 } },
  { id: "n-hcc-rec", placeId: HARBOUR_PLACE_ID, elementId: "hcc-reception", label: "Reception", level: "G", nodeType: "reception", coordinates: { x: 40, y: 10 } },
  { id: "n-hcc-quiet", placeId: HARBOUR_PLACE_ID, elementId: "hcc-quiet-g", label: "Quiet waiting room", level: "G", nodeType: "quiet_space", coordinates: { x: 45, y: 15 } },
  { id: "n-hcc-lift-g", placeId: HARBOUR_PLACE_ID, elementId: "hcc-lift", label: "Main lift (ground)", level: "G", nodeType: "lift", coordinates: { x: 40, y: 25 } },
  { id: "n-hcc-lift-3", placeId: HARBOUR_PLACE_ID, elementId: "hcc-lift", label: "Main lift (level 3)", level: "3", nodeType: "lift", coordinates: { x: 40, y: 25 } },
  { id: "n-hcc-west-g", placeId: HARBOUR_PLACE_ID, elementId: "hcc-lift-west", label: "Western lift (ground)", level: "G", nodeType: "lift", coordinates: { x: 10, y: 25 } },
  { id: "n-hcc-west-3", placeId: HARBOUR_PLACE_ID, elementId: "hcc-lift-west", label: "Western lift (level 3)", level: "3", nodeType: "lift", coordinates: { x: 10, y: 25 } },
  { id: "n-hcc-corr", placeId: HARBOUR_PLACE_ID, elementId: "hcc-corr-3", label: "Level 3 main corridor", level: "3", nodeType: "corridor", coordinates: { x: 55, y: 25 } },
  { id: "n-hcc-corr-west", placeId: HARBOUR_PLACE_ID, elementId: "hcc-corr-west", label: "Level 3 western corridor", level: "3", nodeType: "corridor", coordinates: { x: 25, y: 25 } },
  { id: "n-hcc-room", placeId: HARBOUR_PLACE_ID, elementId: "hcc-room", label: "Interview Room 3.12", level: "3", nodeType: "room", coordinates: { x: 70, y: 25 } },
  { id: "n-hcc-toilet", placeId: HARBOUR_PLACE_ID, elementId: "hcc-toilet-2", label: "Accessible toilet (level 2)", level: "2", nodeType: "toilet", coordinates: { x: 40, y: 40 } },
];

const edges: RouteEdge[] = [
  {
    id: "e-hcc-drop-a",
    fromNodeId: "n-hcc-drop",
    toNodeId: "n-hcc-a",
    distanceMetres: 25,
    widthMm: 1200,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.85,
    surface: "exposed",
  },
  {
    id: "e-hcc-drop-b",
    fromNodeId: "n-hcc-drop",
    toNodeId: "n-hcc-b",
    distanceMetres: 65,
    widthMm: 1200,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.9,
    surface: "sheltered",
  },
  {
    id: "e-hcc-a-rec",
    fromNodeId: "n-hcc-a",
    toNodeId: "n-hcc-rec",
    distanceMetres: 25,
    widthMm: 1000,
    steps: 3,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-b-rec",
    fromNodeId: "n-hcc-b",
    toNodeId: "n-hcc-rec",
    distanceMetres: 20,
    widthMm: 910,
    steps: 0,
    automaticDoor: true,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-rec-quiet",
    fromNodeId: "n-hcc-rec",
    toNodeId: "n-hcc-quiet",
    distanceMetres: 12,
    widthMm: 1200,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.8,
  },
  {
    id: "e-hcc-rec-lift",
    fromNodeId: "n-hcc-rec",
    toNodeId: "n-hcc-lift-g",
    distanceMetres: 15,
    widthMm: 1200,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.9,
  },
  {
    id: "e-hcc-rec-west",
    fromNodeId: "n-hcc-rec",
    toNodeId: "n-hcc-west-g",
    distanceMetres: 40,
    widthMm: 1200,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.9,
  },
  {
    id: "e-hcc-lift",
    fromNodeId: "n-hcc-lift-g",
    toNodeId: "n-hcc-lift-3",
    distanceMetres: 5,
    widthMm: 900,
    steps: 0,
    liftAvailable: true,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-west-lift",
    fromNodeId: "n-hcc-west-g",
    toNodeId: "n-hcc-west-3",
    distanceMetres: 5,
    widthMm: 900,
    steps: 0,
    liftAvailable: true,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-lift-corr",
    fromNodeId: "n-hcc-lift-3",
    toNodeId: "n-hcc-corr",
    distanceMetres: 18,
    widthMm: 1350,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-west-corr",
    fromNodeId: "n-hcc-west-3",
    toNodeId: "n-hcc-corr-west",
    distanceMetres: 22,
    widthMm: 1250,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.95,
  },
  {
    id: "e-hcc-corr-merge",
    fromNodeId: "n-hcc-corr-west",
    toNodeId: "n-hcc-corr",
    distanceMetres: 28,
    widthMm: 1250,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.9,
  },
  {
    id: "e-hcc-corr-room",
    fromNodeId: "n-hcc-corr",
    toNodeId: "n-hcc-room",
    distanceMetres: 12,
    widthMm: 1000,
    steps: 0,
    temporaryBarrier: false,
    evidenceConfidence: 0.9,
  },
  {
    id: "e-hcc-display-narrow",
    fromNodeId: "n-hcc-corr",
    toNodeId: "n-hcc-room",
    distanceMetres: 14,
    widthMm: 780,
    steps: 0,
    temporaryBarrier: true,
    evidenceConfidence: 0.7,
    surface: "temporary_display",
  },
];

export const HARBOUR_OPERATING_RULES: TemporalRule[] = [
  {
    id: "rule-ent-b-hours",
    placeId: HARBOUR_PLACE_ID,
    elementId: "hcc-ent-b",
    edgeIds: ["e-hcc-b-rec", "e-hcc-drop-b"],
    ruleType: "opening_hours",
    closesAfterHourLocal: 18,
    effect: {
      available: false,
      note: "Entrance B closes at 18:00 local time unless special access is arranged.",
    },
  },
];

export const HARBOUR_BASELINE_INCIDENTS: LiveIncident[] = [];

export const MAIN_LIFT_OUTAGE_INCIDENT: LiveIncident = {
  id: "inc-hcc-main-lift",
  placeId: HARBOUR_PLACE_ID,
  elementId: "hcc-lift",
  type: "lift_outage",
  severity: "high",
  description: "Main lift unavailable (Living Building simulation).",
  sourceType: "system_feed",
  reportedAt: new Date().toISOString(),
  status: "active",
  affectedEdgeIds: ["e-hcc-lift", "e-hcc-lift-corr"],
};

export function buildHarbourAccessGraph(): AccessGraph {
  return {
    place: PLACE,
    elements,
    features,
    evidence,
    nodes,
    edges,
  };
}

export function buildHarbourLivingTwin(
  overrides?: {
    incidents?: LiveIncident[];
    features?: AccessFeature[];
    edges?: RouteEdge[];
    operatingRules?: TemporalRule[];
  },
): LivingAccessTwin {
  const graph = buildHarbourAccessGraph();
  return {
    place: graph.place,
    elements: graph.elements,
    features: overrides?.features ?? graph.features,
    evidence: graph.evidence,
    nodes: graph.nodes,
    edges: overrides?.edges ?? graph.edges,
    incidents: overrides?.incidents ?? HARBOUR_BASELINE_INCIDENTS,
    operatingRules: overrides?.operatingRules ?? HARBOUR_OPERATING_RULES,
    destinations: [
      {
        id: "dest-room-312",
        nodeId: "n-hcc-room",
        label: "Interview Room 3.12",
        level: "3",
      },
      {
        id: "dest-toilet-2",
        nodeId: "n-hcc-toilet",
        label: "Accessible toilet (level 2)",
        level: "2",
      },
    ],
    version: "1.0.0-living",
    updatedAt: new Date().toISOString(),
    fictionalNotice:
      "Harbour Civic Centre is a clearly fictional demonstration building. Measurements do not represent a real venue.",
  };
}

export const HARBOUR_MUTATIONS: VenueMutation[] = [
  {
    id: "mut-ent-b-evening",
    title: "Keep Entrance B open after 18:00",
    description: "Extend level entry hours for evening visits.",
    mutationType: "change_opening_hours",
    targetElementId: "hcc-ent-b",
    targetRuleId: "rule-ent-b-hours",
    after: { closesAfterHourLocal: 22, available: true },
    estimatedEffort: "low",
    estimatedCostBand: "operational",
    evidenceRequiredAfterCompletion: [
      "Updated opening-hours attestation",
      "Security roster confirmation",
    ],
  },
  {
    id: "mut-verify-toilet",
    title: "Verify accessible toilet is operating",
    description: "Confirm level-2 toilet operational status today.",
    mutationType: "verify_unknown",
    targetElementId: "hcc-toilet-2",
    targetFeatureType: "accessible_toilet",
    after: { value: true, confidence: 0.95, notes: "Operating — verified today" },
    estimatedEffort: "very_low",
    estimatedCostBand: "operational",
    evidenceRequiredAfterCompletion: [
      "Venue attestation with timestamp",
      "Optional photograph of in-service signage",
    ],
  },
  {
    id: "mut-repair-main-lift",
    title: "Repair main lift",
    description: "Restore main lift service after outage.",
    mutationType: "repair_element",
    targetElementId: "hcc-lift",
    targetIncidentId: "inc-hcc-main-lift",
    after: { status: "resolved" },
    estimatedEffort: "moderate",
    estimatedCostBand: "minor",
    evidenceRequiredAfterCompletion: [
      "Lift contractor clearance",
      "System feed restoration",
    ],
  },
  {
    id: "mut-remove-display",
    title: "Remove temporary corridor display",
    description: "Clear narrowing obstruction near Room 3.12.",
    mutationType: "remove_obstruction",
    targetEdgeIds: ["e-hcc-display-narrow"],
    after: { temporaryBarrier: false, widthMm: 1200 },
    estimatedEffort: "very_low",
    estimatedCostBand: "operational",
    evidenceRequiredAfterCompletion: ["Floor walk confirmation"],
  },
  {
    id: "mut-quiet-space",
    title: "Guarantee quiet waiting for booked visits",
    description: "Staff commit quiet waiting room for bookable appointments.",
    mutationType: "add_quiet_waiting_space",
    targetElementId: "hcc-quiet-g",
    targetFeatureType: "quiet_waiting_area",
    after: { value: true, confidence: 0.9, sourceType: "venue_attestation" },
    estimatedEffort: "low",
    estimatedCostBand: "operational",
    evidenceRequiredAfterCompletion: ["Booking SOP attestation"],
  },
  {
    id: "mut-staff-assist",
    title: "Guarantee reception assistance for booked visits",
    description: "Confirm staff assistance for interviews.",
    mutationType: "add_staff_availability",
    targetElementId: "hcc-reception",
    targetFeatureType: "staff_assistance",
    after: { value: true, notes: "Booked visit assistance confirmed" },
    estimatedEffort: "low",
    estimatedCostBand: "operational",
    evidenceRequiredAfterCompletion: ["Reception roster note"],
  },
  {
    id: "mut-hearing-loop",
    title: "Resolve hearing loop dispute and publish status",
    description: "Confirm portable hearing loop at reception.",
    mutationType: "resolve_dispute",
    targetFeatureType: "hearing_augmentation",
    after: { disputed: false, value: true, confidence: 0.9 },
    estimatedEffort: "moderate",
    estimatedCostBand: "minor",
    evidenceRequiredAfterCompletion: ["Assessor or calibrated check"],
  },
  {
    id: "mut-tactile",
    title: "Add tactile signage to western lift",
    description: "Improve wayfinding to western vertical circulation.",
    mutationType: "improve_signage",
    targetElementId: "hcc-lift-west",
    targetFeatureType: "tactile_wayfinding",
    after: { value: true },
    estimatedEffort: "moderate",
    estimatedCostBand: "minor",
    evidenceRequiredAfterCompletion: ["Installation photograph", "Mapper verification"],
  },
];
