import type { LocalAccessGuide } from "./types";

export const kuRingGaiPilotGuide: LocalAccessGuide = {
  id: "local-access-guide:nsw:ku-ring-gai:pilot-v1",
  jurisdiction: "NSW",
  region: "Greater Sydney",
  lgaSlug: "ku-ring-gai",
  lgaName: "Ku-ring-gai",
  title: "Ku-ring-gai Local Access Guide",
  description:
    "Pilot projection of MapAble accessibility evidence for public places and local infrastructure in Ku-ring-gai.",
  productionClaim: "pilot",
  generatedAt: "2026-08-19T00:00:00+10:00",
  evidenceNotice:
    "Pilot coverage is incomplete. Unknown means evidence has not yet been verified; it does not mean inaccessible.",
  localities: ["Gordon", "Lindfield", "Pymble", "Roseville", "St Ives", "Turramurra", "West Pymble"],
  assets: [
    {
      id: "krg-gordon-library",
      name: "Gordon Library",
      kind: "library",
      locality: "Gordon",
      latitude: -33.753803,
      longitude: 151.152253,
      evidenceState: "venue_reported",
      sourceLabel: "Ku-ring-gai Council public information",
      summary: "Accessible parking is publicly reported. Detailed path, entrance and amenity evidence remains to be compiled into the canonical evidence model.",
      auditRequired: true,
    },
    {
      id: "krg-lindfield-library",
      name: "Lindfield Library",
      kind: "library",
      locality: "Lindfield",
      latitude: -33.77749,
      longitude: 151.16911,
      evidenceState: "venue_reported",
      sourceLabel: "Ku-ring-gai Council public information",
      summary: "Accessible parking is publicly reported. Detailed journey evidence remains incomplete.",
      auditRequired: true,
    },
    {
      id: "krg-bicentennial-park",
      name: "Bicentennial Park",
      kind: "park",
      locality: "West Pymble",
      latitude: -33.763228,
      longitude: 151.132532,
      evidenceState: "venue_reported",
      sourceLabel: "Ku-ring-gai Council public information",
      summary: "Council describes the facility as accessible and identifies wheelchair-accessible toilets. End-to-end route verification is still required.",
      auditRequired: true,
    },
    {
      id: "krg-st-ives-showground-playground",
      name: "St Ives Showground Regional Playground",
      kind: "playground",
      locality: "St Ives",
      latitude: -33.705302,
      longitude: 151.185476,
      evidenceState: "venue_reported",
      sourceLabel: "Ku-ring-gai Council public information",
      summary: "Council describes an accessible inclusive destination playspace. Detailed feature-level observations remain to be imported.",
      auditRequired: true,
    },
    {
      id: "krg-priority-footpath-gap",
      name: "Priority footpath network",
      kind: "footpath",
      locality: "Ku-ring-gai",
      evidenceState: "unknown",
      sourceLabel: "MapAble pilot audit queue",
      summary: "Asset-level width, gradient, crossfall, obstruction and surface evidence is not yet available in the pilot dataset.",
      auditRequired: true,
      barrierSeverity: null,
    },
    {
      id: "krg-crossing-gap",
      name: "Priority pedestrian crossings",
      kind: "crossing",
      locality: "Ku-ring-gai",
      evidenceState: "unknown",
      sourceLabel: "MapAble pilot audit queue",
      summary: "Crossing alignment, refuge, signal, timing and tactile evidence requires structured audit coverage.",
      auditRequired: true,
      barrierSeverity: null,
    },
    {
      id: "krg-kerb-ramp-gap",
      name: "Priority kerb ramps",
      kind: "kerb_ramp",
      locality: "Ku-ring-gai",
      evidenceState: "unknown",
      sourceLabel: "MapAble pilot audit queue",
      summary: "Gradient, landing, alignment, tactile indicator and drainage evidence requires structured audit coverage.",
      auditRequired: true,
      barrierSeverity: null,
    },
  ],
  metrics: [
    { id: "pilot-assets", label: "Pilot assets / audit groups", value: 7, unit: "count" },
    { id: "reported-assets", label: "Publicly reported evidence", value: 4, denominator: 7, unit: "count" },
    { id: "unknown-gaps", label: "Explicit audit-gap groups", value: 3, unit: "count" },
  ],
};
