export type ConstitutionRuleClass =
  | "constitutional_rule"
  | "architectural_preference"
  | "programme_convention"
  | "temporary_exception"
  | "experimental_rule"
  | "deprecated_rule";

export type ConstitutionRuleSeed = {
  ruleKey: string;
  title: string;
  plainLanguage: string;
  rationale: string;
  severity: string;
  ruleClass: ConstitutionRuleClass;
  detectionMethod: string;
  owner: string;
  approver: string;
  affectedDomains: string[];
  prohibitedPatterns: string[];
  requiredConditions: string[];
};

/**
 * Architecture Constitution C-001 … C-025 (Iteration 2 brief).
 * Wave 9: advisory validation only — no merge blocking.
 */
export const CONSTITUTION_RULES: ConstitutionRuleSeed[] = [
  {
    ruleKey: "C-001",
    title: "One authoritative writer per canonical concept",
    plainLanguage:
      "Each canonical concept has exactly one authoritative writer domain or service.",
    rationale: "Prevents multi-writer collisions such as CareOSMission forks.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "collision_engine_single_writer",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["dual_authoritative_writer"],
    requiredConditions: ["canonical_domain_registered"],
  },
  {
    ruleKey: "C-002",
    title: "Multiple read projections permitted",
    plainLanguage:
      "Read projections, views, and adapters may exist alongside the authoritative writer.",
    rationale: "Enables programme-specific reads without fragmenting write authority.",
    severity: "medium",
    ruleClass: "constitutional_rule",
    detectionMethod: "semantic_projection_class",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: [],
    requiredConditions: ["projection_labelled"],
  },
  {
    ruleKey: "C-003",
    title: "AI may interpret, compare, explain, draft, and propose",
    plainLanguage:
      "AI systems may analyse code and draft proposals but do not execute consequential changes.",
    rationale: "Keeps AI in an advisory role.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "policy_review",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["convergence.control_plane"],
    prohibitedPatterns: ["ai_direct_merge", "ai_direct_migration"],
    requiredConditions: ["human_approval_path"],
  },
  {
    ruleKey: "C-004",
    title: "AI may not grant itself authority",
    plainLanguage:
      "AI cannot approve constitution exceptions, merge PRs, or raise its own authority ceiling.",
    rationale: "Authority remains human-held.",
    severity: "critical",
    ruleClass: "constitutional_rule",
    detectionMethod: "agent_preflight_authority_ceiling",
    owner: "platform_assurance",
    approver: "security",
    affectedDomains: ["convergence.control_plane"],
    prohibitedPatterns: ["ai_self_approval"],
    requiredConditions: ["human_approver_required"],
  },
  {
    ruleKey: "C-005",
    title: "Consequential actions via deterministic application services",
    plainLanguage:
      "Payments, claims, clinical, and safeguarding actions run through deterministic services, not free-form AI tools.",
    rationale: "Auditability and predictable side effects.",
    severity: "critical",
    ruleClass: "constitutional_rule",
    detectionMethod: "agent_preflight_side_effects",
    owner: "platform_assurance",
    approver: "security",
    affectedDomains: ["finance.invoice", "ndis.gateway"],
    prohibitedPatterns: ["ai_tool_direct_write"],
    requiredConditions: ["application_service_path"],
  },
  {
    ruleKey: "C-006",
    title: "Participant approval must be purpose-bound and revocable",
    plainLanguage:
      "Participant approvals state purpose, action, currency, inspectability, and revocation.",
    rationale: "Rights-preserving consent and authority chains.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "authority_lineage_gap",
    owner: "rights_os",
    approver: "privacy",
    affectedDomains: ["participant.consent", "access.passport"],
    prohibitedPatterns: ["open_ended_authority"],
    requiredConditions: ["purpose", "revocation_path"],
  },
  {
    ruleKey: "C-007",
    title: "RightsOS owns purpose and disclosure policy",
    plainLanguage:
      "Purpose definitions and disclosure policy decisions are owned by RightsOS.",
    rationale: "Aligns with Wave 0 canonical domain seeds.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "canonical_domain_owner",
    owner: "rights_os",
    approver: "architecture",
    affectedDomains: ["rights.purpose", "rights.disclosure"],
    prohibitedPatterns: ["parallel_disclosure_policy"],
    requiredConditions: ["rights_os_consulted"],
  },
  {
    ruleKey: "C-008",
    title: "Personal Access Vault owns reusable disclosure views",
    plainLanguage:
      "Reusable participant disclosure views are owned by Personal Access Vault.",
    rationale: "Single vault SoR for selective disclosure.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "canonical_domain_owner",
    owner: "personal_access_vault",
    approver: "architecture",
    affectedDomains: ["vault.disclosure_view"],
    prohibitedPatterns: ["parallel_vault"],
    requiredConditions: ["field_scoped_disclosure"],
  },
  {
    ruleKey: "C-009",
    title: "CareOSMission owns cross-programme mission state",
    plainLanguage:
      "Cross-programme mission state is authored by CareOSMission, not parallel Case systems.",
    rationale: "Resolves Case↔CareOSMission semantic overlap.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "semantic_overlap",
    owner: "care_os",
    approver: "architecture",
    affectedDomains: ["missions.care_os", "missions.case"],
    prohibitedPatterns: ["parallel_mission_sor"],
    requiredConditions: ["single_mission_writer"],
  },
  {
    ruleKey: "C-010",
    title: "AccessPassport owns participant-selected functional requirements",
    plainLanguage:
      "Participant-selected functional access requirements live on AccessPassport.",
    rationale: "Doorway and related requirements stay participant-owned.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "canonical_domain_owner",
    owner: "access_passport",
    approver: "architecture",
    affectedDomains: ["access.passport"],
    prohibitedPatterns: ["shadow_passport"],
    requiredConditions: [],
  },
  {
    ruleKey: "C-011",
    title: "AccessPlace owns public-place identity",
    plainLanguage: "Public place identity is owned by AccessPlace.",
    rationale: "Prevents Venue/Place dual SoRs.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "canonical_domain_owner",
    owner: "places",
    approver: "architecture",
    affectedDomains: ["places.access_place"],
    prohibitedPatterns: ["parallel_place_identity"],
    requiredConditions: [],
  },
  {
    ruleKey: "C-012",
    title: "Living Access Twin owns indoor accessibility projection",
    plainLanguage:
      "Building/indoor accessibility projection extends AccessPlace / AccessFloorPlan — not a second place SoR.",
    rationale: "Indoor twin is a projection, not a competing place identity.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "semantic_projection_class",
    owner: "indoor_accessibility",
    approver: "architecture",
    affectedDomains: ["places.floor_plan", "places.access_place"],
    prohibitedPatterns: ["second_place_sor"],
    requiredConditions: ["extends_access_place"],
  },
  {
    ruleKey: "C-013",
    title: "Programme services own operational writes",
    plainLanguage:
      "Care, Transport, Jobs, and Home programme services own their operational writes.",
    rationale: "Keeps operational authority inside programmes.",
    severity: "medium",
    ruleClass: "constitutional_rule",
    detectionMethod: "ownership_registry",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["care.shift", "transport.trip", "jobs.*", "home.*"],
    prohibitedPatterns: ["cross_programme_silent_write"],
    requiredConditions: ["programme_owner"],
  },
  {
    ruleKey: "C-014",
    title: "AuditEvent and outbox own immutable operational evidence",
    plainLanguage:
      "Immutable operational evidence is written via AuditEvent and the canonical outbox.",
    rationale: "Single evidence spine for consequential actions.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "fitness_audit_emission",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["governance.audit"],
    prohibitedPatterns: ["side_channel_audit"],
    requiredConditions: ["audit_on_consequential_action"],
  },
  {
    ruleKey: "C-015",
    title: "No parallel core systems",
    plainLanguage:
      "Do not introduce parallel User, Organisation, Consent, Mission, Audit, Place, Provider, Incident, or Billing systems.",
    rationale: "Stops platform fragmentation.",
    severity: "critical",
    ruleClass: "constitutional_rule",
    detectionMethod: "semantic_overlap",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["parallel_core_system"],
    requiredConditions: [],
  },
  {
    ruleKey: "C-016",
    title: "Missing data remains unknown",
    plainLanguage:
      "Absence of data must not be treated as a negative or affirmative fact.",
    rationale: "Protects participants from false inference.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "policy_review",
    owner: "privacy",
    approver: "privacy",
    affectedDomains: ["*"],
    prohibitedPatterns: ["unknown_as_false"],
    requiredConditions: [],
  },
  {
    ruleKey: "C-017",
    title: "Inference remains inference",
    plainLanguage:
      "Inferred values must be labelled as inference and never silently promoted to fact.",
    rationale: "Separates observed from predicted state.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "policy_review",
    owner: "privacy",
    approver: "privacy",
    affectedDomains: ["*"],
    prohibitedPatterns: ["silent_inference_promotion"],
    requiredConditions: ["inference_label"],
  },
  {
    ruleKey: "C-018",
    title: "Fixture data clearly labelled",
    plainLanguage:
      "Synthetic and fixture data must be labelled and never presented as production evidence.",
    rationale: "Prevents demo data from becoming production claims.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "fixture_label_scan",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["unlabelled_fixture"],
    requiredConditions: ["synthetic_flag"],
  },
  {
    ruleKey: "C-019",
    title: "Shadow mode cannot be marketed as production availability",
    plainLanguage:
      "Shadow or pilot capabilities must not be claimed as production-available.",
    rationale: "Honest capability claims.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "claim_registry",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["shadow_as_production"],
    requiredConditions: ["claim_evidence"],
  },
  {
    ruleKey: "C-020",
    title: "Governed pathways for sensitive domains",
    plainLanguage:
      "Physical, payment, claims, clinical, and safeguarding flows use separate governed pathways.",
    rationale: "Higher bar for high-harm domains.",
    severity: "critical",
    ruleClass: "constitutional_rule",
    detectionMethod: "agent_preflight_stop",
    owner: "security",
    approver: "security",
    affectedDomains: ["finance.*", "ndis.*", "safeguarding.*"],
    prohibitedPatterns: ["ungoverned_sensitive_path"],
    requiredConditions: ["governed_pathway"],
  },
  {
    ruleKey: "C-021",
    title: "Feature flags require full lifecycle metadata",
    plainLanguage:
      "Flags require owner, purpose, default, test coverage, review date, and retirement condition.",
    rationale: "Prevents permanent undocumented toggles.",
    severity: "medium",
    ruleClass: "constitutional_rule",
    detectionMethod: "flag_manifest",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["ownerless_flag"],
    requiredConditions: ["owner", "purpose", "default", "retirement"],
  },
  {
    ruleKey: "C-022",
    title: "Compatibility adapters require expiry",
    plainLanguage:
      "Adapters declare source, target, owner, expiry, and removal plan.",
    rationale: "Stops permanent compatibility debt.",
    severity: "medium",
    ruleClass: "constitutional_rule",
    detectionMethod: "adapter_registry",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["adapter_without_expiry"],
    requiredConditions: ["source", "target", "owner", "expiry"],
  },
  {
    ruleKey: "C-023",
    title: "External integrations require full contracts",
    plainLanguage:
      "Integrations require contract, version, authz, classification, provenance, health, and rollback.",
    rationale: "Operable and auditable vendor boundaries.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "supply_chain_and_parity",
    owner: "platform_assurance",
    approver: "security",
    affectedDomains: ["*"],
    prohibitedPatterns: ["undocumented_integration"],
    requiredConditions: ["contract", "rollback"],
  },
  {
    ruleKey: "C-024",
    title: "Major capabilities require a11y, privacy, security, owner, rollback",
    plainLanguage:
      "Major capabilities ship with accessibility, privacy, security review, owner, and rollback notes.",
    rationale: "Release readiness bar for participant-facing surfaces.",
    severity: "high",
    ruleClass: "constitutional_rule",
    detectionMethod: "capability_catalogue",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["capability_without_rollback"],
    requiredConditions: ["a11y", "privacy", "security", "owner", "rollback"],
  },
  {
    ruleKey: "C-025",
    title: "Public claims cannot exceed deployed evidence",
    plainLanguage:
      "No public production claim may exceed deployed capability evidence.",
    rationale: "Trust and regulatory honesty.",
    severity: "critical",
    ruleClass: "constitutional_rule",
    detectionMethod: "claim_vs_runtime",
    owner: "platform_assurance",
    approver: "architecture",
    affectedDomains: ["*"],
    prohibitedPatterns: ["overstated_claim"],
    requiredConditions: ["deployed_evidence"],
  },
];
