#!/usr/bin/env python3
"""Sync Neon connection strings to local .env and emit Vercel CLI commands.

Usage:
  python3 scripts/sync-neon-vercel-env.py '<pooled-neon-url>'
  NEON_POOLED_URL='postgresql://...' python3 scripts/sync-neon-vercel-env.py

Does not print passwords when --quiet-vercel is passed (writes a helper script only).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIGURE = ROOT / "scripts" / "configure-neon-env.py"
VERCEL_HELPER = ROOT / "scripts" / "vercel-env-push.sh"

VERCEL_PROJECT = "mapableau-new"
VERCEL_TEAM = "mapableau"

# Server-only vars to mirror from .env on Vercel (see README_NEON.md)
VERCEL_ENV_KEYS = [
    "DATABASE_URL",
    "DIRECT_URL",
    "NEXTAUTH_SECRET",
    "NEXTAUTH_URL",
    "NDIS_ENCRYPTION_KEY",
    "NEXT_PUBLIC_APP_URL",
    "REALTIME_DRIVER",
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "NEXT_PUBLIC_REALTIME_GATEWAY_URL",
    "REALTIME_INTERNAL_KEY",
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync Neon URLs to .env and Vercel")
    parser.add_argument(
        "pooled_url",
        nargs="?",
        help="Neon pooled connection string (or set NEON_POOLED_URL)",
    )
    parser.add_argument(
        "--push-vercel",
        action="store_true",
        help="Run vercel env add for each key (requires vercel CLI + login)",
    )
    parser.add_argument(
        "--environments",
        default="production,preview,development",
        help="Comma-separated Vercel environments",
    )
    args = parser.parse_args()

    pooled = (args.pooled_url or os.environ.get("NEON_POOLED_URL") or "").strip()
    if not pooled:
        raise SystemExit(
            "Provide pooled Neon URL as argument or NEON_POOLED_URL env var.\n"
            "Get it from Neon console or: Neon MCP get_connection_string"
        )

    subprocess.run(
        [sys.executable, str(CONFIGURE), pooled],
        check=True,
        cwd=ROOT,
    )

    env_file = ROOT / ".env"
    if not env_file.exists():
        raise SystemExit(".env missing after configure")

    env_map = parse_env(env_file)
    if not env_map.get("DATABASE_URL") or not env_map.get("DIRECT_URL"):
        raise SystemExit("DATABASE_URL and DIRECT_URL must be set in .env")

    write_vercel_helper(env_map, args.environments.split(","))

    print("\nLocal .env updated for Neon.")
    print(f"Vercel helper written: {VERCEL_HELPER}")
    print(
        f"\nManual dashboard: https://vercel.com/{VERCEL_TEAM}/{VERCEL_PROJECT}/settings/environment-variables"
    )

    if args.push_vercel:
        push_vercel_env(env_map, args.environments.split(","))


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        out[key.strip()] = val.strip().strip('"').strip("'")
    return out


def write_vercel_helper(env_map: dict[str, str], environments: list[str]) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/sync-neon-vercel-env.py — run from repo root after: vercel login",
        "set -euo pipefail",
        f'cd "$(dirname "$0")/.."',
        'test -f .env || { echo "Missing .env — run sync-neon-vercel-env.py first"; exit 1; }',
        'set -a; source .env; set +a',
        f'PROJECT="{VERCEL_PROJECT}"',
        f'TEAM_FLAG="--scope {VERCEL_TEAM}"',
        "",
    ]
    envs = " ".join(environments)
    for key in VERCEL_ENV_KEYS:
        if key not in env_map or not env_map[key]:
            lines.append(f"# skip {key} (empty in .env)")
            continue
        lines.append(
            f'if [ -n "${{{key}:-}}" ]; then '
            f'printf "%s" "${{{key}}}" | vercel env add {key} {envs} $TEAM_FLAG --yes 2>/dev/null || '
            f'printf "%s" "${{{key}}}" | vercel env add {key} {envs} $TEAM_FLAG; fi'
        )
    lines.append('echo "Done. Redeploy mapableau-new from Vercel dashboard or: vercel deploy --prod"')
    VERCEL_HELPER.write_text("\n".join(lines) + "\n")
    VERCEL_HELPER.chmod(0o755)


def push_vercel_env(env_map: dict[str, str], environments: list[str]) -> None:
    vercel = "vercel"
    try:
        subprocess.run([vercel, "--version"], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        raise SystemExit("Install Vercel CLI: pnpm add -g vercel && vercel login")

    envs = " ".join(environments)
    for key in VERCEL_ENV_KEYS:
        val = env_map.get(key, "")
        if not val or val.startswith("change-me"):
            print(f"skip {key}")
            continue
        print(f"push {key} → {envs}")
        subprocess.run(
            [vercel, "env", "add", key, *environments, "--scope", VERCEL_TEAM, "--yes"],
            input=val.encode(),
            cwd=ROOT,
            check=False,
        )


if __name__ == "__main__":
    main()
