#!/usr/bin/env bash
# Generated by scripts/sync-neon-vercel-env.py — run from repo root after: vercel login
set -euo pipefail
cd "$(dirname "$0")/.."
test -f .env || { echo "Missing .env — run sync-neon-vercel-env.py first"; exit 1; }
set -a; source .env; set +a
PROJECT="mapableau-new"
TEAM_FLAG="--scope mapableau"

if [ -n "${DATABASE_URL:-}" ]; then printf "%s" "${DATABASE_URL}" | vercel env add DATABASE_URL production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${DATABASE_URL}" | vercel env add DATABASE_URL production preview development $TEAM_FLAG; fi
if [ -n "${DIRECT_URL:-}" ]; then printf "%s" "${DIRECT_URL}" | vercel env add DIRECT_URL production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${DIRECT_URL}" | vercel env add DIRECT_URL production preview development $TEAM_FLAG; fi
if [ -n "${NEXTAUTH_SECRET:-}" ]; then printf "%s" "${NEXTAUTH_SECRET}" | vercel env add NEXTAUTH_SECRET production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${NEXTAUTH_SECRET}" | vercel env add NEXTAUTH_SECRET production preview development $TEAM_FLAG; fi
if [ -n "${NEXTAUTH_URL:-}" ]; then printf "%s" "${NEXTAUTH_URL}" | vercel env add NEXTAUTH_URL production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${NEXTAUTH_URL}" | vercel env add NEXTAUTH_URL production preview development $TEAM_FLAG; fi
if [ -n "${NDIS_ENCRYPTION_KEY:-}" ]; then printf "%s" "${NDIS_ENCRYPTION_KEY}" | vercel env add NDIS_ENCRYPTION_KEY production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${NDIS_ENCRYPTION_KEY}" | vercel env add NDIS_ENCRYPTION_KEY production preview development $TEAM_FLAG; fi
if [ -n "${NEXT_PUBLIC_APP_URL:-}" ]; then printf "%s" "${NEXT_PUBLIC_APP_URL}" | vercel env add NEXT_PUBLIC_APP_URL production preview development $TEAM_FLAG --yes 2>/dev/null || printf "%s" "${NEXT_PUBLIC_APP_URL}" | vercel env add NEXT_PUBLIC_APP_URL production preview development $TEAM_FLAG; fi
# skip REALTIME_DRIVER (empty in .env)
# skip NEXT_PUBLIC_SUPABASE_URL (empty in .env)
# skip NEXT_PUBLIC_SUPABASE_ANON_KEY (empty in .env)
# skip SUPABASE_SERVICE_ROLE_KEY (empty in .env)
# skip NEXT_PUBLIC_REALTIME_GATEWAY_URL (empty in .env)
# skip REALTIME_INTERNAL_KEY (empty in .env)
echo "Done. Redeploy mapableau-new from Vercel dashboard or: vercel deploy --prod"
