import type { LivingAccessGraphSnapshot } from "./types";

const OBSERVED = "2026-06-01T00:00:00.000Z";

/**
 * Synthetic Harbour Civic precinct for Living Access Fabric Wave 2.
 * Canonical AccessPlace refs are synthetic placeholders (not production IDs).
 */
export const HARBOUR_LIVING_ACCESS_GRAPH: LivingAccessGraphSnapshot = {
  snapshotId: "harbour-civic-synthetic-v1",
  precinctId: "harbour_civic",
  precinctLabel: "Harbour Civic Precinct (synthetic)",
  generatedAt: "2026-07-17T00:00:00.000Z",
  synthetic: true,
  limitations: [
    "Synthetic fixture only — not a public accessibility claim",
    "Lift operational state is unknown in the baseline fixture",
    "Corridor clear width on level 3 is unresolved",
  ],
  nodes: [
    {
      id: "harbour_civic.place",
      kind: "access_place",
      label: "Harbour Civic Centre",
      canonicalRef: "accessplace:synthetic:harbour_civic",
      ontologyConceptIds: [],
      properties: { suburb: "Circular Quay", jurisdiction: "NSW" },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Harbour Civic Centre — synthetic AccessPlace",
    },
    {
      id: "harbour_civic.stop_ferry",
      kind: "transport_stop",
      label: "Harbour ferry stop (accessible berth)",
      canonicalRef: null,
      ontologyConceptIds: ["transport.accessible_vehicle"],
      properties: { step_free: true },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Ferry stop with step-free berth (synthetic)",
    },
    {
      id: "harbour_civic.curb_west",
      kind: "curb_zone",
      label: "West curb transition",
      canonicalRef: null,
      ontologyConceptIds: ["physical.step_free"],
      properties: { step_free: true, surface: "sealed" },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "West curb — step-free sealed transition",
    },
    {
      id: "harbour_civic.path_external",
      kind: "path",
      label: "External approach path",
      canonicalRef: null,
      ontologyConceptIds: ["physical.step_free", "physical.minimum_clear_width_mm"],
      properties: { step_free: true, clear_width_mm: 1800 },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "External path — step-free, 1800 mm clear width",
    },
    {
      id: "harbour_civic.entrance_west",
      kind: "entrance",
      label: "Western entrance",
      canonicalRef: null,
      ontologyConceptIds: [
        "physical.step_free",
        "physical.minimum_clear_width_mm",
        "physical.revolving_door",
        "physical.staff_dependent_entrance",
      ],
      properties: {
        step_free: true,
        clear_width_mm: 910,
        revolving_door: false,
        staff_dependent: false,
      },
      temporalState: "current",
      evidenceClass: "independently_verified_claim",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Western entrance — step-free, 910 mm clear width (verified synthetic)",
    },
    {
      id: "harbour_civic.entrance_staff",
      kind: "entrance",
      label: "Staff-assisted service entrance",
      canonicalRef: null,
      ontologyConceptIds: ["physical.staff_dependent_entrance", "physical.step_free"],
      properties: {
        step_free: true,
        clear_width_mm: 1000,
        revolving_door: false,
        staff_dependent: true,
      },
      temporalState: "current",
      evidenceClass: "venue_declaration",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Staff-dependent entrance — excluded when assistance-only entrances avoided",
    },
    {
      id: "harbour_civic.door_lobby",
      kind: "door",
      label: "Lobby inner door",
      canonicalRef: null,
      ontologyConceptIds: ["physical.minimum_clear_width_mm"],
      properties: { clear_width_mm: 900 },
      temporalState: "current",
      evidenceClass: "manual_measurement",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Lobby door — 900 mm clear width",
    },
    {
      id: "harbour_civic.lift_a",
      kind: "lift",
      label: "Lift A to levels 1–4",
      canonicalRef: null,
      ontologyConceptIds: ["physical.lift_operational", "physical.step_free"],
      properties: { lift_operational: null, cabin_width_mm: 1100 },
      temporalState: "unknown",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Lift A — operational status unknown",
    },
    {
      id: "harbour_civic.floor_3",
      kind: "floor",
      label: "Level 3",
      canonicalRef: null,
      ontologyConceptIds: [],
      properties: { level: 3 },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Level 3 floor plate",
    },
    {
      id: "harbour_civic.corridor_3",
      kind: "path",
      label: "Level 3 corridor to Room 3.12",
      canonicalRef: null,
      ontologyConceptIds: ["physical.minimum_clear_width_mm", "physical.step_free"],
      properties: { step_free: true, clear_width_mm: null },
      temporalState: "unknown",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Level 3 corridor — clear width unresolved",
    },
    {
      id: "harbour_civic.room_3_12",
      kind: "room",
      label: "Room 3.12",
      canonicalRef: "harbour_civic.room_3_12",
      ontologyConceptIds: ["physical.step_free"],
      properties: { step_free: true },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Room 3.12 — destination room",
    },
    {
      id: "harbour_civic.toilet_3",
      kind: "toilet",
      label: "Level 3 accessible toilet",
      canonicalRef: null,
      ontologyConceptIds: ["physical.accessible_toilet"],
      properties: { accessible_toilet: true },
      temporalState: "current",
      evidenceClass: "venue_declaration",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Level 3 accessible toilet — venue declared",
    },
    {
      id: "harbour_civic.counter_service",
      kind: "counter",
      label: "Service counter (level 3)",
      canonicalRef: null,
      ontologyConceptIds: [],
      properties: { lowered_section: true },
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      observedAt: OBSERVED,
      publicPartition: true,
      listSummary: "Service counter with lowered section",
    },
  ],
  edges: [
    {
      id: "e1",
      kind: "connects_to",
      from: "harbour_civic.stop_ferry",
      to: "harbour_civic.curb_west",
      label: "Stop to curb",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e2",
      kind: "connects_to",
      from: "harbour_civic.curb_west",
      to: "harbour_civic.path_external",
      label: "Curb to path",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e3",
      kind: "connects_to",
      from: "harbour_civic.path_external",
      to: "harbour_civic.entrance_west",
      label: "Path to western entrance",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e4",
      kind: "connects_to",
      from: "harbour_civic.path_external",
      to: "harbour_civic.entrance_staff",
      label: "Path to staff entrance",
      temporalState: "current",
      evidenceClass: "venue_declaration",
      properties: {},
    },
    {
      id: "e5",
      kind: "connects_to",
      from: "harbour_civic.entrance_west",
      to: "harbour_civic.door_lobby",
      label: "Entrance to lobby door",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e6",
      kind: "connects_to",
      from: "harbour_civic.door_lobby",
      to: "harbour_civic.lift_a",
      label: "Lobby to lift",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e7",
      kind: "connects_to",
      from: "harbour_civic.lift_a",
      to: "harbour_civic.floor_3",
      label: "Lift to level 3",
      temporalState: "unknown",
      evidenceClass: "synthetic_fixture",
      properties: { requires: "physical.lift_operational" },
    },
    {
      id: "e8",
      kind: "contains",
      from: "harbour_civic.floor_3",
      to: "harbour_civic.corridor_3",
      label: "Floor contains corridor",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e9",
      kind: "connects_to",
      from: "harbour_civic.corridor_3",
      to: "harbour_civic.room_3_12",
      label: "Corridor to Room 3.12",
      temporalState: "unknown",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e10",
      kind: "connects_to",
      from: "harbour_civic.corridor_3",
      to: "harbour_civic.toilet_3",
      label: "Corridor to accessible toilet",
      temporalState: "current",
      evidenceClass: "venue_declaration",
      properties: {},
    },
    {
      id: "e11",
      kind: "alternative_to",
      from: "harbour_civic.entrance_west",
      to: "harbour_civic.entrance_staff",
      label: "Western entrance alternative to staff entrance",
      temporalState: "current",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
    {
      id: "e12",
      kind: "requires_confirmation",
      from: "harbour_civic.lift_a",
      to: "harbour_civic.room_3_12",
      label: "Lift status confirmation required for room access",
      temporalState: "unknown",
      evidenceClass: "synthetic_fixture",
      properties: {},
    },
  ],
};

export function getHarbourGraph(): LivingAccessGraphSnapshot {
  return HARBOUR_LIVING_ACCESS_GRAPH;
}
