import { getOntologyConceptV2 } from "./seed-v2";
import type { AccessOntologyConcept, AccessOntologyVersion } from "./types";

const V = "1.0.0";

function concept(
  partial: Omit<AccessOntologyConcept, "version"> & { version?: string },
): AccessOntologyConcept {
  return { version: V, ...partial };
}

/** Versioned ontology seed — Wave 1 contracts. Not a universal score schema. */
export const ONTOLOGY_CONCEPTS_V1: AccessOntologyConcept[] = [
  concept({
    id: "physical.step_free",
    domain: "physical",
    definition: "Level or ramped access without steps on the evaluated segment.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observed_or_measured_path_segment"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:pathway"],
    permittedInference: ["combine_segment_step_free_flags"],
    prohibitedInference: ["infer_from_diagnosis", "infer_from_popularity"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "physical.minimum_clear_width_mm",
    domain: "physical",
    definition: "Clear opening or path width in millimetres.",
    dataType: "dimension",
    unit: "mm",
    evidenceRequirements: ["manual_or_professional_measurement_preferred"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:clear_width"],
    permittedInference: ["min_across_route_segments"],
    prohibitedInference: ["treat_vision_estimate_as_certified"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
  }),
  concept({
    id: "physical.threshold_mm",
    domain: "physical",
    definition: "Vertical threshold height at a doorway or transition.",
    dataType: "dimension",
    unit: "mm",
    evidenceRequirements: ["measurement_or_assessor_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:threshold"],
    permittedInference: [],
    prohibitedInference: ["infer_from_photo_without_scale"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
  }),
  concept({
    id: "physical.gradient_ratio",
    domain: "physical",
    definition: "Ramp or path gradient as rise:run ratio.",
    dataType: "text",
    unit: null,
    evidenceRequirements: ["measured_gradient"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:ramps"],
    permittedInference: [],
    prohibitedInference: ["infer_safe_for_all_users"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
  }),
  concept({
    id: "physical.lift_operational",
    domain: "physical",
    definition: "Lift or vertical circulation currently available for use.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operational_state_or_fresh_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: ["scheduled_maintenance_windows"],
    prohibitedInference: ["assume_operational_from_static_geometry"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "physical.accessible_toilet",
    domain: "physical",
    definition: "Accessible toilet facility available on the journey.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["feature_observation_with_location"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:sanitary"],
    permittedInference: [],
    prohibitedInference: ["infer_from_building_class_alone"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "sensory.hearing_augmentation",
    domain: "sensory",
    definition: "Hearing augmentation system available in the destination space.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_declaration_or_verified_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "sensory.quiet_space",
    domain: "sensory",
    definition: "Designated low-stimulation quiet space.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_or_mapper_observation"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["score_participant_sensory_tolerance"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "cognitive_communication.plain_language",
    domain: "cognitive_communication",
    definition: "Essential journey information available in plain language.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["content_review"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["WCAG2.2:3.1"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "cognitive_communication.human_assistance",
    domain: "cognitive_communication",
    definition: "Staff or supporter assistance available for the journey segment.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operational_roster_or_venue_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: ["opening_hours_bounds"],
    prohibitedInference: ["assume_always_available"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 7,
  }),
  concept({
    id: "service.assistance_animal_policy",
    domain: "service",
    definition: "Assistance animal welcome policy for the place.",
    dataType: "enum",
    unit: null,
    enumValues: ["welcome", "restricted", "unknown"],
    evidenceRequirements: ["venue_declaration_or_policy_document"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis", "infer_pet_policy_as_assistance_animal"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "digital.keyboard_access",
    domain: "digital",
    definition: "Digital booking or information channel is keyboard accessible.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["accessibility_ops_test"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["WCAG2.2:2.1.1"],
    permittedInference: [],
    prohibitedInference: ["infer_from_mobile_app_only_test"],
    reviewOwner: "accessibility-ops",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "transport.accessible_vehicle",
    domain: "transport",
    definition: "Assigned or available vehicle meets accessible boarding requirements.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operator_confirmation_with_equipment_class"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["treat_booking_created_as_vehicle_confirmed"],
    reviewOwner: "transport",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "transport.boarding_assistance",
    domain: "transport",
    definition: "Boarding assistance available for the trip.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operator_or_driver_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_vehicle_type_alone"],
    reviewOwner: "transport",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "physical.revolving_door",
    domain: "physical",
    definition: "Entrance uses a revolving door (often incompatible without alternative).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["assume_no_alternative_entrance"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "physical.staff_dependent_entrance",
    domain: "physical",
    definition: "Entrance usable only with staff assistance.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_or_mapper_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["treat_as_independent_access"],
    reviewOwner: "access-intelligence",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
];

export const ACCESS_ONTOLOGY_V1: AccessOntologyVersion = {
  version: V,
  publishedAt: "2026-07-17T00:00:00.000Z",
  concepts: ONTOLOGY_CONCEPTS_V1,
};

/** Resolve concept by v2 id, v1 id, or v1→v2 alias. */
export function getOntologyConcept(id: string): AccessOntologyConcept | undefined {
  return getOntologyConceptV2(id) ?? ONTOLOGY_CONCEPTS_V1.find((c) => c.id === id);
}
