import type { AccessDomain } from "@/lib/access/infrastructure/domains";

import type { AccessOntologyConcept, AccessOntologyVersion } from "./types";

const V = "2.0.0";

function concept(
  partial: Omit<AccessOntologyConcept, "version"> & { version?: string },
): AccessOntologyConcept {
  return { version: V, ...partial };
}

/**
 * Ontology v2 — Access as Infrastructure domains.
 * Expands beyond premises to services, journeys, digital, emergency, etc.
 * Never includes a universal accessibility score concept.
 */
export const ONTOLOGY_CONCEPTS_V2: AccessOntologyConcept[] = [
  // —— Mobility & movement ——
  concept({
    id: "mobility_movement.step_free",
    domain: "mobility_movement",
    definition: "Level or ramped access without steps on the evaluated segment.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observed_or_measured_path_segment"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:pathway"],
    permittedInference: ["combine_segment_step_free_flags"],
    prohibitedInference: ["infer_from_diagnosis", "infer_from_popularity"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
    aliases: ["physical.step_free"],
  }),
  concept({
    id: "mobility_movement.minimum_clear_width_mm",
    domain: "mobility_movement",
    definition: "Clear opening or path width in millimetres.",
    dataType: "dimension",
    unit: "mm",
    evidenceRequirements: ["manual_or_professional_measurement_preferred"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:clear_width"],
    permittedInference: ["min_across_route_segments"],
    prohibitedInference: ["treat_vision_estimate_as_certified"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
    aliases: ["physical.minimum_clear_width_mm"],
  }),
  concept({
    id: "mobility_movement.threshold_mm",
    domain: "mobility_movement",
    definition: "Vertical threshold height at a doorway or transition.",
    dataType: "dimension",
    unit: "mm",
    evidenceRequirements: ["measurement_or_assessor_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:threshold"],
    permittedInference: [],
    prohibitedInference: ["infer_from_photo_without_scale"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
    aliases: ["physical.threshold_mm"],
  }),
  concept({
    id: "mobility_movement.gradient_ratio",
    domain: "mobility_movement",
    definition: "Ramp or path gradient as rise:run ratio.",
    dataType: "text",
    unit: null,
    evidenceRequirements: ["measured_gradient"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:ramps"],
    permittedInference: [],
    prohibitedInference: ["infer_safe_for_all_users"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
    aliases: ["physical.gradient_ratio"],
  }),
  concept({
    id: "mobility_movement.lift_operational",
    domain: "mobility_movement",
    definition: "Lift or vertical circulation currently available for use.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operational_state_or_fresh_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: ["scheduled_maintenance_windows"],
    prohibitedInference: ["assume_operational_from_static_geometry"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
    aliases: ["physical.lift_operational"],
  }),
  concept({
    id: "mobility_movement.surface_stable",
    domain: "mobility_movement",
    definition: "Path surface is firm and stable for mobility devices.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation_or_assessor"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:continuous_accessible_path"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "mobility_movement.turning_space",
    domain: "mobility_movement",
    definition: "Adequate turning space for mobility devices at critical points.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["measurement_or_assessor_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:circulation"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
  }),
  concept({
    id: "mobility_movement.revolving_door",
    domain: "mobility_movement",
    definition: "Entrance uses a revolving door (often incompatible without alternative).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["assume_no_alternative_entrance"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
    aliases: ["physical.revolving_door"],
  }),
  concept({
    id: "mobility_movement.staff_dependent_entrance",
    domain: "mobility_movement",
    definition: "Entrance usable only with staff assistance.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_or_mapper_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["treat_as_independent_access"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
    aliases: ["physical.staff_dependent_entrance"],
  }),

  // —— Reach / seating ——
  concept({
    id: "reach_strength_dexterity.low_force_door",
    domain: "reach_strength_dexterity",
    definition: "Door operable with low opening force or automatic operation.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["measurement_or_assessor_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:doorways"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "seating_stamina.rest_seating_available",
    domain: "seating_stamina",
    definition: "Rest seating available along approach or within the venue.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),

  // —— Vision / hearing ——
  concept({
    id: "vision.tactile_or_braille_signage",
    domain: "vision",
    definition: "Tactile and/or Braille wayfinding or identification signage present.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:signage"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "vision.detectable_edges",
    domain: "vision",
    definition: "Detectable warning or edge treatments at hazards and transitions.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation_or_assessor"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.4"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 730,
  }),
  concept({
    id: "hearing.hearing_augmentation",
    domain: "hearing",
    definition: "Hearing augmentation system available in the destination space.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_declaration_or_verified_observation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
    aliases: ["sensory.hearing_augmentation"],
  }),
  concept({
    id: "hearing.visual_announcements",
    domain: "hearing",
    definition: "Visual equivalents for spoken announcements.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation_or_operator_declaration"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),

  // —— Communication / language / cognition ——
  concept({
    id: "speech_communication.text_fallback",
    domain: "speech_communication",
    definition: "Staff or service can communicate via text as a fallback.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_or_service_declaration"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "speech_communication.direct_communication",
    domain: "speech_communication",
    definition: "Service undertakes to communicate directly with the person (not via companion by default).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["policy_or_staff_practice_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "auslan_language.auslan_available",
    domain: "auslan_language",
    definition: "Auslan interpreting available for the service or event (booked or on-site).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["booking_confirmation_or_roster"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: ["scheduled_session_windows"],
    prohibitedInference: ["assume_always_available"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 7,
  }),
  concept({
    id: "auslan_language.easy_read",
    domain: "auslan_language",
    definition: "Essential information available in Easy Read.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["content_review"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "cognition_learning.plain_language",
    domain: "cognition_learning",
    definition: "Essential journey information available in plain language.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["content_review"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["WCAG2.2:3.1"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
    aliases: ["cognitive_communication.plain_language"],
  }),
  concept({
    id: "cognition_learning.human_assistance",
    domain: "cognition_learning",
    definition: "Staff or supporter assistance available for the journey segment.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operational_roster_or_venue_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: ["opening_hours_bounds"],
    prohibitedInference: ["assume_always_available"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 7,
    aliases: ["cognitive_communication.human_assistance"],
  }),
  concept({
    id: "executive_memory.preparation_information",
    domain: "executive_memory",
    definition: "Clear preparation information provided before the visit or journey.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["content_review"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),

  // —— Sensory / psychosocial / fatigue ——
  concept({
    id: "sensory_regulation.quiet_space",
    domain: "sensory_regulation",
    definition: "Designated low-stimulation quiet space.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_or_mapper_observation"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["score_participant_sensory_tolerance"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
    aliases: ["sensory.quiet_space"],
  }),
  concept({
    id: "sensory_regulation.low_sensory_environment",
    domain: "sensory_regulation",
    definition: "Environment managed for reduced sensory load (lighting/noise/crowd).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_declaration_or_observation"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: ["scheduled_sensory_friendly_sessions"],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "psychosocial.chosen_supporter_welcome",
    domain: "psychosocial",
    definition: "Person may bring a chosen supporter into the service environment.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["policy_declaration"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "pain_fatigue_fluctuating.flexible_timing",
    domain: "pain_fatigue_fluctuating",
    definition: "Flexible arrival or appointment timing accommodated.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["service_policy"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),

  // —— Self-care / equipment / animals ——
  concept({
    id: "self_care_continence.accessible_toilet",
    domain: "self_care_continence",
    definition: "Accessible toilet facility available on the journey.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["feature_observation_with_location"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["AS1428.1:sanitary"],
    permittedInference: [],
    prohibitedInference: ["infer_from_building_class_alone"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
    aliases: ["physical.accessible_toilet"],
  }),
  concept({
    id: "self_care_continence.changing_places",
    domain: "self_care_continence",
    definition: "Changing Places (or equivalent adult change) facility available.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["verified_facility_listing_or_assessor"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_accessible_toilet_alone"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
  concept({
    id: "equipment_at.wheelchair_charging",
    domain: "equipment_at",
    definition: "Mobility device charging point available.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_declaration_or_observation"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "assistance_animals.welcome_policy",
    domain: "assistance_animals",
    definition: "Assistance animal welcome policy for the place.",
    dataType: "enum",
    unit: null,
    enumValues: ["welcome", "restricted", "unknown"],
    evidenceRequirements: ["venue_declaration_or_policy_document"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis", "infer_pet_policy_as_assistance_animal"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
    aliases: ["service.assistance_animal_policy"],
  }),

  // —— Digital / service / financial ——
  concept({
    id: "digital.keyboard_access",
    domain: "digital",
    definition: "Digital booking or information channel is keyboard accessible.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["accessibility_ops_test"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["WCAG2.2:2.1.1"],
    permittedInference: [],
    prohibitedInference: ["infer_from_mobile_app_only_test"],
    reviewOwner: "accessibility-ops",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "digital.no_timed_only_interactions",
    domain: "digital",
    definition: "Critical tasks do not rely on timed interactions without extension.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["accessibility_ops_test"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["WCAG2.2:2.2.1"],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "accessibility-ops",
    deprecationPathway: null,
    defaultFreshnessDays: 90,
  }),
  concept({
    id: "service_staff.adjustment_procedure",
    domain: "service_staff",
    definition: "Published procedure for requesting reasonable adjustments.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["policy_document"],
    personalFitBehaviour: "preference_only",
    standardsMappings: ["DDA:reasonable_adjustments"],
    permittedInference: [],
    prohibitedInference: ["treat_as_dda_compliance_certificate"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "financial_admin.accessible_complaints",
    domain: "financial_admin",
    definition: "Accessible complaints channel available (not phone-only).",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["policy_or_channel_review"],
    personalFitBehaviour: "preference_only",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),

  // —— Transport / emergency ——
  concept({
    id: "transport.accessible_vehicle",
    domain: "transport",
    definition: "Assigned or available vehicle meets accessible boarding requirements.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operator_confirmation_with_equipment_class"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: ["DSAPT"],
    permittedInference: [],
    prohibitedInference: ["treat_booking_created_as_vehicle_confirmed"],
    reviewOwner: "transport",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "transport.boarding_assistance",
    domain: "transport",
    definition: "Boarding assistance available for the trip.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["operator_or_driver_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_vehicle_type_alone"],
    reviewOwner: "transport",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "transport.remain_in_wheelchair",
    domain: "transport",
    definition: "Passenger may remain seated in their wheelchair during travel.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["vehicle_equipment_class_confirmation"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis"],
    reviewOwner: "transport",
    deprecationPathway: null,
    defaultFreshnessDays: 1,
  }),
  concept({
    id: "transport.accessible_dropoff",
    domain: "transport",
    definition: "Accessible drop-off / pickup point at the destination.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["observation_or_venue_declaration"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_accessible_entrance_alone"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 180,
  }),
  concept({
    id: "emergency.accessible_exit_information",
    domain: "emergency",
    definition: "Accessible exit and evacuation information available.",
    dataType: "boolean",
    unit: null,
    evidenceRequirements: ["venue_emergency_plan_or_assessor"],
    personalFitBehaviour: "hard_constraint_when_required",
    standardsMappings: [],
    permittedInference: [],
    prohibitedInference: ["infer_from_diagnosis", "assume_staff_always_present"],
    reviewOwner: "access-infrastructure",
    deprecationPathway: null,
    defaultFreshnessDays: 365,
  }),
];

export const ACCESS_ONTOLOGY_V2: AccessOntologyVersion = {
  version: V,
  publishedAt: "2026-08-11T00:00:00.000Z",
  framework: "access_as_infrastructure",
  concepts: ONTOLOGY_CONCEPTS_V2,
};

/** v1 concept id → v2 concept id */
export const ONTOLOGY_CONCEPT_ALIASES_V1_TO_V2: Record<string, string> = Object.fromEntries(
  ONTOLOGY_CONCEPTS_V2.flatMap((c) => (c.aliases ?? []).map((alias) => [alias, c.id])),
);

export function resolveOntologyConceptId(id: string): string {
  return ONTOLOGY_CONCEPT_ALIASES_V1_TO_V2[id] ?? id;
}

export function getOntologyConceptV2(id: string): AccessOntologyConcept | undefined {
  const resolved = resolveOntologyConceptId(id);
  return (
    ONTOLOGY_CONCEPTS_V2.find((c) => c.id === resolved || c.id === id) ??
    ONTOLOGY_CONCEPTS_V2.find((c) => c.aliases?.includes(id))
  );
}

export function listAccessDomainsInOntology(): AccessDomain[] {
  return [...new Set(ONTOLOGY_CONCEPTS_V2.map((c) => c.domain as AccessDomain))];
}
