import type { CapabilitySeed } from "@/lib/platform/convergence-os/types";

export const CAPABILITY_SEEDS: CapabilitySeed[] = [
  {
    capabilityKey: "access.place_search",
    name: "Accessibility place search",
    programme: "Access",
    userValue: "Find accessible places matching needs",
    canonicalOwner: "places.access_place",
    implementationPaths: ["app/access/", "lib/access/fit/"],
    authorityLevel: "read",
    readWrite: "read",
    maturity: "production_gated",
    persistenceType: "prisma",
    runtimeMode: "live",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: true,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "access.indoor_floor_plan",
    name: "Indoor floor-plan viewing",
    programme: "Indoor Accessibility",
    userValue: "View indoor floor plans for venues",
    canonicalOwner: "places.floor_plan",
    implementationPaths: ["lib/access/indoor/", "lib/access/floor-plan/"],
    featureFlags: ["floorPlanAuthoring", "INDOOR_FLAG_*"],
    maturity: "pilot",
    persistenceType: "prisma",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.trip_request",
    name: "Transport request",
    programme: "Transport",
    userValue: "Request accessible transport trips",
    canonicalOwner: "transport.trip",
    implementationPaths: ["lib/transport/", "app/api/transport/"],
    maturity: "production_gated",
    persistenceType: "prisma",
    productionClaimStatus: "pilot",
    honesty: {
      implemented: true,
      featureEnabled: true,
      connected: true,
      durable: true,
      tested: true,
      piloted: true,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.driver_vehicle_verification",
    name: "Driver and vehicle verification",
    programme: "Transport",
    canonicalOwner: "transport.trip",
    implementationPaths: ["PR #276 app/api/provider/transport/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "aura.mission_planning",
    name: "AURA mission planning",
    programme: "AURA",
    canonicalOwner: "aura.proposal",
    implementationPaths: ["lib/aura/", "app/api/intelligence/aura/"],
    authorityLevel: "propose",
    maturity: "shadow",
    persistenceType: "prisma_and_memory",
    runtimeMode: "shadow",
    productionClaimStatus: "fixture_only",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "aura.approved_execution",
    name: "Approved AURA execution",
    programme: "AURA",
    canonicalOwner: "aura.execution",
    implementationPaths: ["lib/aura/execution/"],
    authorityLevel: "execution",
    externalSideEffects: true,
    participantApprovalRequired: true,
    maturity: "fixture_only",
    persistenceType: "prisma",
    runtimeMode: "gated_off",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Keep execution flags false; no auto-enable",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "rights.purpose_evaluation",
    name: "RightsOS purpose evaluation",
    programme: "RightsOS",
    canonicalOwner: "rights.purpose",
    implementationPaths: ["lib/rights-os/", "PR #280"],
    featureFlags: ["MAPABLE_RIGHTSOS_*"],
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "vault.disclosure_preview",
    name: "Vault disclosure preview",
    programme: "Personal Access Vault",
    canonicalOwner: "vault.personal_access",
    implementationPaths: ["lib/vault/", "PR #281"],
    featureFlags: ["MAPABLE_PERSONAL_ACCESS_VAULT_ENABLED"],
    participantApprovalRequired: true,
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "civic.asset_registry",
    name: "Civic asset registry",
    programme: "Civic Access Infrastructure",
    canonicalOwner: "places.civic_asset",
    implementationPaths: ["lib/civic-access/", "PR #284"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "a11yops.shadow_rules",
    name: "AccessibilityOps shadow rule evaluation",
    programme: "AccessibilityOps",
    canonicalOwner: "places.accessibility_asset",
    implementationPaths: ["lib/accessibility-ops/", "PR #282"],
    maturity: "shadow",
    persistenceType: "prisma",
    runtimeMode: "shadow",
    productionClaimStatus: "shadow",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.funding_route_validation",
    name: "NDIS funding-route validation",
    programme: "NDIS Gateway",
    canonicalOwner: "ndis.gateway",
    implementationPaths: ["lib/ndis-gateway/", "PR #286"],
    maturity: "scaffolded",
    persistenceType: "none",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.claim_submission",
    name: "Claim submission",
    programme: "NDIS Gateway",
    canonicalOwner: "ndis.gateway",
    implementationPaths: ["lib/ndis/claiming/", "lib/integrations/adapters/"],
    featureFlags: ["NDIA_REAL_SUBMISSION_ENABLED"],
    externalSideEffects: true,
    maturity: "fixture_only",
    persistenceType: "prisma",
    runtimeMode: "mock",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "careos.mission_sor",
    name: "CareOS mission source of truth",
    programme: "CareOS",
    canonicalOwner: "missions.careos_mission",
    implementationPaths: ["PR #252"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "programmes.foundation",
    name: "Shared programme foundation",
    programme: "Shared Programme Foundation",
    implementationPaths: ["lib/programmes/", "PR #279"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "convergence.control_plane",
    name: "ConvergenceOS control plane",
    programme: "Platform Assurance",
    canonicalOwner: "convergence.control_plane",
    implementationPaths: ["lib/platform/convergence-os/", "app/admin/convergence/"],
    featureFlags: ["MAPABLE_CONVERGENCE_OS_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    runtimeMode: "audit",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "access.intelligence_next",
    name: "Access Intelligence Next (Living Access Fabric)",
    programme: "Access Intelligence Next",
    canonicalOwner: "places.access_place",
    implementationPaths: ["lib/access/intelligence-next/"],
    featureFlags: ["MAPABLE_ACCESS_INTELLIGENCE_NEXT_*"],
    maturity: "shadow",
    persistenceType: "fixture_only",
    runtimeMode: "synthetic_shadow",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "accesscast.outlook",
    name: "AccessCast journey/place outlook",
    programme: "AccessCast",
    canonicalOwner: "places.access_place",
    implementationPaths: [
      "lib/accesscast/",
      "app/api/accesscast/",
      "app/accesscast/",
    ],
    featureFlags: ["MAPABLE_ACCESSCAST_ENABLED", "MAPABLE_ACCESSCAST_MODE"],
    maturity: "fixture_only",
    persistenceType: "fixture_only",
    runtimeMode: "synthetic",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Keep AccessCast flags false; never present synthetic outlook as live truth",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "transport.quotes",
    name: "Transport quotes (versioned, expiring)",
    programme: "Transport",
    userValue:
      "Receive accessible transport quotes before exact address disclosure",
    canonicalOwner: "transport.trip",
    implementationPaths: [
      "lib/transport/quotes/",
      "lib/transport/privacy/location-disclosure.ts",
      "app/api/transport/quotes/",
      "prisma/migrations/20260717150000_transport_quotes_persistent/",
    ],
    maturity: "scaffolded",
    persistenceType: "prisma",
    runtimeMode: "gated_off",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Prisma TransportQuote + versions; quote ≠ funding approval; acceptance ≠ exact address for providers",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "workforce.readiness",
    name: "Workforce assignment readiness (no auto-assign)",
    programme: "WorkforceOS",
    canonicalOwner: "org.membership",
    implementationPaths: [
      "lib/workforce/readiness/",
      "app/api/workforce/readiness/",
    ],
    authorityLevel: "evaluate",
    featureFlags: ["MAPABLE_WORKFORCE_READINESS_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Never enable auto-assignment or worker scoring",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "mobile.companion",
    name: "Native MapAble Companion",
    programme: "Companion",
    canonicalOwner: "mobile.companion",
    implementationPaths: [
      "mobile-contracts/",
      "apps/companion/",
      "lib/companion/",
      "app/api/companion/",
    ],
    featureFlags: [
      "MAPABLE_COMPANION_ENABLED",
      "MAPABLE_COMPANION_VISIT_PACK_ENABLED",
    ],
    maturity: "scaffolded",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "provider.ops_attention",
    name: "Provider Operations attention queue",
    programme: "Provider Operations",
    canonicalOwner: "provider.ops_projection",
    implementationPaths: [
      "lib/provider/ops/",
      "app/api/provider-ops/",
      "app/provider-ops/",
    ],
    featureFlags: ["MAPABLE_PROVIDER_OPS_ENABLED"],
    readWrite: "read",
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes: "Read-only projection — never a second operational writer",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "billing.centre",
    name: "Billing Centre (BillingInvoice)",
    programme: "Billing",
    canonicalOwner: "finance.billing_invoice",
    implementationPaths: ["lib/billing/", "app/api/billing/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "care.request_loop",
    name: "Care request to evidence loop",
    programme: "Care",
    canonicalOwner: "care.case",
    implementationPaths: ["lib/care/", "app/api/care/"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "planned",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "care.recurring_schedules",
    name: "Recurring Care schedules and agreement amend",
    programme: "Care",
    canonicalOwner: "care.case",
    implementationPaths: [
      "lib/care/care-recurring-schedule-service.ts",
      "lib/care/care-agreement-service.ts",
      "app/api/care/bookings/",
      "prisma/migrations/20260717160000_care_recurring_schedules/",
    ],
    featureFlags: ["MAPABLE_CARE_RECURRING_SCHEDULES_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Flag default off; schedule is not a second agreement SoT; cancel Care ≠ cancel Transport",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "communication.passport",
    name: "Communication Passport",
    programme: "Access Passport",
    canonicalOwner: "access.passport",
    implementationPaths: [
      "lib/support/communication-passport/",
      "app/api/communication-passport/",
      "app/communication-passport/",
    ],
    participantApprovalRequired: true,
    featureFlags: ["MAPABLE_COMMUNICATION_PASSPORT_ENABLED"],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: true,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "outcomes.ledger",
    name: "Outcomes and Impact Ledger",
    programme: "Outcomes",
    canonicalOwner: "outcomes.ledger",
    implementationPaths: ["lib/outcomes/"],
    maturity: "concept",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "pilot.starting_work",
    name: "Starting Work controlled pilot",
    programme: "Productisation Pilot",
    canonicalOwner: "missions.case",
    implementationPaths: [
      "docs/productisation/STARTING_WORK_PILOT.md",
      "lib/pilot/starting-work/",
      "app/api/pilot/starting-work/",
    ],
    featureFlags: [
      "MAPABLE_STARTING_WORK_PILOT_ENABLED",
      "MAPABLE_STARTING_WORK_SYNTHETIC_ONLY",
    ],
    maturity: "fixture_only",
    persistenceType: "fixture_only",
    runtimeMode: "synthetic",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Synthetic-only by default; database-backed golden journey is a later PR — never market as live",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "managed.support_delivery",
    name: "MapAble Managed Support (direct regulated delivery)",
    programme: "Managed Support",
    canonicalOwner: "care.case",
    implementationPaths: ["docs/strategy/OPERATING_LANES.md"],
    maturity: "concept",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Blocked by registration — do not fabricate NDIS registration or employed-workforce claims",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  // NDIS Expansion Programme (Wave 0 documented; product waves gated)
  {
    capabilityKey: "ndis.expansion_foundation",
    name: "NDIS Expansion programme foundation",
    programme: "NDIS Expansion",
    implementationPaths: [
      "docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md",
      "docs/programmes/NDIS_EXPANSION_DOMAIN_MAP.md",
      "docs/programmes/NDIS_EXPANSION_DELIVERY_SEQUENCE.md",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Docs/registry only — no product schema; product waves blocked until migrate-from-zero green",
    honesty: {
      implemented: true,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.at_continuity",
    name: "Assistive Technology Continuity",
    programme: "NDIS Expansion",
    implementationPaths: [
      "lib/platform/at-continuity/**",
      "lib/config/at-continuity.ts",
      "docs/programmes/AT_CONTINUITY_WAVE1.md",
      "docs/programmes/NDIS_EXPANSION_DOMAIN_MAP.md",
    ],
    featureFlags: [
      "MAPABLE_AT_CONTINUITY_ENABLED",
      "MAPABLE_AT_LIFECYCLE_ENABLED",
    ],
    maturity: "scaffolded",
    persistenceType: "prisma",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 1 scaffold; MAPABLE_AT_CONTINUITY_ENABLED defaults false; precursor MAPABLE_AT_LIFECYCLE_ENABLED remains false; no clinical suitability SoT; revert 20260720120000_at_continuity_wave1 on non-prod if required",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: true,
      tested: true,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.plan_evidence_navigator",
    name: "Participant Plan and Evidence Navigator",
    programme: "NDIS Expansion",
    implementationPaths: ["docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md"],
    featureFlags: ["MAPABLE_PLAN_EVIDENCE_NAVIGATOR_ENABLED"],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 2 planned — must not determine eligibility or fabricate budgets",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.support_coordination_outcomes",
    name: "Support Coordination Outcomes and Reporting",
    programme: "NDIS Expansion",
    implementationPaths: [
      "lib/support/coordinator/",
      "docs/programmes/NDIS_EXPANSION_PR_RECONCILIATION.md",
    ],
    featureFlags: ["MAPABLE_SUPPORT_COORDINATION_OUTCOMES_ENABLED"],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 3 planned — reuse SC SoT on main; #188/#243 are not landed SoT",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.home_living_navigator",
    name: "Home and Living Navigation and Transition",
    programme: "NDIS Expansion",
    implementationPaths: ["docs/programmes/NDIS_EXPANSION_DOMAIN_MAP.md"],
    featureFlags: [
      "MAPABLE_HOME_LIVING_NAVIGATOR_ENABLED",
      "MAPABLE_HOME_ENABLED",
      "MAPABLE_TRANSITION_HOME_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 4 planned — no SDA/SIL eligibility decisions; AccessPlace for accessibility evidence",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.workforce_assurance",
    name: "Provider Quality and Workforce Assurance",
    programme: "NDIS Expansion",
    implementationPaths: [
      "lib/workforce/readiness/",
      "lib/provider/quality/",
      "docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md",
    ],
    featureFlags: [
      "MAPABLE_WORKFORCE_ASSURANCE_ENABLED",
      "MAPABLE_WORKFORCE_READINESS_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 5 planned — extends WorkerProfile; no scores; no auto-assign or auto-clearance",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.psychosocial_recovery",
    name: "Psychosocial Recovery Continuity",
    programme: "NDIS Expansion",
    implementationPaths: ["docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md"],
    featureFlags: ["MAPABLE_PSYCHOSOCIAL_RECOVERY_ENABLED"],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 6 planned — no crisis prediction, diagnosis, or automatic emergency contact",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.pbs_operations",
    name: "Positive Behaviour Support Practice Operations",
    programme: "NDIS Expansion",
    implementationPaths: [
      "docs/programmes/NDIS_REGULATORY_GATE_MATRIX.md",
      "docs/strategy/BUILD_PARTNER_DEFER.md",
    ],
    featureFlags: [
      "MAPABLE_PBS_OPERATIONS_ENABLED",
      "MAPABLE_PBS_AI_DRAFTING_ENABLED",
      "MAPABLE_RESTRICTIVE_PRACTICE_REGISTER_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 7 high-risk — AI must not conduct FBA, authorise RP, or approve plans",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.early_childhood_workspace",
    name: "Early Childhood Family Workspace",
    programme: "NDIS Expansion",
    implementationPaths: ["docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md"],
    featureFlags: [
      "MAPABLE_EARLY_CHILDHOOD_WORKSPACE_ENABLED",
      "MAPABLE_KIDS_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 8 planned — no diagnosis, ranking scores, or child data for advertising/training",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.allied_health_exchange",
    name: "Allied Health and Home Modification Exchange",
    programme: "NDIS Expansion",
    implementationPaths: [
      "docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md",
      "docs/strategy/BUILD_PARTNER_DEFER.md",
    ],
    featureFlags: [
      "MAPABLE_ALLIED_HEALTH_EXCHANGE_ENABLED",
      "MAPABLE_HOME_MODIFICATION_COORDINATION_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 9 planned — adapters off until partner agreements; MapAble does not prescribe or certify",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.plan_manager_infrastructure",
    name: "Plan Management Infrastructure",
    programme: "NDIS Expansion",
    implementationPaths: [
      "lib/support/plan-manager/",
      "lib/billing/",
      "docs/programmes/NDIS_REGULATORY_GATE_MATRIX.md",
    ],
    featureFlags: [
      "MAPABLE_PLAN_MANAGER_INFRASTRUCTURE_ENABLED",
      "MAPABLE_NDIA_CLAIM_SUBMISSION_ENABLED",
      "MAPABLE_AUTOMATED_PAYMENT_APPROVAL_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 10 planned — Infrastructure for registered PMs; NDIA submit and automated payment approval must remain false",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
  {
    capabilityKey: "ndis.regional_capacity_exchange",
    name: "Regional Thin-Market and Service Continuity Exchange",
    programme: "NDIS Expansion",
    implementationPaths: [
      "docs/programmes/NDIS_EXPANSION_MASTER_PLAN.md",
      "docs/productisation/CAPABILITY_REGISTRY.md",
    ],
    featureFlags: [
      "MAPABLE_REGIONAL_CAPACITY_EXCHANGE_ENABLED",
      "MAPABLE_REGIONAL_CAPACITY_ENABLED",
    ],
    maturity: "documented",
    persistenceType: "none",
    productionClaimStatus: "unsupported",
    rollbackNotes:
      "Wave 11 planned — CapacityBlock ≠ exchange; no scores, pay-to-rank, or auto-allocation",
    honesty: {
      implemented: false,
      featureEnabled: false,
      connected: false,
      durable: false,
      tested: false,
      piloted: false,
      externallyIntegrated: false,
      productionSupported: false,
    },
  },
];
