import type { PilotDependencySeed, PilotPrSeed } from "@/lib/platform/convergence-os/types";

/** File-verified pilot PR set from ConvergenceOS plan §29 / §34. */
export const PILOT_PR_SEEDS: PilotPrSeed[] = [
  {
    number: 285,
    title: "docs(ndis-gateway): Wave 0 repository audit and integration map",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/ndis-gateway-audit-4203",
    mergeable: "MERGEABLE",
    changedFiles: 5,
    additions: 1346,
    classLabel: "docs_only",
    collisionRisk: "low",
    recommendedMergeOrder: 0,
    warningLabels: [],
    url: "https://github.com/ausdisau/mapableau-new/pull/285",
    behindMain: 0,
    dropsIndoor: false,
    schemaChanged: false,
  },
  {
    number: 279,
    title: "feat(programmes): shared programme foundation (Prompt 0)",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/shared-programme-foundation-7fa5",
    mergeable: "MERGEABLE",
    changedFiles: 36,
    classLabel: "foundation",
    collisionRisk: "medium",
    domainsAffected: ["missions.case_mission_adapter", "governance.programme_source"],
    migrationsAdded: ["20260716120000_shared_programme_foundation"],
    recommendedMergeOrder: 1,
    warningLabels: ["rebase_preserve_indoor", "migration_ts_vs_indoor"],
    url: "https://github.com/ausdisau/mapableau-new/pull/279",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 278,
    title: "feat(platform-assurance): standards version registry and worker trust gaps",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/platform-assurance-registry-ccbf",
    mergeable: "MERGEABLE",
    changedFiles: 33,
    classLabel: "registry",
    collisionRisk: "high",
    domainsAffected: ["assurance.platform"],
    recommendedMergeOrder: 2,
    warningLabels: ["stale_base_drops_indoor", "source_registry_overlap_279"],
    url: "https://github.com/ausdisau/mapableau-new/pull/278",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 286,
    title: "feat(ndis-gateway): Wave 1 canonical domain and funding facades",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/ndis-canonical-domain-4203",
    mergeable: "MERGEABLE",
    changedFiles: 24,
    classLabel: "lib_compat",
    collisionRisk: "low",
    domainsAffected: ["ndis.gateway", "finance.funding"],
    recommendedMergeOrder: 3,
    warningLabels: [],
    url: "https://github.com/ausdisau/mapableau-new/pull/286",
    behindMain: 0,
    dropsIndoor: false,
    schemaChanged: false,
    explicitNonGoals: "No Prisma schema changes in Wave 1",
  },
  {
    number: 252,
    title: "feat(careos): platform completion — canonical mission SoR and consolidation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "agent/careos-national-platform",
    headBranch: "agent/careos-platform-completion",
    mergeable: "UNKNOWN",
    changedFiles: 38,
    classLabel: "canonical_mission",
    collisionRisk: "critical",
    domainsAffected: ["missions.careos_mission", "governance.outbox"],
    prismaModelsAdded: ["CareOSMission", "CareOSMissionEvent", "CloudEventOutbox"],
    recommendedMergeOrder: 4,
    warningLabels: [
      "defer_until_rebase_on_main",
      "careos_mission_sor",
      "behind_main_indoor",
    ],
    url: "https://github.com/ausdisau/mapableau-new/pull/252",
    behindMain: 17,
    aheadOfMain: 231,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 281,
    title: "feat(vault): Personal Access Vault reference registry and hybrid pillars",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/personal-access-vault-registry-77ea",
    mergeable: "MERGEABLE",
    changedFiles: 98,
    classLabel: "vault",
    collisionRisk: "high",
    domainsAffected: ["vault.personal_access"],
    prismaModelsAdded: ["PersonalVault", "VaultItem", "VaultDevice", "VaultExport"],
    migrationsAdded: ["20260716140000_personal_access_vault"],
    recommendedMergeOrder: 5,
    warningLabels: ["merge_before_rightsos", "migration_ts_20260716140000"],
    url: "https://github.com/ausdisau/mapableau-new/pull/281",
    behindMain: 0,
    dropsIndoor: false,
    schemaChanged: true,
  },
  {
    number: 280,
    title: "feat: MapAble RightsOS — purpose registry, shadow firewall, and Rights Centre",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/rightsos-purpose-registry-shadow-aa10",
    mergeable: "MERGEABLE",
    changedFiles: 74,
    classLabel: "rightsos",
    collisionRisk: "critical",
    domainsAffected: ["rights.purpose", "vault.personal_access"],
    prismaModelsAdded: [
      "RightsPurpose",
      "PersonalVault",
      "PersonalVaultItem",
      "VaultDevice",
      "VaultExport",
    ],
    recommendedMergeOrder: 6,
    warningLabels: [
      "depends_on_vault_281",
      "duplicate_vault_models",
      "stale_base_drops_indoor",
    ],
    url: "https://github.com/ausdisau/mapableau-new/pull/280",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 284,
    title: "feat(civic): Civic Asset Registry and Static Accessibility Projection",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/civic-asset-registry-static-projection-585f",
    mergeable: "MERGEABLE",
    changedFiles: 54,
    classLabel: "civic",
    collisionRisk: "medium",
    domainsAffected: ["places.civic_asset"],
    prismaModelsAdded: ["CivicAsset", "CivicAssetVersion", "CivicSource"],
    migrationsAdded: ["20260716160000_civic_asset_registry"],
    recommendedMergeOrder: 7,
    warningLabels: ["related_asset_domain_vs_a11yops"],
    url: "https://github.com/ausdisau/mapableau-new/pull/284",
    behindMain: 0,
    dropsIndoor: false,
    schemaChanged: true,
  },
  {
    number: 282,
    title: "feat(accessibility-ops): Asset Registry and Shadow Rule Evaluation",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/accessibility-ops-asset-registry-4343",
    mergeable: "MERGEABLE",
    changedFiles: 59,
    classLabel: "accessibility_ops",
    collisionRisk: "high",
    domainsAffected: ["places.accessibility_asset"],
    prismaModelsAdded: ["AccessibilityAsset", "AccessibilityRule"],
    migrationsAdded: ["20260716140000_accessibility_ops_registry"],
    recommendedMergeOrder: 8,
    warningLabels: ["migration_ts_20260716140000", "after_civic_284"],
    url: "https://github.com/ausdisau/mapableau-new/pull/282",
    behindMain: 0,
    dropsIndoor: false,
    schemaChanged: true,
  },
  {
    number: 276,
    title: "feat(transport): production claims for verification, evidence review, and routing",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/transport-production-claims-5a9f",
    mergeable: "MERGEABLE",
    changedFiles: 28,
    classLabel: "transport_claims",
    collisionRisk: "medium",
    domainsAffected: ["transport.trip"],
    recommendedMergeOrder: 10,
    warningLabels: ["prefer_over_transport_mvp_283", "stale_drops_indoor"],
    url: "https://github.com/ausdisau/mapableau-new/pull/276",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: false,
  },
  {
    number: 283,
    title: "feat(transport): MapAble Transport MVP adapted to Next.js/Prisma",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/mapable-transport-mvp-c42d",
    mergeable: "MERGEABLE",
    changedFiles: 63,
    classLabel: "transport_mvp",
    collisionRisk: "critical",
    domainsAffected: ["transport.trip", "transport.booking_legacy"],
    migrationsAdded: ["20260716140000_transport_mvp_domain"],
    recommendedMergeOrder: 99,
    warningLabels: [
      "rebuild_or_adapter_candidate",
      "migration_ts_20260716140000",
      "conflicts_with_transport_trip_canonical",
    ],
    url: "https://github.com/ausdisau/mapableau-new/pull/283",
    schemaChanged: true,
  },
  {
    number: 266,
    title: "feat(access-intelligence): Wave 0–5 production expansion",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/ai-canonical-place-binding-6ea8",
    mergeable: "CONFLICTING",
    changedFiles: 289,
    classLabel: "access_intelligence_base",
    collisionRisk: "critical",
    domainsAffected: ["places.ai_access_place", "participant.access_passport"],
    prismaModelsAdded: ["AiAccessPlace", "AiAccessPassport", "AiLivingTwinMeta"],
    recommendedMergeOrder: 8,
    warningLabels: [
      "conflicting",
      "drops_indoor",
      "do_not_merge_as_is",
      "aura_stack_base",
    ],
    url: "https://github.com/ausdisau/mapableau-new/pull/266",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 273,
    title: "Access Intelligence Production Expansion (Waves 0–5)",
    state: "OPEN",
    isDraft: false,
    baseBranch: "main",
    headBranch: "cursor/access-intelligence-expansion-6ea8",
    mergeable: "CONFLICTING",
    changedFiles: 321,
    classLabel: "access_intelligence",
    collisionRisk: "critical",
    domainsAffected: ["places.ai_access_place", "participant.access_passport"],
    recommendedMergeOrder: 8,
    warningLabels: ["conflicting", "duplicates_266", "drops_indoor"],
    url: "https://github.com/ausdisau/mapableau-new/pull/273",
    behindMain: 5,
    dropsIndoor: true,
    schemaChanged: true,
  },
  {
    number: 267,
    title: "feat(aura): Wave 1 read-only MapAble AURA vertical slice",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/ai-canonical-place-binding-6ea8",
    headBranch: "cursor/mapable-aura-wave1-6ea8",
    mergeable: "MERGEABLE",
    changedFiles: 51,
    classLabel: "aura_stacked",
    collisionRisk: "critical",
    domainsAffected: ["aura.proposal", "missions.careos_mission"],
    prismaModelsAdded: ["AuraMissionExtension", "CareOSMission", "AuraCapabilityLease"],
    migrationsAdded: ["20260716200000_mapable_aura_wave1"],
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w1", "adds_careos_mission_ddl", "depends_on_266"],
    url: "https://github.com/ausdisau/mapableau-new/pull/267",
    schemaChanged: true,
    dropsIndoor: true,
  },
  {
    number: 268,
    title: "feat(aura): Wave 2 counterfactual resilience, Stop, audit replay, offline packs",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/mapable-aura-wave1-6ea8",
    headBranch: "cursor/mapable-aura-wave2-6ea8",
    classLabel: "aura_stacked",
    collisionRisk: "high",
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w2"],
    url: "https://github.com/ausdisau/mapableau-new/pull/268",
    schemaChanged: true,
    dropsIndoor: true,
  },
  {
    number: 269,
    title: "feat(aura): Wave 3 immutable proposals, shadow review, execution guard",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/mapable-aura-wave2-6ea8",
    headBranch: "cursor/mapable-aura-wave3-6ea8",
    classLabel: "aura_stacked",
    collisionRisk: "high",
    domainsAffected: ["aura.proposal"],
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w3"],
    url: "https://github.com/ausdisau/mapableau-new/pull/269",
    schemaChanged: true,
    dropsIndoor: true,
  },
  {
    number: 272,
    title: "feat(aura): Wave 4 approved execution + Wave 5 memory/calibration",
    state: "OPEN",
    isDraft: false,
    baseBranch: "cursor/mapable-aura-wave3-6ea8",
    headBranch: "cursor/mapable-aura-wave4-5-6ea8",
    classLabel: "aura_stacked",
    collisionRisk: "critical",
    domainsAffected: ["aura.execution"],
    prismaModelsAdded: ["AuraExecutionApproval", "AuraExecutionReceipt"],
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w4_5", "execution_flags_must_default_false"],
    url: "https://github.com/ausdisau/mapableau-new/pull/272",
    schemaChanged: true,
    dropsIndoor: true,
  },
  {
    number: 275,
    title: "feat(aura): Wave 6 Pocket + Wave 7 journey world model and Guardian",
    state: "OPEN",
    isDraft: false,
    baseBranch: "cursor/mapable-aura-wave4-5-6ea8",
    headBranch: "cursor/mapable-aura-wave6-7-6ea8",
    classLabel: "aura_stacked",
    collisionRisk: "high",
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w6_7", "fixture_in_memory"],
    knownLimitations: "Journey world / Guardian largely in-memory on this PR",
    url: "https://github.com/ausdisau/mapableau-new/pull/275",
    schemaChanged: false,
    dropsIndoor: true,
  },
  {
    number: 277,
    title: "feat(aura): Wave 7 gap-fill + Waves 8–10 portable trust, reliability, physical demo",
    state: "OPEN",
    isDraft: true,
    baseBranch: "cursor/mapable-aura-wave6-7-6ea8",
    headBranch: "cursor/mapable-aura-wave7-10-6ea8",
    classLabel: "aura_stacked",
    collisionRisk: "high",
    recommendedMergeOrder: 9,
    warningLabels: ["stacked_w7_10", "careos_mission_on_tip"],
    url: "https://github.com/ausdisau/mapableau-new/pull/277",
    schemaChanged: true,
    dropsIndoor: true,
  },
  {
    number: 287,
    title: "feat(continuity-os): Life Events registry and service recovery control plane",
    state: "OPEN",
    isDraft: true,
    baseBranch: "main",
    headBranch: "cursor/continuity-os-life-event-registry-9cd2",
    classLabel: "continuity",
    collisionRisk: "critical",
    domainsAffected: ["missions.careos_mission"],
    prismaModelsAdded: ["CareOSMission", "CareOSMissionEvent", "LifeEventMissionExtension"],
    migrationsAdded: ["20260716210000_continuity_os_foundation"],
    recommendedMergeOrder: 11,
    warningLabels: [
      "second_careos_mission_ddl",
      "rebase_to_extension_only",
    ],
    url: "https://github.com/ausdisau/mapableau-new/pull/287",
    schemaChanged: true,
  },
];

export const PILOT_DEPENDENCY_SEEDS: PilotDependencySeed[] = [
  { edgeType: "based_on", fromPr: 267, toPr: 266, evidence: "PR base branch ai-canonical-place-binding" },
  { edgeType: "based_on", fromPr: 268, toPr: 267, evidence: "Stacked AURA Wave2 on Wave1" },
  { edgeType: "based_on", fromPr: 269, toPr: 268, evidence: "Stacked AURA Wave3 on Wave2" },
  { edgeType: "based_on", fromPr: 272, toPr: 269, evidence: "Stacked AURA Wave4-5 on Wave3" },
  { edgeType: "based_on", fromPr: 275, toPr: 272, evidence: "Stacked AURA Wave6-7 on Wave4-5" },
  { edgeType: "based_on", fromPr: 277, toPr: 275, evidence: "Stacked AURA Wave7-10 on Wave6-7" },
  { edgeType: "should_merge_before", fromPr: 285, toPr: 286, evidence: "NDIS docs before facades" },
  { edgeType: "should_merge_before", fromPr: 281, toPr: 280, evidence: "Vault SoR before RightsOS; PersonalVault collision" },
  { edgeType: "should_merge_before", fromPr: 284, toPr: 282, evidence: "Civic then AccessibilityOps with AccessPlace FK rules" },
  { edgeType: "should_merge_before", fromPr: 279, toPr: 278, evidence: "Programme foundation before assurance source link" },
  { edgeType: "depends_on", fromPr: 267, toPr: 252, evidence: "AURA tip CareOSMission DDL must come from CareOS SoR" },
  { edgeType: "depends_on", fromPr: 287, toPr: 252, evidence: "Continuity must not redefine CareOSMission" },
  { edgeType: "conflicts_with", fromPr: 281, toPr: 280, evidence: "PersonalVault/VaultDevice/VaultExport dual-define" },
  { edgeType: "conflicts_with", fromPr: 266, toPr: 273, evidence: "Sibling Access Intelligence expansions both CONFLICTING" },
  { edgeType: "conflicts_with", fromPr: 283, toPr: 276, evidence: "Transport MVP rewrite vs Trip production claims" },
  { edgeType: "requires_migration", fromPr: 281, toPr: 282, evidence: "Shared migration timestamp 20260716140000" },
  { edgeType: "requires_migration", fromPr: 282, toPr: 283, evidence: "Shared migration timestamp 20260716140000" },
  { edgeType: "should_rebase_after", fromPr: 267, toPr: 266, evidence: "Rebuild AI base preserving indoor before AURA stack" },
  { edgeType: "duplicates", fromPr: 267, toPr: 252, evidence: "CareOSMission model added on AURA and CareOS tips" },
  { edgeType: "duplicates", fromPr: 287, toPr: 252, evidence: "CareOSMission model added on Continuity and CareOS" },
  { edgeType: "requires_manual_review", fromPr: 252, toPr: 279, evidence: "CareOSMission vs CaseMissionAdapter cutover" },
];
