import type { SentinelState } from "./contracts";

const TRANSITIONS: Record<SentinelState, readonly SentinelState[]> = {
  OBSERVING: [
    "VERIFICATION_REQUIRED",
    "PAUSED",
    "PARTICIPANT_CONFIRMATION_REQUIRED",
    "HUMAN_REVIEW_REQUIRED",
    "COMPLAINT_HANDOFF",
    "INCIDENT_TRIAGE_HANDOFF",
    "CONTINUING",
    "RESOLVED",
    "SECURITY_QUARANTINE",
    "DEGRADED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  VERIFICATION_REQUIRED: [
    "PAUSED",
    "CONTINUING",
    "HUMAN_REVIEW_REQUIRED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  PAUSED: [
    "VERIFICATION_REQUIRED",
    "PARTICIPANT_CONFIRMATION_REQUIRED",
    "HUMAN_REVIEW_REQUIRED",
    "RECOVERY_PROPOSED",
    "COMPLAINT_HANDOFF",
    "INCIDENT_TRIAGE_HANDOFF",
    "CONTINUING",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  PARTICIPANT_CONFIRMATION_REQUIRED: [
    "RECOVERY_PROPOSED",
    "APPROVED_ACTION_PENDING",
    "CONTINUING",
    "HUMAN_REVIEW_REQUIRED",
    "STOPPED_BY_PARTICIPANT",
    "FAILED_SAFE",
  ],
  HUMAN_REVIEW_REQUIRED: [
    "RECOVERY_PROPOSED",
    "APPROVED_ACTION_PENDING",
    "CONTINUING",
    "COMPLAINT_HANDOFF",
    "INCIDENT_TRIAGE_HANDOFF",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  COMPLAINT_HANDOFF: [
    "CONTINUING",
    "RESOLVED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  INCIDENT_TRIAGE_HANDOFF: [
    "CONTINUING",
    "RESOLVED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  RECOVERY_PROPOSED: [
    "PARTICIPANT_CONFIRMATION_REQUIRED",
    "APPROVED_ACTION_PENDING",
    "HUMAN_REVIEW_REQUIRED",
    "PAUSED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  APPROVED_ACTION_PENDING: [
    "CONTINUING",
    "PAUSED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  CONTINUING: [
    "OBSERVING",
    "RESOLVED",
    "PAUSED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  RESOLVED: [],
  STOPPED_BY_PARTICIPANT: [],
  SECURITY_QUARANTINE: ["HUMAN_REVIEW_REQUIRED", "FAILED_SAFE", "RESOLVED"],
  DEGRADED: [
    "OBSERVING",
    "PAUSED",
    "FAILED_SAFE",
    "STOPPED_BY_PARTICIPANT",
  ],
  FAILED_SAFE: ["HUMAN_REVIEW_REQUIRED", "STOPPED_BY_PARTICIPANT"],
};

export function canTransitionSentinelState(
  from: SentinelState,
  to: SentinelState,
): boolean {
  return TRANSITIONS[from].includes(to);
}

export function assertSentinelTransition(
  from: SentinelState,
  to: SentinelState,
): void {
  if (!canTransitionSentinelState(from, to)) {
    throw new Error(`SENTINEL_INVALID_STATE_TRANSITION:${from}:${to}`);
  }
}
