import type { ProviderProfile } from "./types";

export const MOCK_PROVIDER_PROFILES: ProviderProfile[] = [
  {
    id: "mock-1",
    name: "Harbour Support Co.",
    category: "Personal care",
    suburb: "Parramatta",
    postcode: "2150",
    distanceLabel: "4.2 km",
    rating: 4.7,
    reviews: 128,
    responseTime: "Usually replies in 2 hours",
    funding: "NDIS registered",
    accessNeeds: ["Wheelchair access", "Hoist trained"],
    description:
      "Daily living and community access with transport coordination for western Sydney participants.",
    availability: "Available this week",
    featured: true,
    verified: true,
    coordinates: { lat: -33.815, lng: 151.0 },
    slug: "harbour-support-co",
  },
  {
    id: "mock-2",
    name: "Bright Steps Therapy",
    category: "Therapy",
    suburb: "Footscray",
    postcode: "3011",
    distanceLabel: "12 km",
    rating: 4.5,
    reviews: 42,
    responseTime: "Usually replies same day",
    funding: "Plan-managed",
    accessNeeds: ["Low sensory", "Auslan"],
    description: "OT and speech pathways with low-sensory clinic rooms and Auslan-friendly sessions.",
    availability: "Enquire for availability",
    featured: false,
    verified: true,
    coordinates: { lat: -37.8, lng: 144.9 },
    slug: "bright-steps-therapy",
  },
  {
    id: "mock-3",
    name: "Northside Community Transport",
    category: "Transport",
    suburb: "Chatswood",
    postcode: "2067",
    distanceLabel: "8 km",
    rating: 4.8,
    reviews: 210,
    responseTime: "Usually replies in 2 hours",
    funding: "NDIS registered",
    accessNeeds: ["Wheelchair access"],
    description: "Wheelchair accessible vehicles with trained drivers across Sydney north.",
    availability: "Available this week",
    featured: true,
    verified: true,
    coordinates: { lat: -33.796, lng: 151.18 },
  },
  {
    id: "mock-4",
    name: "Inclusive Works Hub",
    category: "Employment",
    suburb: "Adelaide",
    postcode: "5000",
    distanceLabel: "Remote",
    rating: 4.3,
    reviews: 18,
    responseTime: "Response time varies",
    funding: "Self-managed",
    accessNeeds: ["Complex support"],
    description: "Employment coaching with workplace access planning and employer liaison.",
    availability: "Telehealth slots open",
    featured: false,
    verified: false,
  },
];

export const SAMPLE_SPONSORED_PARTNERS = [
  {
    id: "sp-1",
    title: "Accessible Transport Alliance",
    description:
      "Community partner offering regional transport planning resources — not a verified provider recommendation.",
    label: "Community partner" as const,
  },
];
